hazelcast/hazelcast-jet

hazelcast-jet/src/test/java/com/hazelcast/jet/DagTest.java
Added tests for basic directed acyclic graph validations
=> added DAG unit test

hazelcast-jet/src/main/java/com/hazelcast/jet/api/container/task/TaskProcessor.java, hazelcast-jet/src/main/java/com/hazelcast/jet/api/data/io/SocketReader.java, hazelcast-jet/src/main/java/com/hazelcast/jet/impl/container/task/DefaultContainerTask.java, hazelcast-jet/src/main/java/com/hazelcast/jet/impl/container/task/nio/AbstractNetworkTask.java, hazelcast-jet/src/main/java/com/hazelcast/jet/impl/container/task/nio/DefaultSocketReader.java, hazelcast-jet/src/main/java/com/hazelcast/jet/impl/container/task/nio/DefaultSocketThreadAcceptor.java, hazelcast-jet/src/main/java/com/hazelcast/jet/impl/container/task/nio/DefaultSocketWriter.java, hazelcast-jet/src/main/java/com/hazelcast/jet/impl/container/task/processors/ConsumerTaskProcessor.java, hazelcast-jet/src/main/java/com/hazelcast/jet/impl/container/task/processors/ProducerTaskProcessor.java, hazelcast-jet/src/main/java/com/hazelcast/jet/impl/container/task/processors/SimpleTaskProcessor.java, hazelcast-jet/src/main/java/com/hazelcast/jet/impl/statemachine/application/DefaultApplicationStateMachineRequestProcessor.java, hazelcast-jet/src/main/java/com/hazelcast/jet/impl/statemachine/applicationmaster/processors/FinalizeApplicationProcessor.java, hazelcast-jet/src/main/java/com/hazelcast/jet/spi/CombinedJetException.java, hazelcast-jet/src/main/java/com/hazelcast/jet/spi/config/JetApplicationConfig.java, hazelcast-jet/src/test/java/com/hazelcast/jet/SimpleMultiNodeTestSuite.java, hazelcast-jet/src/test/java/com/hazelcast/jet/SimpleSingleNodeTestSuite.java
1) Serious transport bug has been fixed
2) Serious race condition on reading between containers has been fixed
=> 1) Serious transport bug has been fixed

hazelcast-jet-language/pom.xml, pom.xml
1) New maven module hazelcast-jet-language has been added
2) Root pom has been added
=> Maven module restructure

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadFileStreamP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadFileStreamPTest.java
The processor is still barely useful, its weaknesses are at least better documented.
Fixes #298
=> Fix behavior and test of ReadFileStreamP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/DAG.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Edge.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetInstanceImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/ExecuteJobOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/StreamUtil.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/collectors/AbstractHazelcastCollector.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/collectors/DistributedCollectorImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/collectors/DistributedStringJoiner.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/collectors/HazelcastGroupingMapCollector.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/collectors/HazelcastListCollector.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/collectors/HazelcastMapCollector.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/collectors/HazelcastMergingMapCollector.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/AbstractPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/DistinctPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/LimitPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/PeekPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/SortPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/source/ListSourcePipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/source/MapSourcePipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/terminal/Matcher.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/terminal/Reducer.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadFileStreamPTest.java
Before PR:
```
Vertices {sink=Vertex sink, accumulator=Vertex accumulator, source=Vertex source, combiner=Vertex combiner, doc-lines=Vertex doc-lines, tokenizer=Vertex tokenizer}
Edges [(source, 0) -> (doc-lines, 0), (tokenizer, 0) -> (accumulator, 0), (combiner, 0) -> (sink, 0), (doc-lines, 0) -> (tokenizer, 0), (accumulator, 0) -> (combiner, 0)]
```
After PR:
```
dag
.vertex("source").localParallelism(1)
.vertex("doc-lines").localParallelism(1)
.vertex("tokenize")
.vertex("reduce")
.vertex("combine")
.vertex("sink")
.edge(between("source", "doc-lines"))
.edge(between("doc-lines", "tokenize"))
.edge(between("tokenize", "reduce").partitioned(?))
.edge(between("reduce", "combine").partitioned(?).distributed())
.edge(between("combine", "sink"))
```
=> Better DAG.toString()

pom.xml
(sonar 2.6->2.7.1, jacoco 0.7.4.201502262128->0.7.9)
=> upgraded sonar and jacoco plugins to newer versions 

hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/TransformPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/processor/TransformP.java
This PR enables code like the following:
```java
Stream<X> stream  = ...;
Stream<Y> branch1 = stream.map(toY);
Stream<X> branch2 = stream.filter(predicate);
```
=> Allow branching of the j.u.s pipeline

hazelcast-jet-client-protocol/pom.xml, hazelcast-jet-core/src/test/java/com/hazelcast/jet/benchmark/WordCountTest.java
Rename processors to match their actual function
=> Clean up twoPhaseAggregation test

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadSocketTextStreamP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadSocketTextStreamPTest.java
=> ReadSocketTextStreamP should immediately emit items after reading

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetSerializerHook.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/connector/hadoop/ReadHdfsP.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/connector/hadoop/SerializableJobConf.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/connector/hadoop/WritableSerializerHook.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/connector/hadoop/WritableSerializerHooks.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/connector/hadoop/WriteHdfsP.java, hazelcast-jet-hadoop/src/main/resources/META-INF/services/com.hazelcast.SerializerHook, hazelcast-jet-hadoop/src/test/java/com/hazelcast/jet/connector/hadoop/ReadHdfsPTest.java, hazelcast-jet-hadoop/src/test/java/com/hazelcast/jet/connector/hadoop/WriteHdfsPTest.java
* Additional javadocs added
* Added support for serializing some primitive types
=> jet-hadoop module improvements

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/XmlJetConfigLocator.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/config/XmlConfigTest.java, hazelcast-jet-core/src/test/resources/hazelcast-jet-member-test.xml
Contains some more tests, one of the added tests is marked as `@Ignore` as it needs reviewed to see if is it a valid test to attempt.
=> Wrong configuration file is used for IMDG when Jet config present in classpath

hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/connector/kafka/ReadKafkaP.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/connector/kafka/KafkaTestSupport.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/connector/kafka/ReadKafkaPTest.java
added random groupId for the test
=> In case of highwater, seek to the latest offset

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetClientInstanceImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetInstanceImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/ResourceIterator.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/ResourceIteratorTest.java
It had issues:
- single use ill-defined Util.read() method
- improper use of InputStream.available() to detect EOF
- didn't handle empty files (not a requirement, but anyway)
=> Fix ResourceIterator and add test

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetSerializerHook.java, hazelcast-jet-core/src/main/resources/META-INF/services/com.hazelcast.SerializerHook, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/HazelcastConnectorIntegrationTest.java
also added a wrapper for cache-reader
fixes #366
=> Removed Cache.Entry serializer

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadSocketTextStreamP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadSocketTextStreamPTest.java
Also introduced WriteSocketTextStreamP
=> Added multiple socket suport to ReadSocketTextStreamP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/DistributedDoubleStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/DistributedIntStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/DistributedLongStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/DistributedStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/StreamUtil.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/AbstractPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/DoublePipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/IntPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/LongPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/StreamContext.java, hazelcast-jet-core/src/test/java/deployment/AbstractDeploymentTest.java
fixes https://github.com/hazelcast/hazelcast-jet/issues/353
=> Added configuration option to DistributedStream

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorP.java, pom.xml
changed hazelcast-version to 3.8.2-SNAPSHOT
=> Removed wrapper for CacheReader

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteFileP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteFilePTest.java
A processor to write to single file, one item.toString() per line.
=> Add WriteFileP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/BlockingProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/CooperativeProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/ArrayDequeOutbox.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/CooperativeProcessorTaskletTest.java
Ensure DONE_ITEM submitted only once
=> Fix bug in processor tasklets

checkstyle/checkstyle.xml, hazelcast-jet-all/src/main/java/com/hazelcast/jet/server/StartServer.java, hazelcast-jet-cascading/src/main/java/com/hazelcast/jet/cascading/planner/rule/tez/expression/BalanceGroupSplitHashJoinExpression.java, hazelcast-jet-cascading/src/main/java/com/hazelcast/jet/cascading/planner/rule/tez/expression/BalanceGroupSplitSpliceExpression.java, hazelcast-jet-cascading/src/main/java/com/hazelcast/jet/cascading/planner/rule/tez/expression/BalanceHashJoinSameSourceExpression.java, hazelcast-jet-cascading/src/main/java/com/hazelcast/jet/cascading/planner/rule/tez/expression/BalanceJoinSplitExpression.java, hazelcast-jet-cascading/src/main/java/com/hazelcast/jet/cascading/planner/rule/tez/expression/BalanceSplitSplitToStreamedHashJoinExpression.java, hazelcast-jet-cascading/src/main/java/com/hazelcast/jet/cascading/runtime/JetBoundaryStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/DAG.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Distributed.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/LiveOperationRegistry.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamTextSocketP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteFileP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/CustomClassLoadedObject.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/ExecuteOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/ExceptionUtil.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/DistributedCollectors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/MapDecorator.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/connector/hadoop/ReadHdfsP.java
Non-semantic change that sets CheckStyle's right margin to 123 and fixes the resulting errors. This is a backport of the same change on the `windowing` branch.
=> Fix right margin

hazelcast-jet-core/src/main/java/com/hazelcast/jet/AbstractProcessor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Traversers.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteBufferedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ReceiverTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetSerializerHook.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/GroupByFrameP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/SlidingWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/WindowOperation.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/ProcessorsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteBufferedPTest.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/connector/hadoop/WriteHdfsP.java
=> Make passing of punctuation default

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteBufferedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteFileP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteBufferedPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteFilePTest.java
User gives just the directory name, files are created with global index.
=> Simpler file name in WriteFileP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Distributed.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/LoggingUtil.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/distributed/DistributedComparators.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/ComparatorTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesP_integrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/impl/CacheDecoratorTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/impl/distributed/DistributedComparatorsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/impl/distributed/DistributedDoubleSummaryStatisticsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/impl/distributed/DistributedIntSummaryStatisticsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/impl/distributed/DistributedLongSummaryStatisticsTest.java
Also simplify code in `NullComparator` and `StreamFilesP`
=> Improve test coverage

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteFileP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteFilePTest.java, pom.xml
This reverts commit 903d71bb45617de6ec77de670682e78da7437bdc.
=> Remove suffix from WriteFileP's output

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Punctuation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetSerializerHook.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/SkewReductionPolicy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/TimestampHistory.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/Frame.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/InsertPunctuationP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/PunctuationPolicies.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/PunctuationPolicy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/SessionWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/TimestampedEntry.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/WindowDefinition.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/WindowingProcessor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/WindowingProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/package-info.java, hazelcast-jet-core/src/main/resources/META-INF/services/com.hazelcast.SerializerHook, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/init/JetSerializerHookTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/SkewReductionPolicyTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/TimestampHistoryTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/InsertPunctuationPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/LimitingLagAndDelayTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/LimitingLagAndLullTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/PunctuationPolicyTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/StreamingTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/WindowDefinitionTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/WindowingProcessors_integrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/WindowingProcessors_sessionWindowTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/WindowingProcessors_slidingWindowStage1Test.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/WindowingProcessors_slidingWindowTest.java
Also renames `Frame` to `TimestampedEntry`
=> Use "timestamp" instead of "seq"

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteFileP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteFilePTest.java
=> Add formatter to WriteFileP

hazelcast-jet-core/src/test/java/com/hazelcast/jet/JetInstanceTest.java
I changed some raw string to static value in test case
=> Raw string to static value

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedFunctions.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteSystemOutP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/PeekWrappedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/WrappingProcessorMetaSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/WrappingProcessorSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/DistributedCollector.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/DistributedCollectors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/DistributedStream.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/ProcessorsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/Processors_peekTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteSystemOutPTest.java
=> Add support for debugging

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteLoggerP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteFilePTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteLoggerPTest.java
- Rename `WriteSystemOutP` to `WriteLoggerP`
- make `charset` and `toStringF` non-null for `writeFile`
- improve javadoc
=> Add minor improvements to Processors

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/InstanceConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/WindowOperations.java
Little overhead compared to consequences of possible overflow.
=> Use Math.addExact in average operations

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadIListP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/EdgeTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/ExceptionHandlingTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/VertexTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/WindowingProcessors_integrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/benchmark/BackpressureTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/benchmark/WordCountTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamTextSocketPTest.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/connector/hadoop/ReadHdfsP.java
Make it same style as other processors
=> Add static method for NoopP processor

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SessionWindowP.java
Using `treeMap = treeMap.tailMap(...)` seemingly evicts head items from
the map, but they still remain in the underlying map. `tailMap()` is
just a view into the original map.
This change also improves performance as measured by the benchmark in
`SessionWindowPTest`: on my laptop throughput went from 797k to 875k
events/s. This might be due to the fact that `deadlineToKeys` map
contained less elements.
=> Fix eviction in SessionWindowP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/AggregateOperations.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedFunctions.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/AggregateOperationsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/AggregateOperations_accEqualityTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/benchmark/WordCountTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowP_stage1Test.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/Processors_globalAggregationIntegrationTest.java
Also rename `summintToLong` to just `summingLong`, which is in line with `Collectors`
=> Add `mapping` and collection aggregators

hazelcast-jet-all/pom.xml, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/XmlJetConfigBuilder.java
- introduce unshaded profile for pcf tile
- add fix for release version and namespace in config builder
=> introduce unshaded profile for pcf tile

pom.xml
`mvn test -Ptest-enterprise -DargLine="-Dhazelcast.enterprise.license.key=THE_LICENSE"`
=> Add test profile to jet-core for hazelcast-enterprise

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/ExecuteJobOperation.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/JetSplitBrainTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/TopologyChangeMergeClusterTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/TopologyChangeSplitClusterTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/TopologyChangeTest.java, pom.xml
Fix issues and race condition in TopologySplitTest
=> Update Hazelcast version to 3.9 and split brain fixes

hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedBiConsumer.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedBiFunction.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedConsumer.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedFunction.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedPredicate.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedToLongFunction.java
IDEA release 2017.1.4 no longer has the bug
=> Resolve TODO items related to IDEA bug

hazelcast-jet-all/src/main/java/com/hazelcast/jet/server/JetBootstrap.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/JetInstance.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJetInstance.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetCacheManagerImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/DistributedCollectors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/JetCacheManager.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/AbstractStreamTest.java
=> Introduce jet cache manager

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamEventJournalP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/processor/Sources.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/HazelcastConnectorIntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/HazelcastRemoteConnectorTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorPTest.java
depends on https://github.com/hazelcast/hazelcast/pull/11187
=> Introduce stream event journal processor

hazelcast-jet-core/src/main/java/com/hazelcast/jet/AbstractProcessor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/SnapshotOutbox.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorState.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTaskletBase.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/InsertWatermarksP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/PeekWrappedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SessionWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SlidingWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/test/TestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/SnapshottableProcessorTaskletTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ThrottleWrappedP.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaP.java
rename restoreSnapshot -> restoreFromSnapshot and
saveSnapshot -> saveToSnapshot
=> Implement restoreFromSnapshot in AbstractProcessor

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/InstanceConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/XmlJetConfigBuilder.java, hazelcast-jet-core/src/main/resources/hazelcast-jet-config-0.5.xsd, hazelcast-jet-core/src/main/resources/hazelcast-jet-full-example.xml, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/config/XmlConfigTest.java, hazelcast-jet-core/src/test/resources/hazelcast-jet-full.xml, hazelcast-jet-core/src/test/resources/hazelcast-jet-test.xml, hazelcast-jet-core/src/test/resources/hazelcast-jet-with-variables.xml
Renamed job-metadata-backup-count to backup-count
=> Move backup count configuration to InstanceConfig

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/CloseableProcessorSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorMetaSupplierContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorSupplierContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestSupport.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteBufferedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/Contexts.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlanBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AbstractCloseableProcessorSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/ArrayDequeInbox.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteBufferedPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteLoggerPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteSocketTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ArrayDequeInboxTest.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/core/processor/KafkaProcessors.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaP.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/KafkaPartitionAssignerTest.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/KafkaTestSupport.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaPTest.java
Also includes some clean-up in ArrayDequeInbox
=> Fix snapshot in streamKafka & test

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Job.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Pipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJobImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractSubmittedJobImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractTrackedJobImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java
* Change return type of `getFuture()` to `CompletableFuture`
* Various additional Javadoc improvements
=> Add option to disable job restart

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sources.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/InstanceConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/ProcessingGuarantee.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SinkProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SourceProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamEventJournalP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteFileP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlanBuilder.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/HdfsSinks.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/HdfsSources.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/core/processor/HdfsProcessors.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/KafkaSinks.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/KafkaSources.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/core/processor/KafkaProcessors.java
Also includes:
* Add factory methods for streamMap/streamCache to Sources
* Fix interpretation of snapshotIntervalMillis == 0
=> Javadoc for sources/sinks, factory for streamMap

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java
During job initialization or execution start, if the local master address does not match with the expected coordinator address, it is possible that the local node is shutting down and the master address is reset. In this case, we should fail the job with HazelcastInstanceNotActiveException
Fixes https://hazelcast-l337.ci.cloudbees.com/job/Jet-pr-builder/com.hazelcast.jet$hazelcast-jet-core/1951/testReport/junit/com.hazelcast.jet.core/TopologyChangeTest/when_jobParticipantReceivesStaleInitOperation_then_jobRestarts_2_/
=> Fail with HazelcastInstanceNotActiveException during shutdown

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowP_twoStageSnapshotTest.java
This was partially covered via `JobRestartWithSnapshotTest`, this PR adds a specific unit test.
=> Unit test for two-stage sliding window w/snapshot

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/JetClassLoader.java
I've changed `findResource` method of `JetClassloader` so that it does not throw exception. Instead I've created a custom URL which can be used to load the underlying resource. I've also implemented `findResources` method too, which returns enumeration of URLs for the requested resource.
While creating execution plan of the job, `init` method of `ProcessorMetaSupplier` is called. In this `init` method, user may need to use job resources (ReadHdfsP for example), so we should set `JetClassloader` before creating execution plan.
=> JetClassloader fix

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/DataModelSerializerHooks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/Session.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/TimestampedEntry.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SessionWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SlidingWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/SerializerHookConstants.java, hazelcast-jet-core/src/main/resources/META-INF/services/com.hazelcast.SerializerHook, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/Processors_slidingWindowingIntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/datamodel/DataModelSerializerHooksTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SessionWindowPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowP_stage1Test.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowP_twoStageSnapshotTest.java
Also move `Session` and `TimestampedEntry` to `datamodel` package.
=> Add serializer for Session

hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaP.java
=> Added null check to the consumer

hazelcast-jet-core/src/main/java/com/hazelcast/jet/ComputeStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Vertex.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/DiagnosticProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ComputeStageImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/Planner.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteLoggerP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/PeekTransform.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/ComputeStageTest.java
Adds a logging sink and a `ComputeStage.peek()` transform.
=> Pipeline diagnostics

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/SnapshotRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/SnapshotRecord.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java
This method is required for cases where there needs to be some global
clean up after job completion
=> Introduce PMS.complete() method

hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/impl/connector/hadoop/WriteHdfsP.java
fixes https://github.com/hazelcast/hazelcast-jet/issues/565
=> Implement PMS.complete method for WriteHdfsP to commit the job

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java
If a job participant leaves after the local member initializes the execution, the local member can clean up the ExecutionContext object just before it receives the ExecuteOperation from the coordinator. In this case, the local member should fail with TopologyChangedException instead of IllegalStateException.
=> Fix job execution initialization bug

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/PeekWrappedP.java
=> PeekWrappedP changes logger for wrapped processor

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/PeekWrappedP.java
=> [Backport] PeekWrappedP changes logger for wrapped processor (#610)

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sink.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Source.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sources.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Stage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Transform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/EdgeConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/Planner.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/CoGroupTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/FilterTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/FlatMapTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/GroupByTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/HashJoinTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/MapTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/PeekTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/ProcessorTransform.java
Fixes #606
Fixes #614 (Rename source/sink vertex names)
=> Predictable vertex name in pipeline jobs

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sink.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Source.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sources.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Stage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Transform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/EdgeConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/Planner.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/CoGroupTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/FilterTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/FlatMapTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/GroupByTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/HashJoinTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/MapTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/PeekTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/ProcessorTransform.java
Fixes #606
Fixes #614 (Rename source/sink vertex names)
=> [Backport of #616] Predictable vertex name in pipeline jobs

hazelcast-jet-core/src/main/resources/hazelcast-jet-client-default.xml, hazelcast-jet-core/src/main/resources/hazelcast-jet-member-default.xml
=> Change xsd version to 3.9 for hazelcast-jet-member-default.xml and hazelcast-jet-client-default.xml

hazelcast-jet-core/src/main/resources/hazelcast-jet-client-default.xml, hazelcast-jet-core/src/main/resources/hazelcast-jet-member-default.xml
backport of https://github.com/hazelcast/hazelcast-jet/pull/626
=> [BACKPORT] Change xsd version to 3.9 for hazelcast-jet-member-default.xml and hazelcast-jet-client-default.xml

hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperations.java
=> Fix and improve AggregateOperations Javadoc

hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/WriteKafkaP.java
fixes https://github.com/hazelcast/hazelcast-jet/issues/638
=> Add watermark check to WriteKafkaP

hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/WriteKafkaP.java
back-port of https://github.com/hazelcast/hazelcast-jet/pull/639
=> [BACKPORT] Add watermark check to WriteKafkaP

checkstyle/suppressions.xml, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesPTest.java, hazelcast-jet-hadoop/src/test/java/com/hazelcast/jet/impl/connector/hadoop/HdfsTestSupport.java, hazelcast-jet-hadoop/src/test/java/com/hazelcast/jet/impl/connector/hadoop/ReadHdfsPTest.java, hazelcast-jet-hadoop/src/test/java/com/hazelcast/jet/impl/connector/hadoop/WriteHdfsPTest.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/KafkaTestSupport.java, pom.xml
=> Fix Windows build

hazelcast-jet-core/src/main/java/com/hazelcast/jet/JournalInitialPosition.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/JournalInitialSequence.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sources.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Util.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SourceProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamEventJournalP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/Sources_withEventJournalTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/HazelcastConnectorTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/HazelcastRemoteConnectorTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamEventJournalPTest.java
=> Improve map/cache journal defaults

hazelcast-jet-core/src/main/java/com/hazelcast/jet/ComputeStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sources.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Traverser.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Traversers.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SourceProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamEventJournalP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/TraverserTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/TraversersTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/HazelcastConnectorTest.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/HdfsSources.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/impl/connector/hadoop/ReadHdfsP.java, hazelcast-jet-hadoop/src/test/java/com/hazelcast/jet/impl/connector/hadoop/ReadHdfsPTest.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/KafkaSources.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaP.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/KafkaTestSupport.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaPTest.java
Links in javadoc will work when hazelcast/hazelcast#12142 is merged and
pom.xml references imdg 3.10. Fixes #669.
=> Fix & document projection to null

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java
* Minor refactorings to assertTrueEventually() calls
Fixes #676
=> Fix TopologyChangeTest failure

hazelcast-jet-core/src/main/java/com/hazelcast/jet/ComputeStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sources.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Transform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/Processors.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/HdfsSinks.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/HdfsSources.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/KafkaSinks.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/KafkaSources.java
=> Improve javadoc on statelessness, parallelism

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java
=> Do not restart auto-restart disabled job if the master node leaves

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestSupport.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamEventJournalP.java
Co-authored-by: Can Gencer <can@hazelcast.com>
=> Fix saveToSnapshot in EventJournal & improve test

hazelcast-jet-all/pom.xml, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/DecoratorTest.java
Jenkins build: https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/Jet-JDK9/
=> Fixes to get build working on JDK 9

hazelcast-jet-core/src/main/java/com/hazelcast/jet/GenericPredicates.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sources.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/IStreamMap.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/GenericPredicatesTest.java, pom.xml
=> Add generic Predicate factory methods

hazelcast-jet-core/src/test/java/com/hazelcast/jet/PipelineTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/SinksTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/SourcesTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/Sources_withEventJournalTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/TestInClusterSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadFilesPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesP_integrationTest.java
Increased coverage of `Sources.class` to 100%
=> Increased test-coverage around Sources

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/DiagnosticProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteLoggerP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteLoggerPTest.java
=> Log WMs at FINE level in WriteLoggerP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/Networking.java
=> Fix incorrect flow control packet

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sources.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SourceProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamFilesP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadFilesPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesP_integrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesP_readCompleteLineTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/impl/sources/SourcesTest.java
Pipeline API not updated - will be updated when this PR is merged to pipeline branch.
=> Add ability to emit file name from file sources

hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/DataModelSerializerHooks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/SerializerHookConstants.java, hazelcast-jet-core/src/main/resources/META-INF/services/com.hazelcast.SerializerHook, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/pipeline/transform/AggregateTransform_IntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/pipeline/transform/WindowAggregateTransform_IntegrationTest.java
=> Added TimestampedItem serializer hook and increased test coverage 

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestSupport.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SessionWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SlidingWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SessionWindowPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SessionWindowP_failoverTest.java
=> Drop late events in SessionWindowP

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SnapshotFailureTest.java
The test was racy, records for failed snapshots are deleted right after
they are marked as FAILED. This commit rewrites it to check using map
journal where we shouldn't miss events.
Fixes #759
=> Fix intermittent failure in SnapshotFailureTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/WatermarkSourceUtil.java
When using system time, we might coalesce based on one timestamp and
emit another timestamp because the `timestampFn` returns
`currentTimeMillis()`.
Also rename `item` to `event` (unify terminology).
=> Extract timestamp only once in WSU

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/CancellationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ManualRestartTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java
=> Fix a few packet filter calls in tests

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/TransformUsingContextP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java, hazelcast-jet-distribution/src/main/resources/bin/jet-submit.bat, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/KafkaProcessors.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/KafkaSources.java
=> Set Kafka parallelism to 4, javadoc updates

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamEventJournalP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamEventJournalPTest.java
Fixes #741
Should be merged after https://github.com/hazelcast/hazelcast/pull/12429
=> Follow changes in EventJournal

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExceptionHandlingTest.java
=> Fix deserialization error reporting from master

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/DAG.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/WatermarkSourceUtil.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java
Also remove unused parameter `event` in `WSU`.
=> Print actual local parallelism

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamEventJournalP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java
- Mark StreamEventJournalP cooperative
- Higher idle time for blocking processors
- Avoid overflow of idleCount
Related to #775
=> [MERGE TO 0.6.1] Idle CPU usage improvements

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/TaskletExecutionServiceTest.java
Now it stresses the number of work staling occurrences
=> Improve work-stealing test

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamEventJournalP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java
- Mark StreamEventJournalP cooperative
- Higher idle time for blocking processors
- Avoid overflow of idleCount
Related to #775
=> [BACKPORT] Idle CPU usage improvements

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamFilesP.java
Previous behavior wasn't wrong, it was unnecessary.
Fixes #796
=> [BACKPORT] Don't call close eagerly in file sources (#799)

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/TaskletExecutionServiceTest.java
Now it stresses the number of work staling occurrences
=> Improve work-stealing test (backport of #811)

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/BroadcastKey.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorMetaSupplierContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorSupplierContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/BroadcastKeyReference.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionSerializerHooks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/Contexts.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlanBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/VertexDef.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/PeekWrappedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImpl.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ExecutionSerializerHooksTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Blocking.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Snapshots.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Watermarks.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImplTest.java
Also:
* Add test for the problem (snapshot+restore stress test)
* Remove random id from BroadcastKeyReference
* Add memberIndex to Processor.Context
=> Fix snapshot data key uniqueness (backport of #840)

hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/impl/StreamKafkaP.java
=> Handle InterruptException in Kafka.partitionsFor

hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/impl/StreamKafkaP.java
=> Handle InterruptException in Kafka.partitionsFor (#842)

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/WatermarkCoalescer_IntegrationTest.java
=> Fix for test failure in WatermarkCoalescer tests

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java
=> Fix SplitBrainTest failure

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java
=> Fix when_CompleteThrows_then_failJob

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java
Backport of https://github.com/hazelcast/hazelcast-jet/pull/855
Fixes #835
=> [BACKPORT] Fix SplitBrainTest failure

hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/hadoop/impl/ReadHdfsP.java
=> Use hostname equality if reverse lookup throws UnknownHostException exception

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java
=>  Fix when_CompleteThrows_then_failJob (backport of #853)

hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/hadoop/impl/ReadHdfsP.java
backport of https://github.com/hazelcast/hazelcast-jet/pull/858
=> [BACKPORT] Use hostname equality if reverse lookup throws UnknownHostException exception

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/XmlJetConfigBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/WindowGroupAggregateBuilder.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/JetTestInstanceFactory.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/JetConfigTest_loadFromClassPath.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/config/XmlConfigTest.java
=> Util to load JetConfig from classpath or file (backport of #856)

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/SerializableClientConfig.java, hazelcast-jet-core/src/main/resources/hazelcast-jet-client-default.xml, hazelcast-jet-core/src/main/resources/hazelcast-jet-member-default.xml, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/config/XmlConfigTest.java, hazelcast-jet-core/src/test/resources/hazelcast-jet-member-test.xml, hazelcast-jet-distribution/src/main/resources/bin/cluster.sh, hazelcast-jet-spring/src/main/java/com/hazelcast/jet/spring/JetClientBeanDefinitionParser.java, hazelcast-jet-spring/src/main/java/com/hazelcast/jet/spring/JetInstanceBeanDefinitionParser.java, hazelcast-jet-spring/src/test/java/com/hazelcast/jet/spring/TestApplicationContext.java, hazelcast-jet-spring/src/test/resources/com/hazelcast/jet/spring/application-context-jet.xml
This commit can be reverted once hazelcast/hazelcast#11667 is merged and hazelcast/hazelcast#11867 is fixed.
Also see #734
=> Re-add the password field that was removed previously

hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/impl/StreamKafkaP.java
=> Catch InterruptException in `StreamKafkaP.close`

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJetInstance.java
=> Lazy initialisation of JobRepository

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/LoggerSinkTest.java
=> Converted logger-sink test to use mockito

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/InstanceConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/XmlJetConfigBuilder.java, hazelcast-jet-core/src/main/resources/hazelcast-jet-config-0.7.xsd, hazelcast-jet-core/src/main/resources/hazelcast-jet-full-example.xml, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/InstanceConfigTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/config/XmlConfigTest.java, hazelcast-jet-core/src/test/resources/hazelcast-jet-full.xml, hazelcast-jet-core/src/test/resources/hazelcast-jet-test.xml, hazelcast-jet-core/src/test/resources/hazelcast-jet-with-variables.xml, hazelcast-jet-spring/src/main/resources/hazelcast-jet-spring-0.7.xsd, hazelcast-jet-spring/src/test/java/com/hazelcast/jet/spring/TestApplicationContext.java, hazelcast-jet-spring/src/test/resources/com/hazelcast/jet/spring/application-context-jet.xml
=> Remove InstanceConfig.tempDir

hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/CoAggregateOperationBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/WindowAggregateBuilder1.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/WindowGroupAggregateBuilder1.java
Removed leftover duplicate Javadoc
=> Javadoc cleanup in aggregate operation builders

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/SinkBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SinkBuilderTest.java
fixes https://github.com/hazelcast/hazelcast-jet/issues/889
=> Add name to sink builder

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java
=> Fix JobRestartWithSnapshotTest.stressTest failure

hazelcast-jet-avro/pom.xml, hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/AvroProcessors.java, hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/AvroSinks.java, hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/AvroSources.java, hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/package-info.java, hazelcast-jet-avro/src/test/java/com/hazelcast/jet/avro/AvroSinkTest.java, hazelcast-jet-avro/src/test/java/com/hazelcast/jet/avro/AvroSourceTest.java, hazelcast-jet-avro/src/test/java/com/hazelcast/jet/avro/model/SpecificUser.java, hazelcast-jet-avro/src/test/java/com/hazelcast/jet/avro/model/User.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SourceProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/Contexts.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/PeekWrappedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadFilesPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Blocking.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Snapshots.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Watermarks.java, pom.xml
* make `ReadFilesP` generic so that it supports reading avro files
* add `localProcessorIndex` to `Processor.Context`
* add support for reading shared file system 
* introduce avro module
=> Introduce Avro Connector

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamJmsPTest.java
fixes https://github.com/hazelcast/hazelcast-jet/issues/901
=> Assert that JMS queue has enough elements before starting the test

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java
This was claimed to happen at hackathon.
=> Add test when one of two jobs fails

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/JmsSourceBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java
Too much javadoc was removed...
=> Bring back removed javadoc

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamJmsPTest.java
Also fix Sinks.filesBuilder javadoc
fixes https://github.com/hazelcast/hazelcast-jet/issues/917
=> Fix StreamJmsPTest.when_topic

hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/AvroProcessors.java, hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/AvroSourceBuilder.java, hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/AvroSources.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/FileSourceBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/JmsSourceBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsIntegrationTest.java
move outputFunctions to build methods
=> Add explicit source builder for Avro

hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/KeyedWindowResult2Function.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/KeyedWindowResult3Function.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/KeyedWindowResultFunction.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/WindowResult2Function.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/WindowResult3Function.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/WindowResultFunction.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/FunctionAdapter.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/JetEvent.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/HashJoinP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/RollingAggregateP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SessionWindowP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowAggregateTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowGroupAggregateTest.java
=> Consistent behaviour of `mapToOutputFn`

hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperation.java
This merges the leftover from the earlier PR.
=> Improve javadoc of AggregateOperation.andThen

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java
Causes mapWithMerging and mapWithUpdating to fail with parallelism > 1
Test will follow later.
=> bufferFn should be created once per processor

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java, hazelcast-jet-distribution/pom.xml, hazelcast-jet-distribution/src/assembly/zip.xml
fixes https://github.com/hazelcast/hazelcast-jet/issues/966
=> Add spring and avro modules to distribution

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, pom.xml
Will compile after hazelcast/hazelcast#13311 is merged and 3.10.3 is released.
=> Add unit to Jet probes [MERGE AFTER 3.10.3]

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/DAG.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/OutboxImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/EdgeDef.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/VertexDef.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/DotTest.java
Additional do not print them when restarting the job
=> Do not tag snapshot restore vertices with source=yes

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteJmsP.java
Changed misleading variable name `buffer` to `jmsContext`.
=> changed variable name buffer to jmsContext

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestSupport.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java
=> Increase hard limit on cooperative call in tests

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/GracefulShutdownTest.java
There was a race: the `savedCounter` is updated in each call to `saveToSnapshot`, but we've read the value after the shutdown when more snapshots have been done. We should read it after the terminal snapshot before the shutdown was done.
=> Fix GracefulShutdownTest failure

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Job.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/CancellationTest.java
=> Make cancellation of completed job not fail

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/PeekWrappedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/ProcessorWrapper.java, hazelcast-jet-spring/src/test/java/com/hazelcast/jet/spring/TestCustomProcessor.java, hazelcast-jet-spring/src/test/resources/com/hazelcast/jet/spring/application-context-processor.xml
fixes https://github.com/hazelcast/hazelcast-jet/issues/988
=> Inject spring resources to wrapped processors

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/jmx/JmxPublisher.java
=> Ignore race when deregistreing MBeans

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamJmsPTest.java
=> Fix StreamJmsPTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Job.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/SnapshotRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/exception/JobTerminateRequestedException.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/SnapshotRepositoryTest.java
Might be easier to review commit by commit
=> Fix JobRestartWithSnapshotTest.stressTest failures

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/jmx/JmxPublisher.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/metrics/jmx/JmxPublisherTest.java
=> Fix value escaping in MBean's ObjectName

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamEventJournalP_WmCoalescingTest.java
It's hard to tell for sure what happened here, because the output of all
parallel tests in the class is mixed, but looks like the map-writing
thread was stalled for >2 seconds and the source marked partition as
idle. This should not happen if there is output all the time.
In the fix, I increased the idle timeout to 4 seconds and made the
updating thread to run until interrupted. I also made the value put to
map different in each test so that we can tell apart output of each test
and prove the cause should it happen again.
Fixes #1018
=> Fix WmCoalescingTest failure

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/AbstractProcessor.java, pom.xml
Also makes it possible to build Jet with Java 10
=> Update plugin versions

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/SnapshotOperation.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/StoreSnapshotTaskletTest.java
=> Fix serialization of SnapshotOperationResult.error

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImpl.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java
Getting map eagerly causes creation of a snapshot map even when snapshots are turned off.
=> Lazy creation of snapshot map

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncMapWriter.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncMapWriterTest.java
Remove unnecessary entry wrapping and inline method
=> Small refactor and address test failures around AsyncMapWriterTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/management/ReadMetricsOperation.java
=> Fix service for ReadMetricsOperation

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamEventJournalP_WmCoalescingTest.java
=> Make WmCoalescingTest timing insensitive

hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/impl/StreamKafkaP.java
=> Include Kafka's commitSync in try-catch block

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java
=> make sure replicated map has correct size before starting the execution

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java
=> Removes unnecessary cancellation check

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamEventJournalPTest.java
```
| auto-scaling on | auto-scaling off |
----------------|-----------------+------------------+
snapshots       |   restart       |   suspend        |
no snapshots    |   restart       |   fail           |
```
=> Fail job on RestartableExc if not snapshotting

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java
=> Fix possibly infinite loop in stealWork()

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Traverser.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Traversers.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/TraverserTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/TraversersTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/AbstractProcessorTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/AppendableTraverserTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ProcessorsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/WatermarkCoalescer_TerminalSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/FlatMappingTraverserTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowGroupAggregateTest.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/kafka/KafkaSinkTest.java
=> Traverser.over -> Traversers.traverseItems

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/WatermarkCoalescer_TerminalSnapshotTest.java
=> Fix WatermarkCoalescer_TerminalSnapshotTest

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImplTest.java
=> Changed assertion to check whether all the items are flushed or not.

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/AbstractJobOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/AsyncJobOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/AsyncOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/NotifyMemberShutdownOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/SnapshotOperation.java
Some refactoring of operation base classes
Fixes #1094
=> Have NotifyMemberShutdownOp registered on live operations registry

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/JobRepositoryTest.java
=> Fix test_getJobRecordFromClient

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/PostponedSnapshotTest.java
=> Fix PostponedSnapshotTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/XmlJetConfigBuilder.java, hazelcast-jet-core/src/main/resources/hazelcast-jet-config-0.8.xsd, hazelcast-jet-core/src/main/resources/hazelcast-jet-default.xml, hazelcast-jet-core/src/main/resources/hazelcast-jet-full-example.xml, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/JetConfigTest_loadFromClassPath.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/XmlConfigTest.java, hazelcast-jet-core/src/test/resources/hazelcast-jet-test.xml, hazelcast-jet-core/src/test/resources/hazelcast-jet-with-variables.xml, hazelcast-jet-spring/src/main/resources/hazelcast-jet-spring-0.8.xsd, hazelcast-jet-spring/src/test/java/com/hazelcast/jet/spring/TestApplicationContext.java, hazelcast-jet-spring/src/test/resources/com/hazelcast/jet/spring/application-context-jet.xml
=> Add scaleUpDelay config option to XML

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/XmlJetConfigBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/XmlJetConfigLocator.java, hazelcast-jet-core/src/main/resources/hazelcast-jet-config-0.7.1.xsd, hazelcast-jet-core/src/main/resources/hazelcast-jet-default.xml, hazelcast-jet-core/src/main/resources/hazelcast-jet-full-example.xml, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/JetConfigTest_loadFromClassPath.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/XmlConfigTest.java, hazelcast-jet-core/src/test/resources/hazelcast-jet-test.xml, hazelcast-jet-core/src/test/resources/hazelcast-jet-with-variables.xml, hazelcast-jet-spring/src/main/resources/META-INF/spring.schemas, hazelcast-jet-spring/src/main/resources/hazelcast-jet-spring-0.7.1.xsd, hazelcast-jet-spring/src/test/java/com/hazelcast/jet/spring/TestApplicationContext.java, hazelcast-jet-spring/src/test/resources/com/hazelcast/jet/spring/application-context-jet.xml, hazelcast-jet-spring/src/test/resources/com/hazelcast/jet/spring/application-context-processor.xml
=> Add scaleUpDelay config option to XML (backport of #1143)

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java
`JobCoordinationService` is a big class and it's hard to get an overview of operations it supports. When methods are sorted by visibilty, it is easier to view the outline of the code and see them.
=> Sort methods by visibility in JobCoordinationService

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/GracefulShutdownTest.java
=> Fix GracefulShutdownTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/PriorityQueueHook.java
fixes https://github.com/hazelcast/hazelcast-jet/issues/1169
=> Create priority queue with capacity as 1 if queue size is 0

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/PriorityQueueHook.java
forward port of https://github.com/hazelcast/hazelcast-jet/pull/1170
=> [FORWARD-PORT] Create priority queue with capacity as 1 if queue size is 0

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/CustomClassLoadedObject.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/ExceptionUtil.java
=> Add explanation to exc when lambda class missing

hazelcast-jet-client-protocol/src/main/java/com/hazelcast/client/impl/protocol/template/JetCodecTemplate.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ClusterMetadata.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetClientInstanceImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetGetClusterMetadataMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetGetMemberXmlConfigurationMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetMessageTaskFactoryProvider.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetInitDataSerializerHook.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetClusterMetadataOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobSummaryListOperation.java
and methods and messages to retrieve it from client
=> Introduced ClusterMetadata 

pom.xml
also bump sure-fire plugin version
=> Add guava and reflections as test dependency

hazelcast-jet-spring/pom.xml
=> Fix java9+ build

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestOutbox.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/OutboxImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/OutboxInternal.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/Planner.java
Watermarks tell the event time. If the user adds timestamps to the
stream, he probably wants to see current event time in MC.
=> Improve watermark debugging

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/PipelineImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/SinkImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/BatchSourceTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/StreamSourceTransform.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SourcesTest.java
=> Disallow reusing same Source instance

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/SnapshotValidationRecord.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/SnapshotValidator.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImpl.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/SnapshotLargeChunk_IntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImplTest.java
=> Fix validation record & data for large chunks

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java
=> Fix test asserting the DAG deserialization failure

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MigrationWatcher.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorP_MigrationDetectionTest.java
=> Add partition migration detection

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetSubmitJobMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/SubmitJobOperation.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java
=> Always force JobConfig serialization

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/BatchStageImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/BatchStageWithKeyImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/ComputeStageImplBase.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StreamStageImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StreamStageWithKeyImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/PartitionedProcessorTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/ProcessorTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStageWithKey.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStageWithKey.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StreamStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StreamStageWithKey.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamStageTest.java
* add overrides returning `StreamStage` and `BatchStage`
* add 3 overloads taking each form of processor supplier
* add missing tests
=> Fix `customTransform`

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExportSnapshotTest.java
Related to #1189, I tried again to reproduce the problem, without success
=> Tweaks in exporting snapshot of a suspended job

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/WatermarkPolicy.java
=> Improve `limitingLag` javadoc

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ReceiverTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ReceiverTaskletSendLimitTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ReceiverTaskletTest.java
=> Add context to ReceiverTasklet logs

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Edge.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/EdgeDef.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/VertexDef.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java
This is supposed to be refactor only, even though it's hard to compare...
=> Split job & snapshot coordination in MasterContext

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowAggregateTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowGroupAggregateTest.java
=> Fix session window early results test

hazelcast-jet-all/src/test/java/com/hazelcast/jet/server/JetCommandLineTest.java
=> Fix for race in JetCommandLineTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java
PR adds a cluster-wide check for the cluster state before submitting the jobs.
Before this change, when cluster is at `FROZEN` state we were not starting the jobs. With the change, when cluster is at `PASSIVE` or `IN_TRANSITION` we are not starting the jobs.
=> Check cluster-state to be same for all members before submitting the jobs

hazelcast-jet-core/src/main/java/com/hazelcast/jet/accumulator/LongLongAccumulator.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ConvenientSourceP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/ComputeStageImplBase.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/SessionWindowDefinition.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/SlidingWindowDefinition.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StageWithKeyAndWindow.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchAggregateTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/PipelineStreamTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/PipelineTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowAggregateTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowGroupAggregateTest.java
Main difference is using a simple custom source instead of the IMap event journal.
=> Simplify pipeline tests

hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/hadoop/impl/WriteHdfsP.java
Changed the creation of the RecordWriter to receive its own copy
of the JobConf. That way changes to the JobConf will not infer
with other RecordWriters.
=> Fixed creation of RecordWriter for HdfsWriteP

hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/hadoop/impl/WriteHdfsP.java, hazelcast-jet-hadoop/src/test/java/com/hazelcast/jet/hadoop/impl/WriteHdfsPTest.java
Test for the issue https://github.com/hazelcast/hazelcast-jet/issues/1309
=> Add test for LazyOutputFormat

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/FileSourceBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesPTest.java
=> Add test for picking up multiple additions

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/HazelcastConnectorTest.java
There were 26 members created in parallel, let's create one cluster and
reuse it for all tests. Convert the test to serial so that logs from
individual tests are not intertwined.
Also extend the timeout that possibly caused the failure.
Fixes #735
=> Reuse cluster in HazelcastConnectorTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJetInstance.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJobProxy.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java
=> Improve ignored duplicate job submission logs

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/GroupP.java
1. Cache the result of `logger.isFinestEnabled()` in `TaskletExecutionService`
2. Eagerly release the data from `GroupP` while completing
=> Two optimizations

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/EventTimeMapper.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ConvenientSourceP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamEventJournalP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamJmsP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/InsertWatermarksP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/EventTimeMapperTest.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/impl/StreamKafkaP.java
=> Allow removing partitions from EventTimeMapper

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionRecord.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/SnapshotValidator.java
Fixes https://github.com/hazelcast/hazelcast-jet/issues/1348.
Includes refactoring of `MasterJobContext.tryStartJob()`.
=> Improve error messages in SnapshotValidator

hazelcast-jet-distribution/src/main/resources/bin/common.sh, hazelcast-jet-distribution/src/main/resources/bin/jet-start.sh, hazelcast-jet-distribution/src/main/resources/bin/jet-stop.sh, hazelcast-jet-distribution/src/main/resources/bin/jet.sh
Fixes #1366
Needed to use bash and arrays, there's no correct way to do it with /bin/sh
@eminn Please test it on macOS
=> Fix running jet scripts directory with space

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SourceBuilderTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SourceBuilder_TopologyChangeTest.java
Added tests based on https://hazelcast.atlassian.net/wiki/spaces/TES/pages/1713373213/Pipeline+API+-+Fault+Tolerant+Custom+Sources+Test+Plan
=> Improved coverage for custom sources fault tolerance

hazelcast-jet-core/src/test/java/com/hazelcast/jet/MulticastDiscoveryTest.java
fixes https://github.com/hazelcast/hazelcast-jet/issues/1407
=> Set the address of the created instance to the client

hazelcast-jet-core/src/test/java/com/hazelcast/jet/benchmark/BackpressureTest.java
Fixes https://github.com/hazelcast/hazelcast-jet/issues/1357.
=> Fix BackpressureTest

checkstyle/suppressions.xml, hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperations.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/CoAggregateOperationBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/aggregate/AggregateOperationsTest.java
=> Add samples to javadoc in AggregateOperations

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/VertexDef.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/init/VertexDef_HigherPrioritySourceTest.java
Also add test for isHigherPrioritySource - the feature is pretty important, but untested.
=> Fix StackOverflowError with long path in DAG

hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/impl/StreamKafkaP.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/kafka/impl/StreamKafkaPTest.java
When the broker is down, the `poll(long)` and `commitSync()` calls don't
return. The deprecated `poll(long)` call was replaced with
`poll(Duration)` which should not have this problem. `commitSync` is
called only if some records were returned by the `poll` - this doesn't
prevent the issue completely if the broker fails between the `poll` and
`commitSync` calls, but if it fails while `poll` is blocking, it will
prevent stucking.
There is another possibility of getting stuck when fetching metadata in
`assignPartitions`, which I don't know how to fix.
=> Fix Kafka source responsiveness when broker down

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/WindowDefinition.java
=> Improve documentation of windowing constructs

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ManualRestartTest.java
=> Fix test failure in ManualRestartTest

hazelcast-jet-distribution/src/main/resources/bin/common.sh
=> Fix space handling in JAVA_OPTS

hazelcast-jet-distribution/src/main/resources/bin/common.sh
=> Fix space handling in JAVA_OPTS (#1448)

hazelcast-jet-distribution/src/assembly/zip.xml
back-port of https://github.com/hazelcast/hazelcast-jet/pull/1451
=> [BACKPORT] Add default yaml configurations to the distribution

hazelcast-jet-all/src/main/java/com/hazelcast/jet/server/JetCommandLine.java, hazelcast-jet-all/src/test/java/com/hazelcast/jet/server/JetCommandLineTest.java, hazelcast-jet-all/src/test/resources/com/hazelcast/jet/server/hazelcast-client-test.xml, hazelcast-jet-all/src/test/resources/com/hazelcast/jet/server/hazelcast-client-test.yaml
=> Introduced YAML configuration for CLI client

hazelcast-jet-reference-manual/src/main/asciidoc/get-started.adoc
=> Update xml configuration with yaml configuration

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/test/Assertions.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/test/TestSources.java, hazelcast-jet-reference-manual/src/main/asciidoc/pipeline-api/pipeline-api.adoc, hazelcast-jet-reference-manual/src/main/java/CheatSheet.java, hazelcast-jet-reference-manual/src/main/java/Testing.java
* Improve readability of cheat sheet
* Add note about items per second accuracy to streaming test source
* Add example of how to use AssertionCompletedException
=> Improve javadoc for TestSources and assertions

hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/kafka/impl/KafkaTestSupport.java
=> Use random port for kafka tests

pom.xml
Add profile which is useful for doing fast deploys locally. Doesn’t run
any of the tests or run checkstyle.
=> Add quick profile

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/test/TestSourcesTest.java
=> Make TestSourcesTest.test_itemStream_withWindowing less sensitive 

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/metrics/MeasurementPredicates.java
Fixes https://github.com/hazelcast/hazelcast-jet/issues/1532
=> Fix logic of matching metric tags with regular expressions

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/SourceBuilder.java
=> Fix SourceBuilder's javadoc

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/ComputeStageImplBase.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/FunctionAdapter.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/GrAggBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/Planner.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StageWithKeyAndWindowImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StageWithWindowImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/SinkTransform.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SinksTest.java
=> Fix adapting keyFn for partitioned sink input

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java
It was possible that the method saw neither the JobResult nor the
MasterContext because between those two checks another thread created
the JobResult and removed the MasterContext. In this case it threw
`JobNotFoundException`, which was the failure in the issue.
Now we first check `masterContexts` and if one isn't found, we proceed
to checking the JobResults. When finalizing the job, the creation of
JobResult _happens before_ removal of MasterContext.
Fixes #1519
=> Fix race in JobCoordinationService.terminateJob()

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/DAG.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Vertex.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlanBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/StreamSourceTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/TimestampTransform.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/PipelineStreamTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamSourceStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamSourceStageTestBase.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamStageTest.java
=> Match upstream parallelism when adding timestamp transform

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/LoggingUtil.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartStressTestBase.java
=> Reduce visibility of snapshot logs

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Job.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/CompleteExecutionOperation.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_MiscTest.java
Fixes https://github.com/hazelcast/hazelcast-jet/issues/1569
Fixes https://github.com/hazelcast/hazelcast-jet/issues/1580
=> Stop rendering metrics for jobs that don't have them enabled

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/MetricsConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/JetMetricsService.java
Fixes https://github.com/hazelcast/hazelcast-jet/issues/1584
=> Harmonize metrics related config params

hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/KafkaSources.java
=> More details about Kafka's two modes of operation

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/JetProperties.java, hazelcast-jet-reference-manual/src/main/asciidoc/appendix.adoc, hazelcast-jet-reference-manual/src/main/asciidoc/configuration.adoc
=> Copy-paste system properties list to refman

examples/spring/src/main/java/com/hazelcast/jet/examples/spring/XmlConfigurationSample.java, examples/spring/src/main/java/com/hazelcast/jet/examples/spring/XmlConfigurationWithSchemaSample.java, examples/spring/src/main/java/com/hazelcast/jet/examples/spring/source/CustomSourceP.java, hazelcast-jet-spring/pom.xml
Module name was changed by mistake when merging code samples
=> Fix bad module name in spring

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/test/AssertionSinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/test/Assertions.java
=> Fix javadoc for assertionCollectedEventually

hazelcast-jet-s3/src/test/java/com/hazelcast/jet/s3/S3SourceTest.java
=> Added region property to S3 client in test

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/PeekWrappedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/ProcessorWrapper.java
=> Update logger when wrapping a processor

hazelcast-jet-s3/src/main/java/com/hazelcast/jet/s3/S3Sinks.java, hazelcast-jet-s3/src/test/java/com/hazelcast/jet/s3/S3MockTest.java, hazelcast-jet-s3/src/test/java/com/hazelcast/jet/s3/S3SinkTest.java, hazelcast-jet-s3/src/test/java/com/hazelcast/jet/s3/S3SourceTest.java, hazelcast-jet-s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java
=> S3 sink should handle items larger than buffer size

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/TransformStatefulPTest.java
Following tests were added:
- check that state object actually survives watermark
- check that state object survives eviction for different grouping key
=> Added more test scenarios to TransformStatefulPTest

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StatefulMappingStressTest.java
Fixes https://github.com/hazelcast/hazelcast-jet/issues/1651
=> Fixed StatefulMappingStressTest

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java
=> Fix for intermittent test failure

hazelcast-jet-reference-manual/src/main/asciidoc/pipeline-api/pipeline-api.adoc, hazelcast-jet-reference-manual/src/main/asciidoc/source-sink-connectors/index.adoc, hazelcast-jet-reference-manual/src/main/asciidoc/source-sink-connectors/overview.adoc
forward port of https://github.com/hazelcast/hazelcast-jet/pull/1666
=> Add s3 to the index of source/sink connectors

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteJdbcP.java
=> Fix WriteJdbcP in jobs with timestamps - backport

hazelcast-jet-reference-manual/src/main/asciidoc/work-with-jet/performance-considerations.adoc, hazelcast-jet-reference-manual/src/main/java/Serialization.java
=> Fix code sample

hazelcast-jet-all/src/main/resources/logging.properties
=> Add exception logging to JUL logging.properties

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/BatchStageImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StreamStageImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceOrderedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceUnorderedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/ProcessorSupplierWithService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/TransformUsingServiceP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStageWithKey.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StreamStageWithKey.java
Cleanup of some type params leftover from mapUsingContext
=> Cleanup of type params regarding mapUsingService

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Traverser.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Traversers.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/BatchStageImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/BatchStageWithKeyImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StreamStageImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StreamStageWithKeyImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SlidingWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/TransformStatefulP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStageWithKey.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStageWithKey.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StreamStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StreamStageWithKey.java
=> Avoid nested wildcards in flatMap

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/metrics/JobMetrics.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobMetricsUtil.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/JobMetricsPublisher.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/CompleteExecutionOperation.java
Less garbage is created now during reading from compressor
=> Follow MetricCompressor changes

hazelcast-jet-distribution/src/bin-regular/common.sh
Automatically add required modules when starting Jet from JDK9+
=> Auto import modules in JDK9+ in start script

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetGetJobConfigMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetGetJobSummaryListMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetJoinSubmittedJobMessageTask.java
https://github.com/hazelcast/hazelcast/pull/15860
=> Adapt changes on client protocol

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/JetProperties.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRecord.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/UpdateMapP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/InitExecutionOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/SubmitJobOperation.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetSplitBrainTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/OperationLossTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/OperationTimeoutTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamEventJournalPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamEventJournalP_WmCoalescingTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/WatermarkCoalescer_TerminalSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamSourceStageTestBase.java
* GroupProperty -> ClusterProperty
* dataIn/Out.read/WriteData -> IOUtil.read/writeData
=> Follow changes in IMDG

examples/hello-world/src/main/java/com/hazelcast/jet/examples/helloworld/HelloWorld.java, examples/hello-world/src/main/resources/hazelcast.yaml
* Make output map name non-random, so you can start multiple clients
* Add a yaml file to use as config when using embedded mode.
=> Some minor tweaks to hello-world example

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/AbstractTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStage.java
=> Fix @Nullable name in BatchStage

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/MapEntryHook.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/QueryEntryHook.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/SerializerHookConstants.java, hazelcast-jet-core/src/main/resources/META-INF/services/com.hazelcast.SerializerHook
see https://github.com/hazelcast/hazelcast/issues/15179#issuecomment-558966682
=> Remove MapEntry and PriorityQeueu hooks since they are on IMDG side

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadJdbcPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteJdbcPTest.java
fixes https://github.com/hazelcast/hazelcast-jet/issues/1777
=> Use temp directory for h2

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java
fixes https://github.com/hazelcast/hazelcast-jet/issues/1757
=> Increase assert timeout for initial snapshot

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/SinkBuilder.java
fixes https://github.com/hazelcast/hazelcast-jet/issues/1731
=> Use context object instead of writer for sink-builder

hazelcast-jet-reference-manual/src/main/asciidoc/work-with-jet/job-management.adoc, hazelcast-jet-reference-manual/src/main/asciidoc/work-with-jet/start-jet-submit-job.adoc, hazelcast-jet-reference-manual/src/main/java/StartJet.java
fixes https://github.com/hazelcast/hazelcast-jet/issues/1768
=> Explain how to parametrise jobs

hazelcast-jet-reference-manual/src/main/asciidoc/source-sink-connectors/s3.adoc
fixes https://github.com/hazelcast/hazelcast-jet/issues/1635
=> Document s3 sink behaviour and limitation for streaming jobs

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/VertexDef.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/init/VertexDef_HigherPrioritySourceTest.java
=> backport fix #1806 to 3.2

hazelcast-jet-s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java
fixes https://github.com/hazelcast/hazelcast-jet/issues/1817
=> Add assertEventually for s3 sink tests

hazelcast-jet-all/src/main/java/com/hazelcast/jet/server/JetBootstrap.java, hazelcast-jet-all/src/main/java/com/hazelcast/jet/server/JetCommandLine.java, hazelcast-jet-all/src/test/java/com/hazelcast/jet/server/JetCommandLineTest.java
=> Introduced an option to pick main class from the JAR file

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_StreamTest.java
Using `START_FROM_CURRENT` for journal and putting data after submitting the job is racy. Even if the job status is `RUNNING` the processor may not still registered to the journal thus some of the data put may not be seen by the processors. I've converted the test to use `START_FROM_OLDEST`
Fixes #1693
=> Removed START_FROM_CURRENT usage since it is racy

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java
There was a 5 seconds delay after starting a node
that the submitted jobs would be running on it. By having
a shorter delay when partitions are not yet initialized, we
can start the job quicker on initial submission.
=> Make job scanning delay adaptable

hazelcast-jet-reference-manual/src/main/asciidoc/source-sink-connectors/hdfs.adoc
Describes which JARs to put to classpath in order to use Hadoop module
=> Enhance Hadoop JARs and Classpath chapter in reference manual

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadMapOrCacheP.java
Removing migration watcher and update javadoc will be in a follow up PR
Checklist
=> Follow changes in map/cache iterators

hazelcast-jet-all/src/main/java/com/hazelcast/jet/server/JetCommandLine.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ClientJobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetClientInstanceImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java
=> Adapt to IMDG using UUID instead of Address for Invocations

hazelcast-jet-all/src/main/java/com/hazelcast/jet/server/JetCommandLine.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/MulticastDiscoveryTest.java
=> Clean-up some redundant code

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadMapOrCacheP_ConsistencyTest.java
`when_removing_items_then_stable_iteration_remote` called `testAddingItems`...
=> ReadMapOrCacheP_ConsistencyTest fix & touchups

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetExistsDistributedObjectCodec.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetExportSnapshotCodec.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetGetJobConfigCodec.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetGetJobIdsByNameCodec.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetGetJobIdsCodec.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetGetJobMetricsCodec.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetGetJobStatusCodec.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetGetJobSubmissionTimeCodec.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetGetJobSummaryListCodec.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetJoinSubmittedJobCodec.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetResumeJobCodec.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetSubmitJobCodec.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetTerminateJobCodec.java
Reflected the changes done in https://github.com/hazelcast/hazelcast/pull/16447 to Jet codecs.
=> update codecs with recent changes

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/test/TestSourcesTest.java
Fixes issue https://github.com/hazelcast/hazelcast-jet/issues/1855
Checklist
=> Make TestSourceTest more tolerant to hiccups

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorState.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TestUtil.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Blocking.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Snapshots.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Watermarks.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/TaskletExecutionServiceTest.java
=> Don't call Processor.close on cooperative thread

hazelcast-jet-core/src/test/java/com/hazelcast/jet/job/JobSubmissionSlownessRegressionTest.java
The test was using `availableProcessors` which is 72 in our test environment. Also per run duration was too much which was increasing the total test duration. By decreasing and fixing the thread count and decreasing the per run duration we can now have a more stable test. It is not a total deterministic fix though.
Checklist
Fixes #1722
=> JobSubmissionSlownessRegressionTest: decrease and fix thread count, decrease per run duration

hazelcast-jet-reference-manual/src/main/asciidoc/pipeline-api/pipeline-api.adoc, hazelcast-jet-reference-manual/src/main/asciidoc/source-sink-connectors/overview.adoc, hazelcast-jet-reference-manual/src/main/java/BuildComputation.java
Improve return-results-to-caller related sections of RefMan
Checklist
=> Improve return-results-to-caller related sections of RefMan

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobLifecycleMetricsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_StressTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/MetricsTest.java
Add names to the probes
Checklist
=> Add names to the probes

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/metrics/MeasurementPredicates.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/metrics/Metric.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/metrics/MetricNames.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/metrics/MetricTags.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/metrics/Metrics.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/metrics/Unit.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/MeasurementPredicatesTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/MetricsTest.java
=> Add missing annotation and tests to metrics related code

hazelcast-jet-distribution/src/bin-filemode-755/jet-cluster-cp-admin, hazelcast-jet-distribution/src/root/README.md, hazelcast-jet-distribution/src/root/config/hazelcast.yaml
Enabled CP REST endpoint group by default and added admin script for CP subsystem
Checklist
Fixes #1781
=> Add admin script for CP subsystem

hazelcast-jet-reference-manual/src/main/asciidoc/work-with-jet/configure-fault-tolerance.adoc
=> Fix minor Javadoc issues in Blue/Green client code

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_MiscTest.java, hazelcast-jet-reference-manual/src/main/asciidoc/work-with-jet/log-debug.adoc
=> Add missing metrics to RefMan

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ObservableResultsTest.java
Added test which repeatedly creates `Observable`, uses it in job as sink, destroys it and checks that cycles do not affect to each other.
Checklist
=> Added test for create/destroy Observable repeatedly

examples/files/src/main/java/com/hazelcast/jet/examples/files/SalesJsonAnalyzer.java, hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/AvroProcessors.java, hazelcast-jet-avro/src/test/java/com/hazelcast/jet/avro/AvroSourceTest.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SourceProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadFilesP.java
Also refactor AvroSourceTest to shared cluster
=> Simplify ReadFilesP, simpler java9 code in sample

hazelcast-jet-core/src/main/java/com/hazelcast/jet/JetInstance.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetBootstrap.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/ResourceConfigTest.java
Fixes https://github.com/hazelcast/hazelcast-jet/issues/1896
Checklist
=> Uncheck JobConfig add/attach methods

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/Contexts.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/AbstractDeploymentTest.java
Fixes https://github.com/hazelcast/hazelcast-jet/issues/1895
Checklist
=> Proper exception for wrong ID in attachedFile()

extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java
Fixes https://github.com/hazelcast/hazelcast-jet/issues/1894
Checklist
=> Make files writable before cleanup

pom.xml
=> Update IMDG version to 3.12.6

extensions/hadoop/src/main/java/com/hazelcast/jet/hadoop/HadoopSources.java, reference-manual/src/main/asciidoc/pipeline-api/pipeline-api.adoc, reference-manual/src/main/asciidoc/source-sink-connectors/imdg.adoc, reference-manual/src/main/asciidoc/source-sink-connectors/overview.adoc, reference-manual/src/main/java/BuildComputation.java
=> Add some forgotten adaptations to Jet 4.0 changes

pom.xml
Update Kubernetes plugin version to 2.0.1
=> Update Kubernetes plugin version

pom.xml
=> Remove client protocol version from pom.xml

reference-manual/src/main/asciidoc/get-started.adoc, reference-manual/src/main/asciidoc/index.adoc
Fixed couple of reference manual typos.
=> Fixing couple of reference manual typos.

reference-manual/src/main/asciidoc/expert-zone/dag.adoc, reference-manual/src/main/asciidoc/glossary.adoc, reference-manual/src/main/asciidoc/jet-concepts.adoc, reference-manual/src/main/asciidoc/pipeline-api/pipeline-api.adoc, reference-manual/src/main/asciidoc/pipeline-api/pipeline-cheatsheet.adoc, reference-manual/src/main/asciidoc/work-with-jet/job-management.adoc, reference-manual/src/main/asciidoc/work-with-jet/performance-considerations.adoc
Fixed reference manual formatting in couple of places.
=> Fix refman formatting & grammar

examples/grpc/pom.xml, examples/grpc/src/main/java/com/hazelcast/jet/examples/grpc/GRPCEnrichment.java, extensions/python/pom.xml, extensions/python/src/main/resources/jet_to_python_init.sh, hazelcast-jet-core/src/main/resources/jet-runtime.properties, hazelcast-jet-distribution/src/root/config/log4j.properties, pom.xml
=> Freeze gRPC versions installed via pip

hazelcast-jet-distribution/src/bin-filemode-755/jet-cluster-admin
=> Fix exit-code checking for cluster-admin

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/BatchStageWithKeyImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/ComputeStageImplBase.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StageWithGroupingBase.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StreamStageWithKeyImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/PartitionedProcessorTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/ProcessorTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStageWithKey.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStageWithKey.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StreamStageWithKey.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamStageTest.java
=> Add keyed version of `mapUsingServiceAsyncBatched`

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobSnapshotMetricsTest.java
Basic test coverage for job snapshot metrics.
Checklist
=> Added test for job snapshot metrics

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Util.java
=> Suppress SpotBugs false positive on JDK11

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/ComputeStageImplBase.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AbstractAsyncTransformUsingServiceP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStageWithKey.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ProcessorsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceBatchP_IntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceBatchedPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServicePTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceP_IntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/ProcessorTransformParallelismTest.java
=> Improve `mapUsingServiceAsyncBatched` javadoc

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamJmsP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsIntegrationTestBase.java
=> Add test for durable subscriber

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsIntegrationTestBase.java
The test starts production to the topic when it sees the job RUNNING.
But that could be before the job manages to create the durable
subscriber, therefore it can miss some initial messages. Now we create
the named subscriber before we submit the job so this can't happen.
=> Fix test for durableTopic

hazelcast-jet-all/pom.xml, hazelcast-jet-core/pom.xml, pom.xml
Properly shaded/relocated `picocli` library
Checklist
=> Shade/relocate picocli library.

NOTICE, hazelcast-jet-all/pom.xml
Added notice about `picocli` project usage.
Checklist
=> Add notice about picocli project usage.

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetBootstrap.java
=> Add error message for invalid class

hazelcast-jet-distribution/src/root/README.md
=> Link code samples from readme

extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceConfig.java
=> Add a code sample to Python Javadoc

reference-manual/src/main/asciidoc/source-sink-connectors/jms.adoc
=> Document which JMS implementations we test against

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, pom.xml, reference-manual/pom.xml, reference-manual/src/main/asciidoc/pipeline-api/pipeline-api.adoc, reference-manual/src/main/java/MLModelPrediction.java
=> Added a section regarding ML model prediction

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java, reference-manual/src/main/asciidoc/appendix.adoc, reference-manual/src/main/asciidoc/expert-zone/dag-tutorial.adoc, reference-manual/src/main/asciidoc/expert-zone/dag.adoc, reference-manual/src/main/asciidoc/source-sink-connectors/imdg.adoc, reference-manual/src/main/java/migration/Migration.java
=> Add migration guide to RefMan

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetBootstrap.java
Only replace the handler if the default console handler is present. Adding it unconditionally results in double logging of j.u.l -> slf4j bridge is used (such as in Spring Boot)
Checklist
=> Only configure logging if type is set to JDK

extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java, extensions/python/src/main/resources/jet_to_python_init.sh
Fixes #1987
Checklist
Fixes #1987
=> Check init script return code

site/docs/api/serialization.md
Added xml configuration section & formatted serialization website section.
=> Add xml configuration section & format serialization website section.

site/docs/api/serialization.md
Replaced serialization website section xml configuration with yaml.
=>  Replace serialization website section xml configuration with yaml. 

extensions/pom.xml
=> Fix deploy extensions artifacts

examples/event-journal/src/main/java/com/hazelcast/jet/examples/eventjournal/CacheJournalSource.java, examples/event-journal/src/main/java/com/hazelcast/jet/examples/eventjournal/MapJournalSource.java, examples/event-journal/src/main/java/com/hazelcast/jet/examples/eventjournal/RemoteCacheJournalSource.java, examples/event-journal/src/main/java/com/hazelcast/jet/examples/eventjournal/RemoteMapJournalSource.java, examples/fault-tolerance/src/main/resources/hazelcast.yaml, examples/hello-world/src/main/resources/hazelcast.yaml, examples/imdg-connectors/src/main/java/com/hazelcast/jet/examples/imdg/CacheSourceAndSink.java, examples/imdg-connectors/src/main/java/com/hazelcast/jet/examples/imdg/ListSourceAndSink.java, examples/imdg-connectors/src/main/java/com/hazelcast/jet/examples/imdg/MapSourceAndSinks.java, examples/imdg-connectors/src/main/java/com/hazelcast/jet/examples/imdg/RemoteListSourceAndSink.java, examples/imdg-connectors/src/main/java/com/hazelcast/jet/examples/imdg/RemoteMapSourceAndSink.java, examples/job-management/src/main/resources/hazelcast.yaml, examples/kafka/pom.xml, examples/kafka/src/main/java/com/hazelcast/jet/examples/kafka/KafkaSink.java, examples/tf-idf/src/main/java/com/hazelcast/jet/examples/tfidf/TfIdfJdkStreams.java
Fixed the rest of log4j classpath issues + fixed some code samples
Checklist
=> Fix another log4j classpath issues in code samples

examples/files/src/main/java/com/hazelcast/jet/examples/files/SalesCsvAnalyzer.java, examples/files/src/main/java/com/hazelcast/jet/examples/files/avro/AvroSink.java, extensions/avro/src/main/java/com/hazelcast/jet/avro/AvroProcessors.java, extensions/avro/src/main/java/com/hazelcast/jet/avro/AvroSinks.java, extensions/avro/src/test/java/com/hazelcast/jet/avro/AvroSinkTest.java, hazelcast-jet-distribution/src/root/release_notes.txt, reference-manual/src/main/java/integration/Avro.java
=> Replace Supplier<Schema> with Schema for Avro sink (#2005)

pom.xml
=> Fix sonar build

examples/README.md, examples/files/src/main/java/com/hazelcast/jet/examples/files/s3/S3WordCount.java, examples/pom.xml, examples/spring-boot/README.md, examples/spring-boot/pom.xml, examples/spring-boot/src/main/java/com/hazelcast/jet/examples/spring/SpringBootSample.java, examples/spring/README.md, examples/spring/src/main/java/com/hazelcast/jet/examples/spring/config/AppConfig.java, examples/spring/src/main/resources/application-context-with-schema.xml, examples/spring/src/main/resources/application-context.xml
Forward-port of https://github.com/hazelcast/hazelcast-jet/pull/2009
Checklist
=> Code sample fixes

reference-manual/src/main/asciidoc/jet-concepts.adoc, reference-manual/src/main/java/WhatIsDistributedComputing.java
=> Fix minor problems in Refman

examples/wordcount/src/main/java/com/hazelcast/jet/examples/wordcount/WordCount.java
`WordCount` example started to use `Observable` but this example time to time finishes even before something from `Observable` is actually printed into the log => added 5 seconds sleep before it shutdowns Jet instance.
Checklist
=> Improve WordCount example

reference-manual/src/main/asciidoc/work-with-jet/log-debug.adoc
Found and fixed some minor problems in metrics related documentation.
Checklist
=> Fix minor issues with documentation

extensions/hadoop/src/main/java/com/hazelcast/jet/hadoop/impl/ReadHadoopNewApiP.java
Removed unused `BetterByteArrayOutputStream`.
Checklist
=> Remove unused BetterByteArrayOutputStream

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/DelegatingSerializationService.java
Refactored `DelegatingSerializationService`.
Checklist
=> Use job-level serializers for toData

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java
=> Format javadoc

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/DelegatingSerializationService.java
Adjusted `DelegatingSerializationService` to latest IMDG API.
Checklist
=> Adjust DelegatingSerializationService to latest IMDG API

site/docs/api/testing.md
Fix compile error in the code sample due to wrong method name and missing method argument
=> Fix code sample in "Streaming Source" section

site/docs/how-tos/xa.md, site/website/sidebars.json
=> Add how-to guide for XA compatibility testing

hazelcast-jet-all/pom.xml, hazelcast-jet-distribution/src/root/config/hazelcast.yaml, pom.xml
This change bring following classes to the JAR
```
>jar tf hazelcast-jet-4.1-SNAPSHOT.jar | grep azure
com/hazelcast/azure/
com/hazelcast/azure/RestClient.class
com/hazelcast/azure/AzureDiscoveryStrategy.class
com/hazelcast/azure/PortRange.class
com/hazelcast/azure/AzureProperties.class
com/hazelcast/azure/AzureNetworkInterface.class
com/hazelcast/azure/AzureDiscoveryStrategyFactory.class
com/hazelcast/azure/AzureConfig$Builder.class
com/hazelcast/azure/AzureAddress.class
com/hazelcast/azure/RetryUtils.class
com/hazelcast/azure/AzureConfig$1.class
com/hazelcast/azure/AzureClient.class
com/hazelcast/azure/AzureComputeApi.class
com/hazelcast/azure/RestClientException.class
com/hazelcast/azure/AzureMetadataApi.class
com/hazelcast/azure/AzureAuthenticator.class
com/hazelcast/azure/Utils.class …
```
=> Added hazelcast-azure plugin to the fat jar

examples/job-management/src/main/java/com/hazelcast/jet/examples/jobmanagement/JobSuspendResume.java, examples/job-management/src/main/java/com/hazelcast/jet/examples/jobmanagement/JobTracking.java
=> Fix comment in job-management example

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java
Added `@since` to new `JobConfig` methods.
Checklist
=> Add @since to new JobConfig methods

examples/imdg-connectors/src/main/java/com/hazelcast/jet/examples/imdg/CacheSourceAndSink.java, examples/imdg-connectors/src/main/java/com/hazelcast/jet/examples/imdg/ListSourceAndSink.java, examples/imdg-connectors/src/main/java/com/hazelcast/jet/examples/imdg/MapPredicateAndProjection.java, examples/imdg-connectors/src/main/java/com/hazelcast/jet/examples/imdg/MapSourceAndSinks.java, examples/imdg-connectors/src/main/java/com/hazelcast/jet/examples/imdg/RemoteListSourceAndSink.java, examples/imdg-connectors/src/main/java/com/hazelcast/jet/examples/imdg/RemoteMapSourceAndSink.java
Cleaned up IMDG connectors examples.
Checklist
=> Cleanup IMDG connectors examples

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/ResourceConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/JetClassLoader.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/ReflectionUtils.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ReflectionUtilsTest.java
Refactored `JobConfig.addPackage()` so it does not load classes while scanning.
Checklist
=> Do not load classes while scanning packages

site/docs/operations/monitoring.md
=> Fix small typo in monitoring.md

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SinkProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/AbstractHazelcastConnectorSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastReaders.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadMapOrCacheP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/UpdateMapP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/UpdateMapWithEntryProcessorP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteMapP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteObservableP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/Contexts.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/TestContextSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadMapOrCachePTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SinksTest.java
Allowed job-level serializers to be used with IMDG `Maps`s & `Cache`s.
Checklist
=> Enable job-level serializer for IMDG Maps & Caches

site/docs/design-docs/001-code-deployment-improvements.md, site/docs/design-docs/002-job-level-serialization.md
Updated job-level serialization TDD limitations sections & couple of tweaks.
=> Update job-level serialization TDD

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobSerializerTest.java
Added job serializer IMDG `Map`, `Cache` & `Observable` tests.
Checklist
=> Add job serializer IMDG Map, Cache & Observable tests

site/docs/design-docs/003-elasticsearch-connector.md
Elasticsearch connector TDD for review
=> Add Elasticsearch connector TDD

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/NodeExtensionCommon.java
=> Add logging line with cluster name

site/docs/architecture/fault-tolerance.md, site/website/blog/2020-03-30-ml-inference.md
Fixed couple of markdown linter errors.
=> Fix markdown linter errors

site/docs/how-tos/xa.md
Align with these changes - https://github.com/hazelcast/hazelcast-jet-contrib/pull/65
Checklist
=> Align docs for xa-test with latest version

site/docs/api/serialization.md, site/website/versioned_docs/version-4.0/api/submitting-jobs.md
Added job-level serializer & `addClass()`/`addPackage()` docs.
=> Add job-level serializer & addClass/addPackage docs

site/docs/design-docs/004-spring-boot-starter.md, site/website/sidebars.json
=> Add spring boot starter design doc

site/website/README.md, site/website/blog/2020-04-01-upgrading-to-jet-40.md
=> Write Migration Guide BLOG post for 4.0

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadMapOrCacheP.java
Fixed compilation error after IMDG dependency update.
Checklist
=> Fix compilation error

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/SinkStressTestUtil.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteJdbcPTest.java
=> Fix race asserting RUNNING status and restarting

site/docs/api/spring.md, site/docs/tutorials/spring-boot.md, site/website/sidebars.json
=> Add spring boot starter documentation

site/docs/design-docs/006-declarative-serialization.md
Improved Declarative Serialization TDD.
Checklist
=> Improve Declarative Serialization TDD

site/docs/design-docs/007-pulsar-connector.md, site/docs/design-docs/009-pulsar-connector.md, site/docs/tutorials/pulsar.md, site/website/sidebars.json
Tutorial and TDD for Pulsar are added in this PR. Since the pulsar PR is not merged yet (do not have any build), the maven and gradle build examples mentioned in the tutorial have not been tried.
=> [009] Add tutorial and TDD for Pulsar connector.

hazelcast-jet-all/src/test/java/com/hazelcast/jet/server/JetCommandLineTest.java
=> Make sure the JAR file exists before test execution

checkstyle/checkstyle.xml, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStage.java
=> Add check for missing @Override annotations

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsSourceIntegrationTest_RabbitMQ.java
=> Ignore durable topic test for RabbitMQ

site/docs/operations/discovery.md
Add Azure discovery
Checklist
Fixes https://github.com/hazelcast/hazelcast-jet/issues/2081
=> Add azure discovery

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java
=> Fix NPE when checking executionId

site/docs/api/spring.md
=> Fix property name in Jet spring boot docs

site/website/package-lock.json, site/website/package.json, site/website/replace-version-config.js
We can start putting placeholders for Jet and IMDG versions in the `.md` files and before creating new version they can get replaced with the provided script.
Checklist
=> Added script for version replacement

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Partitioner.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java
Added support for getting partition id with job-level serializer.
Checklist
Fixes #2188
=> Use job-level serializer to get partition id

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JmxMetricsChecker.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobExecutionMetricsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobLifecycleMetricsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetricsChecker.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobSnapshotMetricsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/MetricsTest.java
=> Extract metrics related test utilities, simplify tests

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java
Added @params to `JobConfig.registerSerializer()`
Checklist
=> Add @params to JobConfig.registerSerializer()

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetBootstrap.java
Fixes #2058. I am not adding a test because I wasn't able to reproduce the error. 
Checklist
=> Put a safeguard around shutdown() in JetBootstrap

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ObservableResultsTest.java
Try to address failing tests related to `JetInstance.getObservables()` (issues #2026 & #2191).
Checklist
Links to issues fixed (if any): #2026
=> Try to fix undeterministic behaviour in tests

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, site/docs/enterprise/lossless-restart.md
=> More logging for snapshot on member

site/docs/api/serialization.md
Improved Protobuf serialization docs.
Checklist
=> Improve Protobuf serialization docs

extensions/protobuf/src/test/java/com/hazelcast/jet/protobuf/JobSerializerTest.java
Following is improved:
- protobuf tests were running on cluster with single node, i.e. serialization for pipeline stages did not take into account during running pipeline.
- added test which distributes job across the whole cluster
Checklist
=> Added test for protobuf with distributed job

examples/README.md, examples/pom.xml, examples/protobuf/pom.xml, examples/protobuf/src/main/java/com/hazelcast/jet/examples/protobuf/ProtobufSerializerAdapter.java, examples/protobuf/src/main/java/com/hazelcast/jet/examples/protobuf/ProtobufSerializerHookAdapter.java, examples/protobuf/src/main/proto/messages.proto, examples/protobuf/src/main/resources/META-INF/services/com.hazelcast.SerializerHook
Added protobuf samples.
Checklist
=> Add protobuf samples

site/docs/api/sources-sinks.md, site/docs/how-tos/custom-batch-source.md
Doc updates originally part of #2208, but unrelated to grpc how to guide.
=> Clean up code sample and other docs

site/docs/api/testing.md, site/docs/enterprise/management-center.md, site/docs/operations/kubernetes.md, site/website/attributes.json, site/website/replace-version-config.js
Allow using json file to declare more attributes to be replaced
=> Separate replace script with attributes

examples/spring-boot/src/main/java/com/hazelcast/jet/examples/spring/SpringBootSample.java
Add @SpringBootApplication tag to the example
Checklist
Fixes #NNNN
* ..
=> Add @SpringBootApplication tag to the example

site/docs/api/submitting-jobs.md, site/website/versioned_docs/version-4.0/api/submitting-jobs.md, site/website/versioned_docs/version-4.1/api/submitting-jobs.md
Fixed submitting jobs docs.
Checklist
=> Fixed submitting jobs docs.

hazelcast-jet-distribution/src/root/changelog.txt, hazelcast-jet-distribution/src/root/release_notes.txt
=> Release notes 4 1

site/docs/operations/cluster-sizing.md, site/website/versioned_docs/version-4.1/operations/cluster-sizing.md
Replaced links to the old refman with links to content on the new website.
Checklist
=> Fix links, improve content in Cluster Sizing

hazelcast-jet-distribution/src/root/release_notes.txt
=> Address Serdar's review comments in closed PR

site/website/package.json, site/website/pages/en/demos.js, site/website/siteConfig.js, site/website/static/jss/card.js
Add a new page including the demo applications to the website.
=> Add Demos Page to the Website

site/website/pages/en/demos.js
It was not matching the rest of the website
Checklist
=> Fixed bg color

site/website/blog/2020-04-29-jet-41-is-released.md
=> Fix linter issues in blog post

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/RebalanceBatchStageTest.java
=> Minor improvements for RebalanceBatchStageTest

examples/spring-boot/README.md, examples/spring-boot/pom.xml, examples/spring-boot/src/main/java/com/hazelcast/jet/examples/spring/SpringBootSample.java, examples/spring-boot/src/main/resources/hazelcast-jet.yaml
=> [004] update spring-boot sample to use jet-starter

hazelcast-jet-distribution/pom.xml
=> Fix generating javadoc

site/docs/design-docs/009-pulsar-connector.md, site/docs/tutorials/pulsar.md
- Update the Pulsar documentation to be compatible with the changes on Pulsar Connector API.
- State the scenario that the connector fails the fast-fail.
=> Update Pulsar Documentation

hazelcast-jet-core/src/main/java/com/hazelcast/jet/json/JsonUtil.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/JsonUtilTest.java
It was duplicated with different meaning
=> Fix method name in JsonUtil

examples/wordcount/src/main/java/com/hazelcast/jet/examples/wordcount/WordCount.java
Since Observable was used in WordCount code sample then it printed different results for every execution.
Checklist
=> Use sink map in WordCount code sample

examples/grpc/src/main/java/com/hazelcast/jet/examples/grpc/GRPCEnrichment.java
The server and the executor were not shut down, leaving the application
running. The executor has to be closed explicitly because gRPC server
doesn't take its ownership and doesn't shut it down itself.
Checklist
=> Close gRPC server and executor, allowing example to finish

site/docs/api/sources-sinks.md, site/docs/design-docs/009-pulsar-connector.md, site/docs/tutorials/pulsar.md
- Updates to increase the visibility of the pulsar connector.
- Small fixes -> Fix unresolved example URL, update design doc content.
=> Update Pulsar Related Content on Website

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadFilesPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/JsonUtilTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ReflectionUtilsTest.java, hazelcast-jet-core/src/test/resources/com/hazelcast/jet/impl/util/file_list_pretty_printed.json, hazelcast-jet-core/src/test/resources/com/hazelcast/jet/impl/util/file_pretty_printed.json
=> Add tests for pretty printed json to JsonUtilTest

extensions/cdc-debezium/pom.xml
=> Use same Kafka version for CDC as the rest of the project

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/XaSinkProcessorBase.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TestProcessors.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_StressTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/init/VertexDef_HigherPrioritySourceTest.java
=> Handle WM in XaSinkProcessorBase

extensions/elasticsearch/elasticsearch-7/src/main/java/com/hazelcast/jet/elastic/impl/ElasticSourceP.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/CommonElasticSourcesTest.java, hazelcast-jet-distribution/pom.xml
=> Elastic nonmatching index alias fix

examples/hadoop/src/main/java/com/hazelcast/jet/examples/hadoop/parquet/HadoopParquet.java
=> Add S3 parquet example

site/website/siteConfig.js
When the link shared as an URL on social media this enables Jet logo to appear along with the link
Checklist
=> Add opengraph image configuration

site/website/sidebars.json
=> [005] - Fix wrong name for deploy guide in sidebar

site/docs/how-tos/operator.md, site/docs/operations/discovery.md, site/docs/operations/kubernetes.md, site/website/versioned_docs/version-4.1/how-tos/operator.md, site/website/versioned_docs/version-4.1/operations/discovery.md, site/website/versioned_docs/version-4.1/operations/kubernetes.md, site/website/versioned_sidebars/version-4.1-sidebars.json
=> Update k8s documentation

extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/ChangeRecord.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSource.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/ChangeRecordImpl.java
=> Add "table" and "database" fields to CDC records

hazelcast-jet-distribution/src/bin-regular/common.sh, hazelcast-jet-distribution/src/root/lib/hazelcast-download.properties, site/docs/api/sources-sinks.md, site/docs/operations/docker.md
*  Set the hazelcastDownloadId to `distribution` for tar.gz distribution
5ac586b 
* Add JET_MODULES variable to add jars from opt folder to classpath
=> Distribution improvements

hazelcast-jet-distribution/pom.xml, hazelcast-jet-distribution/src/assembly-descriptor.xml, hazelcast-jet-distribution/src/bin-filemode-755/jet-start, hazelcast-jet-distribution/src/root/NOTICE, hazelcast-jet-distribution/src/root/config/jmx_agent_config.yaml, pom.xml, site/docs/operations/monitoring.md
Add prometheus to base distribution, so it is present in the tar distribution and docker image.
Checklist
=> Add prometheus to base distribution

extensions/elasticsearch/elasticsearch-7/src/main/java/com/hazelcast/jet/elastic/ElasticSinkBuilder.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/CommonElasticSinksTest.java
Fixes tests failing in QE pipeline.
Checklist
=> Throw JetException from Elastic sink

site/docs/api/more-transforms.md, site/docs/api/sources-sinks.md
fix stale documentation regarding Sources#json
Checklist
=> [011] Add JsonUtil to more-transforms section

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java
Fixes #2266
Also log exceptions occurring in the coordinator thread, the exception
wasn't logged so it was hard to find out.
=> Fix CCE in onSnapshotPhase2Complete()

extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/DebeziumCdcSources.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSource.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/ChangeRecordCdcSource.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/DebeziumConfig.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/JsonCdcSource.java, extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/AbstractIntegrationTest.java, extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/DebeziumIntegrationTest.java, extensions/cdc-mysql/src/main/java/com/hazelcast/jet/cdc/mysql/MySqlCdcSources.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlAuthAndConnectionIntegrationTest.java, site/docs/design-docs/005-cdc-sources.md
Add a version of generic Debezium source which does no processing of the raw data.
Checklist
=> Define raw debezium source

site/docs/api/pipeline.md, site/docs/api/stateful-transforms.md, site/docs/api/stateless-transforms.md, site/docs/how-tos/custom-aggregate-operation.md, site/website/core/Footer.js, site/website/sidebars.json
* addTimestamps
* mapUsingPython
* earlyResults
* guide for building custom aggregations
=> Add missing docs from previous reference manual

site/docs/operations/kubernetes.md
This PR adds hazelcast official chart repository to the documentation.
=> Add hazelcast official helm repository

extensions/elasticsearch/elasticsearch-5/src/main/java/com/hazelcast/jet/elastic/ElasticSinks.java, extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/ElasticSinks.java, extensions/elasticsearch/elasticsearch-7/src/main/java/com/hazelcast/jet/elastic/ElasticSinks.java
=> Add code examples to ElasticSinks javadoc

site/docs/api/sources-sinks.md
=> Document failure scenarios for Elasticsearch connector

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/Contexts.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/IOUtil.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java
=> Fix file name extraction on Windows

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java, site/docs/design-docs/011-json-convenience.md
=> Remove json extentsion from json sources

extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/CdcSinksTest.java
Simple tests for CDC sink with reordering particular messages.
Checklist
=> Test for cdc sink reordering

extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcAuthAndConnectionIntegrationTest.java
=> Fix PostgresCdcAuthAndConnectionIntegrationTest

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartStressTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartStressTestBase.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TestProcessors.java
=> Minor test improvements

site/docs/enterprise/docker-enterprise.md, site/docs/operations/docker.md
Add all information contained in docker readme on docker hub.
=> Unify docker docs and readme

extensions/cdc-mysql/src/main/java/com/hazelcast/jet/cdc/mysql/MySqlCdcSources.java, extensions/cdc-postgres/src/main/java/com/hazelcast/jet/cdc/postgres/PostgresCdcSources.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcIntegrationTest.java
Port https://github.com/hazelcast/hazelcast-jet/pull/2378 to release branch.
Checklist
=> [005] Make Postgres dataloss on snapshot-stream sync less severe (4.2 port)

site/docs/api/sources-sinks.md, site/docs/operations/cdc.md, site/docs/tutorials/cdc-join.md, site/docs/tutorials/cdc-mysql.md, site/docs/tutorials/cdc-postgres.md, site/docs/tutorials/cdc.md, site/website/sidebars.json
=> [005] - Add CDC Join tutorial and fix other minor issues

site/docs/api/sources-sinks.md, site/docs/operations/cdc.md, site/docs/tutorials/cdc-join.md, site/docs/tutorials/cdc-postgres.md, site/docs/tutorials/cdc.md, site/website/sidebars.json
=> [005] - Add CDC Join tutorial and fix other minor issues, prod branch migration

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/observer/ObservableImpl.java
=> Handle missed exception type in observer listener

site/website/modules.json, site/website/pages/en/download.js
Add the contrib modules to the download page of our website. 
Checklist
=> Add Contrib. Modules to the Download Page

examples/README.md, examples/cdc/pom.xml, examples/cdc/src/main/java/com/hazelcast/jet/examples/cdc/Cache.java, examples/cdc/src/main/java/com/hazelcast/jet/examples/cdc/Customer.java, examples/pom.xml
=> [005] Add CDC example

extensions/cdc-debezium/pom.xml, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSource.java, extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/DebeziumCdcIntegrationTest.java, extensions/cdc-mysql/pom.xml, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcWhiteBlackListIntegrationTest.java, extensions/cdc-postgres/pom.xml, extensions/cdc-postgres/src/main/java/com/hazelcast/jet/cdc/postgres/PostgresCdcSources.java, hazelcast-jet-distribution/src/root/NOTICE
=> [005] Upgrade to Debezium 1.2.1.Final

extensions/assembly-descriptor-module.xml
=> Package modules as tar.gz instead of zip

site/website/modules.json
=> Add elasticsearch-6 module to downloads

README.md
Fix an import in code snippet and corrects some formatting
=> Fix a minor problem in the README code snippet

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestSupport.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadMapOrCacheP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadMapOrCachePTest.java
=> Fix cooperative emission in ReadMapP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetInstanceImpl.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceP_IntegrationTest.java
This PR does not attempt to solve the root cause, which is a snapshot stuck in Phase 2.
Checklist
Fixes #2452
=> Fix stuck test due to stuck snapshot in AsyncTransformUsingServiceP_IntegrationTest

extensions/elasticsearch/elasticsearch-5/src/test/java/com/hazelcast/jet/elastic/ElasticSinkBuilderTest.java, extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/ElasticSinkBuilderTest.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/ElasticSinkBuilderTest.java
=> Remove retries in a test, unify test across elastic versions

extensions/elasticsearch/elasticsearch-5/src/test/java/com/hazelcast/jet/elastic/BaseElasticTest.java, extensions/elasticsearch/elasticsearch-5/src/test/java/com/hazelcast/jet/elastic/LocalElasticSinkTest.java, extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/BaseElasticTest.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/BaseElasticTest.java
=> Close all clients created in Elastic tests

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SourceBuilderTest.java
This PR adds logging for stream-socket test to see if the missing items are related to the stream source or aggregation afterwards.
Checklist
related to #2460
=> Add logging for stream socket test

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/VertexDef.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/MetricsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Blocking.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Snapshots.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Watermarks.java
=> Fix source=true tag in metrics

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java
The `JobCoordinationService.getJobStatus()` only checked the
`JobExecutionRecord`, but not the `JobRecord`. However, right after the
`JetInstance.newJob()` returns, only the latter is guaranteed to exist.
It could happen that `getJobStatus()` could throw `JobNotFoundException`
if called right after submitting the job using `newJob`.
The failure was rare because after `newJob` the `MasterContext` always
exists. But in the test we regularly restart cluster members and it
could happen after a new master takes over: the `MasterContext` isn't
created yet, nor is `JobExecutionRecord` or `JobResult`, but we didn't
look at `JobRecord`. With some luck, the issue is reproducible by adding
a 1-second sleep at the beginning of `tryStartJob()`.
The fix is to make `jobRecordHandler` parameter of …
=> Fix JobCoordinationService race

pom.xml
=> Use runOrder random for tests

extensions/elasticsearch/elasticsearch-6/src/root/NOTICE, hazelcast-jet-distribution/src/root/NOTICE
=> Fix versions in NOTICE files

site/docs/api/sources-sinks.md
Add http connector to sources/sinks page
Checklist
=> Add http connector to sources/sinks page

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamSocketP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamSocketPTest.java
Also speed up the test (from 50 to 3 seconds)
Fixes #2491
=> Fix StreamSocketP failure

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/test/TestSourcesTest.java
I decreased the number of items in tests because tests are failed with this many items.
Checklist
Fixes #2482
=> Convert the test_longStream to a slightly tolerant test

pom.xml
=> Set forkCount=4 for regular tests

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/TerminationMode.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/SnapshotContext.java
One stale comment also removed.
=> Remove unused CANCEL_GRACEFUL mode

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/TerminationMode.java
This reverts commit 3b4dda416381a30c2e8d562b9392779f19a2fc3f.
=> Revert "Remove unused CANCEL_GRACEFUL mode (#2506)"

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java
Fix needed for [Enterprise PR #131](https://github.com/hazelcast/hazelcast-jet-enterprise/pull/131).
Checklist
=> Fix removing MC after cancelAndExportSnapshot

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamStageTest.java, pom.xml
The issue was fixed in IMDG, this PR adds a test to fix it.
Close #2511
=> Add test to check fixed thenApply behavior

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteFilePTest.java
=> Add logging to WriteFilePTest

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SuspendExecutionOnFailureTest.java
=> [012] Add test for resume job after suspension on failure

hazelcast-jet-distribution/src/root/config/hazelcast-jet.yaml, site/docs/operations/configuration.md
=> Improve default config file and docs on config options

extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/ChangeRecord.java, site/website/blog/2020-04-01-upgrading-to-jet-40.md, site/website/blog/2020-09-18-cdc-meets-stream-processing.md
Blog post on Debezium-Jet integration.
=> CDC blog post

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/DelegatingSerializationService.java, site/docs/api/serialization.md
=> Improve documentation for serializer registration

hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperationBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/aggregate/AggregateOperation3Impl.java
=> Improve AgregateOperationBuilder documentation

pom.xml
=> IMDG 4.0.3-SNAPSHOT now 4.0.3

site/website/blog/2020-09-18-cdc-meets-stream-processing.md
Debezium guys requested a clarification in the blog post, related to licensing.
=> Change license related wording of CDC blog post

site/docs/design-docs/014-batchstage-sort.md
=> TDD for BatchStage.sort()

site/website/blog/2020-07-16-designing-evergreen-cache-cdc.md
Needing the cache host to be a Jet cluster (as opposed to plain Hazelcast one) is not ok for the scenario addressed by the [blog post](https://jet-start.sh/blog/2020/07/16/designing-evergreen-cache-cdc). It's better to just not handle deletions. For that reason I'm reverting the changes I've made in #2519.
=> Revert previous changes to the Evergreen Cache blog post

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsSinkIntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/SinkStressTestUtil.java
=> Increase test timeout in JMS Sink test

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ReceiverTasklet.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/MemberReconnectionTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/OperationLossTest.java
=> Use RestartableException when members reconnect

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStage.java
=> Fix BatchStage.sort() javadoc

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/MemberReconnectionStressTest.java, pom.xml
=> Fix remote ops failure handling in job coordination

extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java
Found by Sonar
Checklist
- [N/A] Breaking changes documented
=> Close stream in Python editPermissionsRecursively

site/docs/api/error-handling.md, site/website/sidebars.json
Needed as a discoverable place about the whole error handling topic.
=> Add programming guide for error handling

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_BatchTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_StreamTest.java
One of our tests is very confusing, due to its name, so need to change that.
Also need to make use of constant metric names in tests, since we have them.
=> Fix minor test problems

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java
This extra logging statement should help with understanding the cause of #2572.
=> Add extra logging to understand MetricsTest issues

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Edge.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/EdgeDef.java
Porting from 4.3 release branch to master.
=> Forward Port: Use custom CL for Comparator serialization (#2582)

extensions/python/src/main/java/com/hazelcast/jet/python/PythonService.java, extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java, extensions/python/src/test/java/com/hazelcast/jet/python/PythonInitCleanupTest.java
Retry initialization of PythonService context
forward-port of https://github.com/hazelcast/hazelcast-jet/pull/2586
=> Retry initialization of PythonService context

pom.xml
We have a test failure related to Mockito #2462.
Before reporting a bug to Mockito, upgrading to the latest version to make sure it is not already resolved issue.
=> Upgrade Mockito version

extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSource.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadJdbcP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteJdbcP.java
=> Fix JDBC driver initialization deadlock [forward port of #2604]

extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/AbstractCdcIntegrationTest.java, extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/DebeziumCdcIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/AbstractMySqlCdcIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/AbstractPostgresCdcIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcNetworkIntegrationTest.java
Migrate CDC test container related fixes from `master`
Checklist:
=> Migrate CDC test container related fixes from `master`

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteFileP.java
=> Fix WriteFileP.isCooperative (backport of #2628)

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteFileP.java
=> Fix WriteFileP.isCooperative

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java
Fixes #2608. It was supposed to be fixed in #2507, but the fix was
incomplete, it only reduced the chances.
=> Fix getJobStatus race

README.md
=> Document PR trigger phrases in README

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobResult.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/UtilTest.java
=> Format job duration

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/JobStatus.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/IMapSqlConnector.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/logical/LogicalRules.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/type/converter/ToConverter.java
A collection of trivial changes to make `master` and `sql-prod` branches as close as possible.
=> SQL leftovers

hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/SqlJobManagementTest.java
Cleaned up tests - consistently using one mechanism for exceptions.
Checklist:
=> Cleanup tests

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/NodeExtensionCommon.java
Add IMDG version message to printNodeInfo.
Fixes #2583
Checklist:
=> Log IMDG version

extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/AbstractMySqlCdcIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/AbstractPostgresCdcIntegrationTest.java
=> Specify reconnect behavior in CDC integration tests

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/kafka/KafkaSqlConnector.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/kafka/PropertiesResolver.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/PropertiesResolverTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlAvroTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlJsonTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlPrimitiveTest.java
Added Kafka (de)serializers inference when possible.
Checklist:
=> Infer Kafka (de)serializers

site/docs/api/sources-sinks.md
=> Add map entry removal usage to the docs

hazelcast-jet-all/src/test/java/com/hazelcast/jet/server/JetCommandLineTest.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/JetPlan.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/JetSqlBackend.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/JetPlanExecutorTest.java
=> Check IMap security for sql

site/docs/api/sources-sinks.md
Fixes https://github.com/hazelcast/hazelcast-jet/issues/1468
Checklist:
=> Add compatibility matrix for Jet and IMDG

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/JetQueryResultProducer.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/JetSqlResultImpl.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/JetSqlResultImplTest.java
=> Fix JetSqlResultImpl.close()

site/docs/tutorials/cdc-postgres.md, site/docs/tutorials/cdc.md, site/docs/tutorials/kafka.md, site/docs/tutorials/map-join.md, site/docs/tutorials/pulsar.md, site/docs/tutorials/python.md, site/docs/tutorials/spring-boot.md, site/docs/tutorials/windowing.md
=> Remove deprecated compile from gradle tutorials

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/JetPlanExecutor.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/SqlJobManagementTest.java, site/docs/design-docs/015-mqtt-connector.md
=> Fix DROP JOB returning too early

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetBootstrap.java
=> Disable auto-detection to have standalone bootstrapped instance

site/docs/design-docs/016-event-reordering.md
=> Fix: TDD numbering

site/docs/design-docs/015-mqtt-connector.md
=> Mqtt design decision regarding fault tolerence 

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/MockLoggingFactory.java
fixes compilation issue
Checklist:
=> Implement noop removeLogger for MockLoggingFactory

site/docs/sql/kafka-connector.md
=> Fix copy-paste error in Kafka SQL docs

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/MockLoggingFactory.java
should be merged after https://github.com/hazelcast/hazelcast/pull/17962
Checklist:
=> Revert removeLogger

hazelcast-jet-sql/pom.xml
Fixes issue when querying json from kafka topic.
Checklist:
=> Fix relocation of jackson packages in sql module

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/schema/MappingStorage.java
A temporary (& not ideal) solution for cluster mapping propagation.
=> Wait for SQL mapping propagation to all members

site/docs/sql/job-management.md
=> Correct snaphsot documentation

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataAvroResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataJavaResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/schema/MappingCatalog.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/schema/MappingCatalogTest.java
=> Provide error message for `ClassNotFoundException` while resolving mappings.

site/docs/api/sources-sinks.md, site/docs/operations/configuration.md, site/docs/sql/ddl.md, site/docs/sql/file-connector.md, site/docs/sql/imap-connector.md, site/docs/sql/kafka-connector.md
=> Improve SQL file connector documentation

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataJsonResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/MetadataJsonResolver.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlAvroTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlJsonTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlPojoTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlJsonTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlPojoTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlPortableTest.java, site/docs/sql/kafka-connector.md
Improved JSON invalid fields error messages (addresses #2759 & #2758). Added missing/unified tests.
=> Improve JSON invalid fields error messages.

site/docs/api/pipeline.md, site/docs/architecture/distributed-computing.md, site/docs/design-docs/016-event-reordering.md
This PR updates the programming guide for event reordering
Checklist:
=> Update the doc of event reordering

site/docs/sql/basic-commands.md, site/docs/sql/file-connector.md, site/docs/sql/imap-connector.md, site/docs/sql/intro.md
=> Improve SQL Docs

site/docs/sql/kafka-connector.md, site/website/attributes.json
=> Fix two issues in SQL docs

extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/StreamKafkaPTest.java
Fixes the 2nd cause in
https://github.com/hazelcast/hazelcast-jet/issues/2810#issuecomment-762066997,
the original cause still remains an issue.
=> Fix race in StreamKafkaP

site/docs/sql/intro.md
=> Add Docker to SQL intro

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, site/docs/enterprise/index.md, site/docs/enterprise/installation.md, site/docs/enterprise/lossless-restart.md, site/docs/enterprise/management-center.md, site/docs/operations/version-compatibility.md
=> Decommision Jet Management Center

site/docs/operations/docker.md
Minor touchups in the Docker page.
Checklist:
=> Touch up Jet Docker page

site/docs/sql/intro.md
=> Add GROUP BY to SQL intro page

site/docs/sql/intro.md
=> Improve the opening sentence in SQL docs

hazelcast-jet-distribution/src/root/release_notes.txt
Jet 4.4 Release Notes
Checklist:
=> Release Notes

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/kafka/PropertiesResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataResolvers.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlPrimitiveTest.java
=> Fix adding of 'key.serializer' options

hazelcast-jet-distribution/src/root/changelog.txt
=> Changelog entry for 4.4

examples/kafka/pom.xml
=> Fix Kafka code sample for JDK14+

hazelcast-jet-distribution/pom.xml
=> Fixes to javadoc generation

site/website/blog/2021-02-03-jet-44-is-released.md
=> Fix absolute links in release blogpost

site/website/blog/2021-02-03-jet-44-is-released.md
=> Add Kinesis to 4.4 release blogpost

extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/DebeziumCdcSources.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/RecordPart.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSerializerHooks.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSourceP.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/ChangeRecordCdcSourceP.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/DebeziumConfig.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/JsonCdcSourceP.java, extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/AbstractCdcIntegrationTest.java, extensions/cdc-mysql/src/main/java/com/hazelcast/jet/cdc/mysql/MySqlCdcSources.java, extensions/cdc-postgres/src/main/java/com/hazelcast/jet/cdc/postgres/PostgresCdcSources.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/AbstractPostgresCdcIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/MultiTableCacheIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcListenBeforeExistsIntegrationTest.java, extensions/kinesis/src/main/java/com/hazelcast/jet/kinesis/KinesisSources.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java
=> Migrate fix for issue #2841 to 4.4-maintenance branch

extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/ChangeRecord.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/IOUtil.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/IOUtilTest.java
=> Fix the zip-slip vulnerability

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/JetPlanExecutor.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/JetQueryResultProducer.java
=> Preserve QueryException error codes while throwing SQL result errors

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/JetQueryResultProducer.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/processors/RootResultConsumerSink.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/JetSqlResultImplTest.java
=> Fix SqlResult close() test

site/docs/sql/ddl.md
Fixes #2923
However I'd bet that we'll not remove this note once we add `ORDER BY` :)
=> Clarify ORDER BY not supported

site/docs/sql/ddl.md
=> Correct OR REPLACE description

extensions/avro/src/test/java/com/hazelcast/jet/avro/AvroSourceTest.java, hazelcast-jet-distribution/src/root/NOTICE, pom.xml
=> Update avro version to 1.10.1 for avro module

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/infoschema/MappingsTable.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/parse/SqlCreateMapping.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/schema/MappingCatalog.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/infoschema/MappingsTableTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/infoschema/SqlInfoSchemaTest.java
Jsonized SQL mapping options.
Not pretty printing as CLI is rather limited in terms of width columns and/or multiple-lines rows.
Addresses #2931
=> Jsonize SQL mapping options

extensions/elasticsearch/elasticsearch-7/pom.xml, extensions/elasticsearch/elasticsearch-7/src/main/java/com/hazelcast/jet/elastic/impl/ElasticSourceP.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/AuthElasticSinksTest.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/AuthElasticSourcesTest.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/ElasticSupport.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/impl/ElasticSourcePTest.java, hazelcast-jet-distribution/src/root/NOTICE
=> Update ElasticSearch-7 to 7.10.0

extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/ElasticSupport.java
=> fix ElasticSearch docker image version

extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/AbstractCdcIntegrationTest.java, extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/CdcSinksTest.java, extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/DebeziumCdcIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/AbstractMySqlCdcIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcListenBeforeExistIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcWhiteBlackListIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/AbstractPostgresCdcIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/MultiTableCacheIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcListenBeforeExistsIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcNetworkIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcWhiteBlackListIntegrationTest.java
=> Fix SSH related issue in CDC tests

examples/hadoop/pom.xml, examples/python/pom.xml, extensions/elasticsearch/elasticsearch-5/pom.xml, extensions/elasticsearch/elasticsearch-6/pom.xml, extensions/elasticsearch/elasticsearch-7/pom.xml, extensions/hadoop-dist/files-azure/src/root/NOTICE, extensions/hadoop-dist/files-gcs/src/root/NOTICE, extensions/hadoop-dist/files-s3/src/root/NOTICE, extensions/hadoop-dist/hadoop-all/src/root/NOTICE, hazelcast-jet-distribution/src/root/NOTICE, pom.xml
=> Bump guava version to 30.1.

extensions/hadoop-dist/files-s3/src/root/NOTICE, extensions/kinesis/pom.xml, hazelcast-jet-distribution/src/root/NOTICE, pom.xml
Addressing the netty part of #2979
=> Bump aws sdk version to 1.11.976.

site/docs/api/sources-sinks.md
=> Improve readability in sources-sinks.md

extensions/hadoop-dist/files-azure/src/root/NOTICE, extensions/hadoop-dist/files-gcs/src/root/NOTICE, extensions/hadoop-dist/files-s3/src/root/NOTICE, extensions/hadoop-dist/hadoop-all/src/root/NOTICE, hazelcast-jet-distribution/src/root/NOTICE, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/extract/AvroQueryTarget.java, pom.xml
=> Update Avro to 1.10.1

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/test/ParallelStreamP.java
Addressed `ParallelStreamP` part of #2834
=> Remove printStackTrace() from ParallelStreamP

extensions/elasticsearch/elasticsearch-6/pom.xml, extensions/elasticsearch/elasticsearch-6/src/root/NOTICE, extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/ElasticSupport.java, extensions/elasticsearch/elasticsearch-7/pom.xml, extensions/elasticsearch/elasticsearch-7/src/main/java/com/hazelcast/jet/elastic/impl/ElasticSourceP.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/AuthElasticSinksTest.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/AuthElasticSourcesTest.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/ElasticSupport.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/impl/ElasticSourcePTest.java, extensions/hadoop-dist/files-azure/src/root/NOTICE, extensions/hadoop-dist/files-gcs/src/root/NOTICE, extensions/hadoop-dist/files-s3/src/root/NOTICE, extensions/hadoop-dist/hadoop-all/src/root/NOTICE, hazelcast-jet-distribution/src/root/NOTICE, pom.xml
Fixes https://github.com/hazelcast/hazelcast-jet/issues/2984
Fixes https://github.com/hazelcast/hazelcast-jet/issues/2983
Forward port of :
- https://github.com/hazelcast/hazelcast-jet/pull/2953
- https://github.com/hazelcast/hazelcast-jet/pull/2948
- https://github.com/hazelcast/hazelcast-jet/pull/2945
- https://github.com/hazelcast/hazelcast-jet/pull/2946
- https://github.com/hazelcast/hazelcast-jet/pull/2943
Checklist:
=> Security Vulnerabilities

extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSourceP.java
=> Fix NPE bug in CdcSourceP

extensions/s3/src/test/java/com/hazelcast/jet/s3/S3MockTest.java, extensions/s3/src/test/java/com/hazelcast/jet/s3/S3SinkTest.java, extensions/s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java
Fixes https://github.com/hazelcast/hazelcast-jet/issues/2853
Checklist:
=> Create directory for each test run in the bucket for isolation

hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlAvroTest.java
=> Fix random port allocation for schema registry in SqlAvroTest

extensions/hadoop-dist/files-azure/src/root/NOTICE, extensions/hadoop-dist/files-gcs/src/root/NOTICE, extensions/hadoop-dist/files-s3/src/root/NOTICE, extensions/hadoop-dist/hadoop-all/src/root/NOTICE, hazelcast-jet-distribution/src/root/NOTICE, pom.xml
=> Upgrade parquet to 1.12.0

pom.xml
=> Update IMDG to 4.2 and kubernetes plugin to 2.2.2

extensions/elasticsearch/elasticsearch-5/pom.xml, extensions/elasticsearch/elasticsearch-6/pom.xml, extensions/elasticsearch/elasticsearch-7/pom.xml, extensions/grpc/pom.xml, extensions/hadoop-dist/files-azure/src/root/NOTICE, extensions/hadoop-dist/files-gcs/src/root/NOTICE, extensions/hadoop-dist/files-s3/src/root/NOTICE, extensions/hadoop-dist/hadoop-all/src/root/NOTICE, hazelcast-jet-distribution/src/root/NOTICE, pom.xml
Fixes https://github.com/hazelcast/hazelcast-jet/issues/3017
Fixes https://github.com/hazelcast/hazelcast-jet/issues/3019
Fixes https://github.com/hazelcast/hazelcast-jet/issues/3020
Checklist:
=> More security

hazelcast-jet-distribution/src/root/changelog.txt, hazelcast-jet-distribution/src/root/release_notes.txt
=> Update release notes and changelog

hazelcast-jet-distribution/src/root/release_notes.txt
=> Update release notes

hazelcast-jet-distribution/src/root/release_notes.txt
=> Release Notes for 4.5.4

hazelcast-jet-distribution/src/root/release_notes.txt
=> Release notes for 4.5.4 [release branch]
