hazelcast/hazelcast-jet

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadIMapP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/PartitionArrangement.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/ExecuteJobOperation.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/JetSplitBrainTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/TopologyChangeMergeClusterTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/TopologyChangeSplitClusterTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/TopologyChangeTest.java, pom.xml
Do not fail job when new members join after execution is planned and even when those new members are removed.
PS: *According to our latest meeting on Friday, this change should target 0.3.1.*
=> Do not fail job when new members join

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Traversers.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/AbstractIntermediatePipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/AbstractPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/DistinctPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/DoublePipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/IntPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/LimitPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/LongPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/PeekPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/SkipPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/SortPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/TransformPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/UnorderedPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/processor/TransformP.java
`TransformP` implemented the same logic that was later encapsulated into `Traverser` and `AbstractProcessor`. This PR redoes the logic in terms of existing API.
=> TransformP in terms of Traverser

hazelcast-jet-kafka/pom.xml, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/connector/kafka/ReadKafkaP.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/connector/kafka/WriteKafkaP.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/connector/kafka/KafkaTestSupport.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/connector/kafka/ReadKafkaPTest.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/connector/kafka/WriteKafkaPTest.java
refactored ReadKafkaP to make use new consumer API
removed serializer/deserializer functions from ReadKafkaP/WriteKafkaP
refactored tests so that we rely on internal kafka test classes rather than an external project
=> Refactored Kafka read/write processors

hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/DistributedStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/AbstractPipeline.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/DistributedStreamCastingTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/DoubleStreamCastingTest.java
forEach is executed locally, so no need to check serializability
=> Do not require forEach action to be serializable

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java
Before, it was just e.g. `reader(ReadFileStreamP)#0`. This way, it wasn't
possible to enable the logger by its class name.
Now is changed to:
`com.hazelcast.jet.impl.connector.ReadFileStreamP.reader(ReadFileStreamP)#0`.
Our default setting is to display only the parte after last '.'. This way, we
see vertex name and class name and vertex instance id, this is importoant for
eventual logs from customres.
=> Change vertex logger to include complete class name

hazelcast-jet-core/src/main/java/com/hazelcast/jet/DAG.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/DAGTest.java
Refers the user to use `Edge.from().to()` instead of `Edge.between()`.
Intended to help for begginer users, who just don't yet know of edge ordinals.
=> Improve error message with duplicate ordinal

hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/DistributedCollectors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/AbstractPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/DoublePipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/IntPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/LongPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/reducers/GroupingIMapReducer.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/reducers/IListReducer.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/reducers/IMapReducer.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/reducers/MergingIMapReducer.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/Demo.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/DistinctTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/DoubleStreamTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/FilterTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/FlatMapTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/IntStreamTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/JetCollectorTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/LimitTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/LongStreamTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/MapTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/MultipleTransformsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/PeekTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/SkipTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/SortTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/UnorderedTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/stream/benchmark/WordCountTest.java
For real use cases, the name is required. At least, the user is aware, that a new map/list
is created.
Fixes #174
=> Add mandatory map/list name parameter to collector

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJetInstance.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetCacheManager.java
creating `CacheDecorator` in the `getCache` method of `JetInstance` triggers the loading of cache-api.
=> Added jet-cache-manager to conceal cache-api

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadFileStreamP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamFilesP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadFileStreamPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadFileStream_readCompleteLineTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadFilesPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesP_readCompleteLineTest.java
Previously, lines from appended files could be emitted in two chunks, if we
read the file with concurrent writing. Also, only appended lines from
pre-existing files will be read.
=> ReadFileStreamP should not emit incomplete lines

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamTextSocketP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/BlockingProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/CooperativeProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTaskletBase.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/Tasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/Contexts.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamTextSocketPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/CooperativeProcessorTaskletTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ExecutionServiceTest.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/connector/kafka/StreamKafkaP.java
The need is to allow for non-cooperative processor to check for job cancellation/failure, without returning from `complete()` method.
Solution moves the call to `Processor.init` from `Tasklet` constructor, which is called from `ExecutionPlan.initialize()` to `Tasklet.init()` method, because only then the `jobFuture` is available.
=> JobFuture in Processor.Context

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ExecutionServiceTest.java
A Jet job would fail when trying to deserialize a user's custom class fetched from a Hazelcast IMap. The same failure would arise in deserialization that follows a distributed edge.
The solution is to always set the job's custom classloader as the thread's context classloader before calling into a tasklet.
Fixes #387
=> Set job's classloader on each tasklet call

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Accumulators.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetSerializerHook.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/WindowOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/WindowOperations.java, hazelcast-jet-core/src/main/resources/META-INF/services/com.hazelcast.SerializerHook, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/init/JetSerializerHookTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/WindowOperationsTest.java
SlidingWindowP, if it has deductF, compares current accumulated value with
empty accumulator, and if it's equal, then removes the corresponding key.
`Object[]` doesn't implement equals, so I replaced it with MutableObject
=> Add mutable accumulators and fix equals for WindowOps.reducing

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Traverser.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/SlidingWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/WindowOperations.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/WindowingProcessors.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/GroupByFramePTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/SlidingWindowIntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/SlidingWindowPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/StreamingTestSupport.java, pom.xml
Improve tests:
- always check for memory leaks
- test SlidingWindowP with both with and without `deductF`
- compare expected and actual outbox as long string: easier to see differences
=> Increase test coverage for SlidingWP and GBFP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/WindowOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/WindowingProcessors.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/AbstractProcessorTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/ProcessorsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/GroupByFramePTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/windowing/SlidingWindowPTest.java
- improve `AbstractProcessorTest` to cover 100% lines of `AbstractProcessor`
- use `Supplier<Processor>` for the return type of factory methods
- simplify `ProcessorsTest` to focus on the business logic of specific processors (cooperative emission is tested through `AbstractProcessorTest`)
- some Javadoc
=> Test coverage and minor improvements

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteBufferedP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/ProcessorsTest.java
Some factory methods used `ProcessorSupplier` even though they could have used the simpler `Supplier<Processor>`.
=> Supplier<Processor> instead of ProcessorSupplier

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamTextSocketP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadFilesPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesP_readCompleteLineTest.java
This makes StreamFilesP in-line with ReadFilesP which has that option.
It also allows for use case where users create `.tmp` files and then rename them to real file name and only then want them to be processed, as mentioned in the PRD.
=> Add glob to StreamFilesP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetSerializerHook.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/WindowOperations.java, hazelcast-jet-core/src/main/resources/META-INF/services/com.hazelcast.SerializerHook
`WindowOperation`'s accumulator needs to correctly implements `equals`. For
this reason we cannot use `Object[]`. We used `Arrays.asList`, however this
class is not hz-serializable, and cannot be made one because it returns a
private class. So we replace with `ArrayList`.
=> Fix WindowOperations.allOf hz-serializability

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Traversers.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/FlatMappingTraverser.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/windowing/InsertPunctuationP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/FlatMappingTraverserTest.java
The `newNullTraverser()` was required to always create an unique
instance. This requirement is specific to `FlatMappingTraverser`,
however, a `nullTraverser() ` method returning a singleton is useful in
public API.
=> Move specific newNullTraverser out from public API

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/PeekWrappedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/WrappingProcessorMetaSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/WrappingProcessorSupplier.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/Processors_peekTest.java
It worked correctly when inbox was drained using peek+remove. If it was
drained using `poll()` there was an `NPE` and secondly, `poll()` returned
`true` instead of the polled object.
Second improvement is that when using peek+remove, the item is logged in
`peek`, not in `remove`, which is called after processing the item in
`AbstractProcessor`, which in turn caused the output items being logged before
input items in case of `peekInput(peekOutput(processor))`.
Another bug was not using `Distributed` version of function.
Also updated the test to test these scenarios.
=> Fix bug in PeekWrappedP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionService.java
Previously, tasklets for a job were assigned to cooperative workers always
starting from worker 0. This could lead to the last worker to have less
tasklets assigned, or even none in extreme cases (such as many small DAGs with
local parallelism of 1 on all vertices, a setting typical if there are many
jobs).
This change makes the starting index global. Work stealing didn't help here
because it only takes place when worker dismissed some tasklet, which works
with assumption that it was balanced before.
=> Add fair distribution of tasklets

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteLoggerP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ExecutionServiceTest.java
- `Processors.writeLogger()` accepts `Function<T, String>` instead of
`Function<Object, String>`. This is not applicable to `toStringF` in
`peekInput`, because it can see both items and `Punctuation`s.
- test for adding two cooperative tasklets in two jobs to different threads
- bit simpler code in ExecutionService
=> Minor improvements

hazelcast-jet-core/src/main/java/com/hazelcast/jet/AggregateOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/WindowingProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/accumulator/LongAccumulator.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedFunctions.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AggregateOperationImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AggregateP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/GroupByKeyP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SessionWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SlidingWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/TransformP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/AggregateOperationsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/ProcessorsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/benchmark/WordCountTest.java
- align group-by-key processors with those in windowing (single-stage, two-stage)
- use `AggregateOperation` in batch processors
- extract private static processor classes to top level
- reorder factories, improve javadoc
=> Reorganize batch processor factories

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamSocketP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteBufferedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteFileP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/processor/Sinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/processor/Sources.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamSocketPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamSocketP_integrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteBufferedPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteSocketTest.java
- rename `streamTextSocket()` to `streamSocket()`: analogous to other "text" connectors
- add `toStringF` and `charset` parameters to `writeSocket()`
- fix closing of socket & file when the job is cancelled
=> Fix, rename and improve socket connectors

.gitignore, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java
Processors are now registered to MetricsRegistry and will be scanned
for probes during creation. The output of probes can be viewed by
enabling the `-Dhazelcast.diagnostics.enabled=true` option.
=> Add support for adding Probes to Processors

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Edge.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Vertex.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedComparator.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlanBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/StreamUtil.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/AbstractPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/DoublePipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/IntPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/LongPipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/impl/pipeline/PeekPipeline.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/Processors_slidingWindowingIntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/function/DistributedComparatorTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteBufferedPTest.java
ProcessorMetaSupplier must be serializable. Out-of-the-box metasuppliers can become non-serializable if they are passed a non-serializable lambda. Currently the job fails if run on multiple instances and the problem is harder to spot, because it fails when serializing the ExecutionPlan, which might contain lot of lambda expressions.
This PR makes this problem easier to spot and will also make the job fail even when using single Jet member.
=> Fail fast when adding non-serializable processor supplier

hazelcast-jet-core/src/main/java/com/hazelcast/jet/AggregateOperations.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/InstanceConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AggregateOperationImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/ResourceStore.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/ProcessorsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/config/XmlConfigTest.java
There were 3 references to JetClassLoader kept:
- from `JetService` by not cleaning the `JetClassLoader` and
`resourceStores` map
- from `ClassLoaderWeakCache`, which keeps reference to class loader as
a key
- from MetricsRegistry, because it keeps references to Class objects
=> Fix class unloading

hazelcast-jet-core/src/main/java/com/hazelcast/jet/TimestampedEntry.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Watermark.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/InsertWatermarksPTest.java
ResourceStore is lazily initialized, it might happen that job completes
before it happens. In my case, missing class (that should have been
added with addClass()) caused it.
Also includes unrelated formatting of timestamp in TimestampedEntry.
=> Fix NPE when releasing uninitialized ResourceStore

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Pipeline.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/impl/ComputeStageImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/impl/PipelineImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/impl/Planner.java
A "leakage" occurs when a ComputeStage has nothing attached to it (its output goes nowhere).
=> Validate pipeline against leakages

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/InitOperation.java
this fixes the resource upload problem to the participants
=> use jobId to retrieve classloader instead of executionId

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/TopologicalSorter.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/impl/AbstractStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/impl/ComputeStageImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/impl/PipelineImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/impl/Planner.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/impl/SinkStageImpl.java
TopologicalSorter now demands a fully populated map: every vertex appearing in some value must appear as a key as well.
PipelineImpl now makes a safe copy of its adjacency map.
=> Simplify adjacency map logic

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetSplitBrainTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java
If a job enables split brain protection, JobCoordinationService prints a log when the current quorum value of the cluster becomes bigger than quorum value of the job. The log is printed because the job loses its split brain protection feature in this case. If the cluster splits into partitions, the job can be successfully restarted on both sides.
=> Log if current cluster quorum value passes quorum value of a jet job

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJobImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/benchmark/BackpressureTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/CancellationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetSplitBrainTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncMapWriterTest.java
If the cluster is not safe when a job is submitted, it could happen that the job could be started before partition re-distribution is completed. To prevent such non-optimal runs, we delay starting execution of a job if the cluster is not safe at job submission time.
Recent `warmUpPartitions()` changes in the test classes are also reverted.
=> Delay job start if cluster is not safe

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/BroadcastKey.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/SnapshotOutbox.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/BroadcastKeyReference.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionSerializerHooks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/InsertWatermarksP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SlidingWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/SerializerHookConstants.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ExecutionSerializerHooksTest.java
SlidingWindowP instances should save unique ‘nextWmToEmit’ values and
validate they are all same on snapshot restore.
=> Add id field to BroadcastKey

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJobImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/StoreSnapshotTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/JoinSubmittedJobOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/SubmitJobOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/ExceptionUtil.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncMapWriterTest.java
This ensures that any exception which may occur during a whenComplete 
call is handled.
=> Make sure that all whenComplete calls wrap the callback in “withTryCatch”

hazelcast-jet-core/src/main/java/com/hazelcast/jet/ComputeStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ComputeStageImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/Planner.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/transform/GroupByTransform.java
- add variance to AggregateOperation arguments
- use `Map.Entry` instead of `Tuple2` for co-grouped results
=> Improve signature of coGroup

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/SnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SlidingWindowP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/SnapshotContextTest.java
The `SnapshotContext.startNewSnapshot()` method can be called _after_ `taskletDone()` or `snapshotDoneForTasklet()` is called. This can happen in a situation when a processor only has input queues from remote members and the remote members happen to process `SnapshotOperation` and send barriers to such processor before the `SnapshotOperation` is called on this member.
=> Allow snapshotDone before snapshotStarted

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Traverser.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestSupport.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamEventJournalP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SlidingWindowP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncMapWriter.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStreamTest.java
It could happen that even in exactly once mode, the WM and barriers
could be reordered with respect to each other.
This was caused by the fact that we could stop at a barrier in one queue,
that would cause the barrier to be emitted, but we continued to another
queue which drained a watermark, which would also cause a WM to be
emitted. After iterating all queues, we first checked for WM to emit and
then for barrier to emit, effectively causing the reordering. It was
fixed by moving the emit check inside to the loop and breaking the
iteration if we emitted either WM or barrier.
ItemDetector was simplified too along the way.
=> Fix CIES to not reorder WM and barrier

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetInitDataSerializerHook.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetSplitBrainTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/JobRepositoryTest.java
When a new member is added to the cluster, quorum sizes of split-brain protection enabled jobs can be invalidated. To prevent issues, JobCoordinationService automatically updates quorums.
=> Update quorum size of jobs when the Jet cluster scales up

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/ProcessingGuarantee.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/AbstractProcessor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/Contexts.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/InsertWatermarksP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SlidingWindowP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Blocking.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Snapshots.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowP_failoverTest.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/HdfsSinks.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/KafkaSinks.java
Document the possibility of watermarks going back after restart of a job with at-least-once guarantee. Fix the assert in SlidingWindowP to allow it.
=> Fix failure in SliWP for at-least-once jobs & docs

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/Networking.java
Otherwise we will get NullPointerExceptions if the member was just shutdown, for example.
=> Add null check before trying to transmit flow control packet

hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/impl/connector/hadoop/ReadHdfsP.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/impl/connector/hadoop/WritableSerializerHooks.java
While instantiating any class, we must pass the context classloader (which is job classloader)
=> Pass classloader while instantiating class

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaP.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/KafkaTestSupport.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaPTest.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/WriteKafkaPTest.java
This can cause watermarks to lag behind indefinitely.
=> StreamKafkaP should throw when there are not enough partitions

hazelcast-jet-core/src/main/java/com/hazelcast/jet/JoinClause.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sources.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SinkProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SourceProcessors.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/ComputeStageTest.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/HdfsSinks.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/HdfsSources.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/core/processor/HdfsProcessors.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/KafkaSinks.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/KafkaSources.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/core/processor/KafkaProcessors.java
Current names were taken over from the underlying Core API vertex names.
This PR adapts them to better fit the Pipeline API.
=> Simplify the names of sources and sinks

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorP.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaP.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/WriteKafkaP.java
add try/catch block for kafka consumer poll to catch the InterruptException while cancelling the job.
add null check to complete method of ProcessorSupplier for WriteHdfsP, WriteKafkaP and ReadWithPartitionIteratorP
Fixes https://github.com/hazelcast/hazelcast-jet/issues/567
=> StreamKafkaP interrupt fix and ProcessorSupplier.complete null check

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/ReflectionUtils.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ReflectionUtilsTest.java
Java SE 7 does not specify any standard modifiers. Some implementations
use custom modifier, but we should not have a hard dependency on them.
This changeset will use the HIGH-sensitivity modifier whenever possible,
yet it will fallback to a default mode when the custom modifier is unavailable.
=> WIP: Read Sensitivity Modifiers via reflection

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Job.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJobImpl.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java
When a job is cancelled, instead of JobStatus.COMPLETED return
the actual status. Fixes #579.
=> Return actual job status on job cancellation

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/CloseableProcessorSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/Networking.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/SnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/Tasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/CompleteOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/ExecuteOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/InitOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/SnapshotOperation.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TestProcessors.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TestUtil.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Blocking.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Snapshots.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/TaskletExecutionServiceTest.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaPTest.java
This supports more flexible execution flow and avoids the
race between job cancellation and completion. Fixes #589
=> Avoid race between job cancellation and job completion

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/CloseableProcessorSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/Networking.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/SnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/Tasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/CompleteOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/ExecuteOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/InitOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/SnapshotOperation.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TestProcessors.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TestUtil.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Blocking.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Snapshots.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/TaskletExecutionServiceTest.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaPTest.java
Replace `doneCallback` in TaskletExecutionService and ExecutionContext
with a single `executionFuture` which signals tasklet completion to simplify
execution flow and avoid races between job cancellation and completion.
Cancellation is now done through a separate future which is only used for
signalling cancellation.
=> [Backport] Avoid race between job cancellation and job completion (#604)

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/KafkaSinks.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/WriteKafkaP.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/KafkaSinkTest.java
KafkaProducer.send() call is async. This scenario was possible:
- send a record
- do a successful snapshot
- member fails before the async record is sent
- after restart, the record is lost and the at-least-once guarantee broken.
This was resolved that the processor ensures that all async calls are
done at the time of snapshot.
Another fixes:
- calling `producer.flush()` after each batch of items
- checking for errors from async calls
Fixes #605
=> Fix Kafka writer issues

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/KafkaSinks.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/WriteKafkaP.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/KafkaSinkTest.java
`KafkaProducer.send()` call is async. This scenario was possible:
- send a record
- do a successful snapshot
- member fails before the async record is sent
- after restart, the record is lost and the at-least-once guarantee broken.
This was resolved by calling `producer.flush()` in `saveToSnapshot()`.
Another fixes:
- checking for errors from async calls
- improve `Processor.tryProcess()` javadoc
Fixes #605
=> [Backport of #611] Fix Kafka writer issues

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/JetTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java
* Don't inherit default config for Jet maps
Fixes #592
* Fix JobRestartWithSnapshotTest on Enterprise HZ
Fixes #591
* Make the internal objects prefix public
Fixes #583
=> Hat-trick fix (backport of #594)

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SnapshotFailureTest.java
* Increase timeout
* Prevent further snapshots from being completed to prevent
snapshot record being deleted.
Fixes #641
=> Fix for when_snapshotStartedBeforeExecution test

checkstyle/suppressions.xml, pom.xml
The Java compiler plugin version was inherited from the Hazelcast IMDG project and is very old.
=> Upgrade Maven Java Compiler plugin

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Sinks.java
The current doc erroneously states that the other map-updating sinks, `mapWithMerging` and `mapWithUpdating`, don't achieve data locality.
The PR also reorders methods in `Sinks`, putting the simple `map()` sink above the more advanced ones.
=> Fix Javadoc for mapWithEntryProcessor

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/JetDataSerializerHook.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/SerializationConstants.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/SinksTest.java
Replace internally used AbstractEntryProcessor inside updatingMap with a counterpart which implements IdentifiedDataSerializable to prevent Java Serialization.
Fixes #671
=> Fix Java Serialization issue on mapWithUpdating

hazelcast-jet-core/src/main/java/com/hazelcast/jet/accumulator/DoubleAccumulator.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SlidingWindowP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowPTest.java
Partially late events caused that one value was combined to
`slidingWindow` and modified value will be deducted, causing computation
errors.
=> Drop partially late events in SliWP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperationBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperations.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AllOfAggregationBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/WatermarkGenerationParams.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/Tuple2.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/Tuple3.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedTriFunction.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/aggregate/AggregateOperationsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/WatermarkSourceUtilTest.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/KafkaSources.java
Before, `AggregateOperations.allOf` wrapped the result to a 
`List<Object>`, which is type-unsafe. This commit replaces it with 
a special versions that uses either `Tuple2`, `Tuple3` or `ItemsByTag` 
in the general case.
=> Modify allOf to use TupleN or ItemsByTag

hazelcast-jet-core/src/main/java/com/hazelcast/jet/JetInstance.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamFilesP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesPTest.java
Other fixes:
- Fix the case when EOF is encountered mid-line and the reading of the
line resumes later
- The processor tried to finish watcher events after it was closed,
which is nonsense. It's only closed when the job is cancelled or the
watched directory was deleted. In neither case we should continue the
work.
- Updated the test to check cooperative emission.
- Fix TestProcessorContext.getLogger: the logger was created in
constructor even though the vertexName or globalProcessorIndex could be
changed later
Fixes #658
=> Fix cooperative emission in StreamFilesP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperationBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperations.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/AbstractProcessor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Outbox.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/JetAssert.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestInbox.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestOutbox.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorMetaSupplierContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorSupplierContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestSupport.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadIListP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/OutboxImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/PeekWrappedP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/AbstractProcessorTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/PeekingWrapperTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ProcessorsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/test/TestOutboxTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadIListPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamEventJournalPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamSocketPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/OutboxImplTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/InsertWatermarksPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/InsertWatermarksP_IntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SessionWindowPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowP_twoStageSnapshotTest.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaPTest.java
Check outbox.offer not called without returning
Another changes:
- check, if the object passed to offer is the same in TestOutbox
- move the method to drain an outbox from TestSupport to TestOutbox
=> Fail when outbox.offer() called again without returning

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/InsertWatermarksPTest.java
Fixed `TestSupport`: it now creates new outbox when it creates new
processor: after snapshot restore, the processor is allowed to offer
different item due to reordering.
Two failures:
- StreamEventJournalPTest.smokeTest:
```
java.lang.AssertionError: Different item provided after offer() was
rejected
```
- time-based failure in
InsertWatermarksPTest.when_idleTimeout_then_idleMessageAfterTimeout
=> Fix intermittent test failures

hazelcast-jet-client-protocol/src/main/java/com/hazelcast/client/impl/protocol/template/JetCodecTemplate.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Job.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ClientJobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetMessageTaskFactoryProvider.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetRestartJobMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/exception/JobRestartRequestedException.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetInitDataSerializerHook.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/AsyncOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/CancelExecutionOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/CancelJobOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobConfigOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobStatusOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobSubmissionTimeOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/InitExecutionOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/RestartJobOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/CompletionToken.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ManualRestartTest.java
A new method is added to the Job interface. If the user calls job.restart() while a job is running, the job is restarted on the current member list of the cluster from the last successful snapshot. The new method can be used as a non-graceful way of achieving elasticity.
=> Introduce manual job restart

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/Processors.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/Processors_slidingWindowingIntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowP_FrameCombiningTest.java
Will allow this scenario:
- 1st sliding window stage will accumulate into tumblingWindowDef(10sec)
- 2nd stage will combine into slidingWindowDef(5min, 1min)
So 1 2nd stage window will combine 6 1st stage frames into 1 frame.
This is useful if you want to connect multiple 2nd stages to single 1st
stage and use different `slideBy` parameter.
=> Group frames in 2nd stage sliding window

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TestProcessors.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/JobRepositoryTest.java
- Fix 1: we relied on `EntryView.getCreationTime`, but we have
statistics disabled.
- Fix 2: we repeatedly tried to delete maps for completed jobs in a way
that created and destroyed the distributed object. Now we try only once.
Fixes #653
=> Fix & improve resources cleanup

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/ProgressTracker.java
a trivial change. the JavaDoc should have been updated by https://github.com/jerrinot/hazelcast-jet/commit/8b5f25fdc65d5308161244327b3d05647c95292d#diff-bc7c1bd4228a368e23974518c7fd84cfR51
=> Obsolete JavaDoc updated

hazelcast-jet-core/src/test/java/com/hazelcast/jet/annotation/IgnoredForCoverage.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/AbstractDeploymentTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/LoadPersonIsolated.java, pom.xml
Fixed the InvalidClassExceptions by using explicit Processor(Meta)Supplier implementations and ignored the j.u.s test which cannot be fixed that way in the sonar build.
Fixes #706
=> Fix Sonar Build Issues

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/HazelcastConnectorTest.java
Fixes #735
```
java.lang.AssertionError: expected:<2> but was:<1>
at com.hazelcast.jet.impl.connector.HazelcastConnectorTest.lambda$test_defaultFilter_mapJournal$12(HazelcastConnectorTest.java:344)
at com.hazelcast.jet.impl.connector.HazelcastConnectorTest.test_defaultFilter_mapJournal(HazelcastConnectorTest.java:343)
```
=> Attempt to fix test failure

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorMetaSupplierContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorSupplierContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/Contexts.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlanBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/VertexDef.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/PeekWrappedP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Blocking.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Snapshots.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Watermarks.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/core/processor/KafkaProcessors.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaP.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaPTest.java
New additional fields of `localParallelism` and `totalParallelism` are now available in `Processor `and `ProcessorSupplier` level. 
Also made them extend the upstream interfaces, so that gradually more information is available in each context as you drill down.
=> Make parallelism available to ProcessorSupplier.Context and Processor.Context

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java
Looks like the failure was due to the job finishing before we shut down
the second member. This commit increases the job duration. It also
increases test duration from 17 to 23 seconds (locally).
Fixes #717
=> Fix JobRestartWithSnapshotTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/EdgeConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/InstanceConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/SerializableClientConfig.java, hazelcast-jet-core/src/main/resources/hazelcast-jet-client-default.xml, hazelcast-jet-core/src/main/resources/hazelcast-jet-config-0.6.xsd, hazelcast-jet-core/src/main/resources/hazelcast-jet-member-default.xml, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/config/XmlConfigTest.java, hazelcast-jet-core/src/test/resources/hazelcast-jet-member-test.xml, hazelcast-jet-distribution/src/main/resources/bin/cluster.sh, hazelcast-jet-spring/pom.xml, hazelcast-jet-spring/src/main/java/com/hazelcast/jet/spring/JetClientBeanDefinitionParser.java, hazelcast-jet-spring/src/main/java/com/hazelcast/jet/spring/JetHazelcastBeanDefinitionParser.java, hazelcast-jet-spring/src/main/java/com/hazelcast/jet/spring/JetInstanceBeanDefinitionParser.java, hazelcast-jet-spring/src/main/java/com/hazelcast/jet/spring/JetNamespaceHandler.java, hazelcast-jet-spring/src/main/java/com/hazelcast/jet/spring/package-info.java, hazelcast-jet-spring/src/main/resources/META-INF/spring.handlers, hazelcast-jet-spring/src/main/resources/META-INF/spring.schemas, hazelcast-jet-spring/src/main/resources/hazelcast-jet-spring-0.6.xsd, hazelcast-jet-spring/src/test/java/com/hazelcast/jet/spring/TestApplicationContext.java, hazelcast-jet-spring/src/test/resources/com/hazelcast/jet/spring/application-context-jet.xml, pom.xml
- Add `hazelcast-jet-spring` module which extends and shades `hazelcast-spring` module. 
- Add some checks for programmatic and declarative configurations. 
fixes https://github.com/hazelcast/hazelcast-jet/issues/740
fixes https://github.com/hazelcast/hazelcast-jet/issues/734
depends on:
- https://github.com/hazelcast/hazelcast/pull/12448
- https://github.com/hazelcast/hazelcast/pull/12463
- https://github.com/hazelcast/hazelcast/pull/12428
=> Add hazelcast jet spring module

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/PeekWrappedP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/StreamKafkaP.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/impl/connector/kafka/KafkaPartitionAssignerTest.java
Also rename all instances of `globalParallelism` to `totalParallelism`.
=> Fix totalParallelism passing in PeekWrappedP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Watermarks.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/WatermarkCoalescer_IntegrationTest.java
When processing DONE_ITEM we can generate a WM. The CIES.drainTo added
the WM to inbox, returned MADE_PROGRESS result and a subsequent call to
CIES.isDone() returned `true`. This confused the algorithm.
We fix it by returning DONE result in this situation and by fixing
ProcessorTasklet to handle this situation.
=> Fix situation DONE_ITEM generated a WM

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java
We need a separate mapping vertex and can't use readMapP's projectionFn: the projection will cause key/value deserialization on partition thread, which doesn't have job's class loader. If the key/value uses a custom object, it will fail. For example, StreamKafkaP uses TopicPartition as the key or a custom processor can use custom key.
=> Fix ClassNotFoundException when restoring snapshot

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ReceiverTasklet.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ReceiverTaskletSendLimitTest.java
We gradually expand and shrink rwin based on the amount of data we've processed during the flow control period. This works well if the stream of data is regular. If it is burst-and-lull (i.e. a burst of data and then nothing for a while), then during the lull the rwin shrinks to 1. When the burst occurs, we apply a lot of backpressure unnecessarily.
This fix works around the problem by not shrinking the rwin if there are no items waiting in the inbox. The `call` method processes data from inbox. During a lull, the inbox is normally empty - we avoid shrinking the rwin in this situation. When inbox is not-empty, it means that we are actively processing data and shrinking/expanding works as before. Expansion of the rwin is unaffected by this change.
Fixex #785
=> Don't shrink RWIN during lulls

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamFilesP.java
Previous behavior wasn't wrong, it was unnecessary.
Fixes #796
=> [MERGE TO 0.6.1] Don't call close eagerly in file sources

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobClassLoaderFactory.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/JetClassLoader.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/JobConfigTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/AbstractDeploymentTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/LoadResource.java
Also fix `JetClassLoader`: `getResourceAsStream` should delegate to parent
first. Done by removing the method, superclass implementation does it by
using `findResource`
=> [BACKPORT] Add custom class loader support (#770)

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StageWithGroupingImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StageWithGrouping.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java
=> Fix for output type of aggregate operations with map to output function

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Edge.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ExplodeSnapshotP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/SnapshotRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/InboundEdgeStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/SnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/StoreSnapshotTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetInitDataSerializerHook.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/VertexDef.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncMapWriter.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriter.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/MockInboundStream.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/StoreSnapshotTaskletTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncMapWriterTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImplTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/MockAsyncSnapshotWriter.java
Store the snapshot in 128kB chunks, not as individual entries. The 
previous implementation suffered from the IMap overhead of about 168 
bytes per entry so the main advantage is reduced heap usage. It also 
gives about 25% speedup in snapshot duration and reduces event latency 
hiccup while snapshot is taken.
=> [BACKPORT] Optimize snapshot storage (#822)

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Job.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SinkProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteBufferedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/SinkBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteBufferedPTest.java
`Processor.close` can be called even if `Processor.init` wasn't called:
avoid `destroyFn` call if `createFn` wasn't called.
=> Fix SinkBuilder destroy before create, javadoc

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java
Fixes this scenario: the job completes (normaly or abruptly). It deletes
snapshot maps and then it marks CompletionFuture in MasterContext as
done.
In parallel, scheduled snapshot is about to start by calling
`JobCoordinationService.beginSnapshot`. It checks whether the
MasterContext is done. It sees it is not, so it goes to generate
snapshotId by looking at `LATEST_STARTED_SNAPSHOT_ID_KEY`, but it's null
since the map was deleted in parallel. So it starts the snapshot 0.
The `SnapshotOperation` will be rejected on members, but it recreates
the maps, which causes the maps to leak and the test to fail.
The fix reorders operations in `MasterContext.finalizeJob`: it first
completes the future and then goes on to delete maps.
Fixes #865
=> Fix race when snapshot started after job was done

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java
- remove confusing queue count after `/`
- use global processor index in `debugName`
=> Improve WM coalescing logging in CIES

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/SinkBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SinkBuilderTest.java
Also add `preferredLocalParallelism` option to `SinkBuilder`
fixes https://github.com/hazelcast/hazelcast-jet/issues/884
=> Convert argument of SinkBuilder createFn to Processor.Context

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SinkProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SourceProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamJmsP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteJmsP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/JmsSinkBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/JmsSourceBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsIntegrationTest.java
- move factory method to `Sources` and `Sinks` where they are easier to
discover
- `isTopic` is required in constructor, it was easy to forget to call
`.topic()`
- get rid of the most generic methods, builder has every feature they had
- sink can accept `javax.jms.Message` on input, doesn't convert
everything to `TextMessage`
- less code duplication (same non-trivial defaults both in builder and in
processor)
=> Simplify JMS builder APIs

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/TimestampKind.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StageWithGroupingImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/DistinctTransform.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java
It was implementd as `filterUsingContext()`, but that operation doesn't use partitioning.
=> Fix distinct()

hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperationBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperations.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AllOfAggregationBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/DiagnosticProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SinkProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SourceProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/aggregate/AggregateOperation1Impl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/aggregate/AggregateOperation2Impl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/aggregate/AggregateOperation3Impl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/aggregate/AggregateOperationImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamEventJournalP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/AggBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/ComputeStageImplBase.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StageWithGroupingAndWindowImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StageWithGroupingBase.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StageWithGroupingImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStageWithGrouping.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/JmsSinkBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/JmsSourceBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/JoinClause.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/SinkBuilder.java
Sometimes it's hard to figure out which lambda fails to serialize from 
the JVM's error message. This commit adds an early check so that the 
stack trace points directly to the delinquent lambda and its parameter 
name.
=> Proactively check serializability in Pipeline API

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Edge.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/TimestampedEntry.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/TimestampedItem.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StageWithGroupingAndWindow.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StageWithWindow.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/WindowAggregateBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/WindowAggregateBuilder1.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/WindowGroupAggregateBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/WindowGroupAggregateBuilder1.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/Processors_slidingWindowingIntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowP_CoGroupTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowP_FrameCombiningTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowP_failoverTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowP_twoStageSnapshotTest.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/KafkaProcessors.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/KafkaSources.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/impl/StreamKafkaP.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/kafka/impl/StreamKafkaPTest.java
- kafka source requires to give at least one topic (uses `String topic,
String ... moreTopics` method contract). Also better documentation of
offset committing.
- add javadoc warnings about null key, null timestamps or nonsensical
timestamps returned in lambdas
- check for null key returned from edge partitioner key extractor and
print a better error message
- remove the constructor in TimestampedEntry and TimestampedItem with
(with `ignored` parameter). It was hard to figure out what this is for.
Replaced with a static method.
=> Usability improvements

hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/AvroProcessors.java, hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/AvroSinks.java, hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/AvroSources.java, hazelcast-jet-avro/src/test/java/com/hazelcast/jet/avro/AvroSourceTest.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SinkProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SourceProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamEventJournalP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/ContextFactory.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/FileSinkBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/FileSourceBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadFilesPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesP_integrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesP_readCompleteLineTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamJmsPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteFilePTest.java, hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/hadoop/HdfsSources.java
Also add shared file system support to StreamFilesP
[Breaking Change for Public API]
- Adds a new boolean parameter `sharedFileSystem` to `SourceProcessors.streamFilesP`
- Changes `Sources.files` and `Sources.fileWatcher` to `Sources.filesBuilder`
- Changes `Sinks.files` to `Sinks.filesBuilder`
=> Introduce file source/sink builders

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java
Fixes #918 
By looking at the test output it seems to me that we've lost the JobRecord. There are 5 members in the test, we terminate 4 of them forcefully. This is only a hypothesis, i couldn't reproduce it locally. I tried to terminate instances at once in parallel to increase the chance of losing a partition, because one `terminate` call takes about 50ms, which might be enough for the backup to pick up and replicate.
```
12:50:01,500 ERROR || - [StartExecutionOperation] hz._hzInstance_69_jet.generic-operation.thread-3 - [127.0.0.1]:5067 [jet] [0.7-SNAPSHOT] Job with id d454-ac6b-9a41-212f not found
com.hazelcast.jet.core.JobNotFoundException: Job with id d454-ac6b-9a41-212f not found
at com.hazelcast.jet.impl.JobCoordinationService.getJobConfig(JobCoordinationService.java:415)
at …
```
=> Fix quorum protection test failure

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestInbox.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ProcessorsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadIListPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/SlidingWindowP_stage1Test.java
Previously we tested only inbox with one item. This commit adds two
testing scenarios: inbox with 1 item and inbox with all items. For
multiple instreams it's all items from one ordinal and the all from
another ordinal. After this change, more cooperative emission problems
are caught.
Fixes #887, where there is an example of a previously uncaught problem.
=> Improve TestSupport

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/FunctionAdapter.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/PeekWrappedP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/PeekingWrapperTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowGroupAggregateTest.java
Also:
- log eventTime in `peek` for streams with timestamps
=>  Fix aggregation of window aggregation results

hazelcast-jet-core/src/main/java/com/hazelcast/jet/JetInstance.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJetInstance.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ClientJobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetClientInstanceImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetInstanceImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRecord.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobResult.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/LiveOperationRegistry.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/SnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/AsyncJobOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/CompleteExecutionOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/InitExecutionOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/JoinSubmittedJobOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/SnapshotOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/StartExecutionOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/ConcurrentMemoizingSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/LiveOperationRegistryTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Snapshots.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Watermarks.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/SnapshotContextTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/StoreSnapshotTaskletTest.java
The following is used in log messages:
`AbstractJobProxy`: logs on the submitting client or member
```
xxxx-xxxx-xxxx-xxxx (name ??)   - if config not loaded yet
xxxx-xxxx-xxxx-xxxx (name '')   - if loaded, but name null
xxxx-xxxx-xxxx-xxxx (name 'abc')
```
`MasterContext`: logs on coordinator member. Name is always known.
```
job 'abc', execution xxx-xxx-xxx-xxx                - if name set
job 'xxx-xxx-xxx-xxx', execution xxx-xxx-xxx-xxx    - if name not set
```
`ExecutionContext`: on each member, name not known for a short while
initially
```
job 'abc', execution xxx-xxx-xxx-xxx              - if name set
job xxx-xxx-xxx-xxx, execution xxx-xxx-xxx-xxx    - if name not set
```
Initial log, printed on each member on INFO level to give association for
jobId, jobName and executionId:
``` …
```
=> Prefer using job name in logs

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetClientConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetConfig.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/JetInstanceTest.java
Currently when you create a new `ClientConfig` object it doesn't have the correct group name and password to connect to the Jet cluster. This class is a convenience for overriding the default group name and password when creating a client config to connect to a Jet cluster.
=> Add JetClientConfig which uses the correct group name and password

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetClientInstanceImpl.java
Exposed HazelcastClient on JetClientInstanceImpl  
- to access connection manager so that connection listeners can be added 
- to fetch connected server version
=> Add getter for HazelcastClient on JetClientInstanceImpl

hazelcast-jet-spring/pom.xml
hazelcast-jet-spring had dependency on `hazelcast-jet-core` and `hazelcast-spring` which in turn introduced dependencies on hazelcast.jar causing a conflict of versions when spring-boot was used. 
Fixes #977
=> Fix for dependencies of hazelcast-jet-spring

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncMapWriter.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/CancellationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ManualRestartTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamEventJournalPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesP_integrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamSocketPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteBufferedPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncMapWriterTest.java
The writer uses `PartitionIteratingOperation`, which can partly fail:
some partitions succeed, some fail. The failed partitions are retried.
The retrial is executed from an `ExecutionCallback`, which is called
once for each member. Both attempts use `invokeOnCluster`, which used a
`doneLatch` to track callbacks from members and when it got to 0, it
completed the future. The problem was if in the first attempt, two
members failed. It will cause two retry calls to `invokeOnCluster`. But
the first completed retry call completed the future before the second
one finishes, causing the test to (correctly) fail.
The solution is to use one `doneLatch` for both the initial attempt and
all retries. `invokeOnCluster` only increments and decrements it. If a
partition is retried, it is first …
=> Fix race in AsyncMapWriter

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetSplitBrainTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java
The test failed if the job upscaled (after default 10 second delay)
before the 5 second wait condition elapsed. Now, we wait for it to
upscale.
Fixes #990
=> Fix test failure, job can manage to upscale

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ScaleUpTest.java
Contains:
- a snapshot could be begun if job was not running (due to upscaling...)
- if we fail to restart to scale-up, we'll schedule a retry
- we called `handleTermination` even if job was not running
The effect of the above was minor, either the 
`CompleteExecutionOperation` or `SnapshotOperation` were rejected by the 
target, which polluted the logs, but no real harm was done.
=> Elasticity fixes

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/SnapshotOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ManualRestartTest.java
The `future` from the `invoke` method was added to the map at a time the
callback could already be executed. This will cause that some of the
responses will be missing when handling.
Fixes #1029: from the logs we see that only one of the member failed and
the error response from the failing member was indeed sent, but the
terminal snapshot was marked as successful despite of that. This
suggests that the response was lost, even though it never reproduced
locally. The window for race is quite small: the thread, that should
execute as the second one, has lot more work to do than the other one.
=> Fix race when collecting responses from members

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/JobNotFoundException.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ClientJobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/Job_StaleInstanceTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/JobRepositoryTest.java
If JobRecord exists, we'll eventually learn of it, but otherwise there's
no point in retrying.
Also includes test for calling methods on stale Job instance.
=> Don't throw HzRetryableExc from terminateJob

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetInstanceImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java
By default, imdg adds its own shutdown hook, which calls either shutdown or terminate according to the shutdown-hook-policy. We've introduced graceful shutdown of jobs but it is only called if explicitly called `JetInstance.shutdown()`. If the processor is killed externally jobs are not shutdown gracefully.
With this PR, we disable the imdg shutdown hook and add our own hook. In the hook, if the policy is graceful then the jobs and underlying imdg instance are shutdown gracefully otherwise we terminate the imdg instance without shutting down the jobs.
=> Add jet shutdown hook, disable imdg one

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/LiveOperationRegistry.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/JetMetricsService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/management/ConcurrentArrayRingbuffer.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/management/JetReadMetricsMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/management/ReadMetricsOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/AsyncJobOperation.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/metrics/ReadMetricsTest.java
ReadMetricsOperation was using wait/notify mechanism but it is not thread-safe, it is designed for partition-thread operations. With the change, `readMetrics` method returns a future which is used to return the response once a new metric arrived.
=> Convert ReadMetricsOperation from blocking to async operation

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/TaskletExecutionServiceTest.java
It also "fixes" the race with work-stealing during graceful shutdown.
=> Remove work-stealing and improve work balance

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/NotifyMemberShutdownOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImpl.java
The JobCoordinationService called `shouldStartJobs` to check whether to
start snapshots. It contained the condition that it doesn't start when
member is shutting down or migration is ongoing. These two conditions do
not apply to snapshots, however. For example, when a terminal snapshot
is started and another snapshot was ongoing, it was postponed. The next
snapshot was supposed to be terminal, but it couldn't start, because
member is shutting down...
=> Fix terminal snapshot when one is in progress

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java
since we complete the jobs on `JetService.reset`  asynchronously, we need to check eventually
fixes https://github.com/hazelcast/hazelcast-jet/issues/1097
=> Convert assertEquals to assertEventually

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionRecord.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/StoreSnapshotTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetInitDataSerializerHook.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriter.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImpl.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/init/JetInitDataSerializerHookTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImplTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/MockAsyncSnapshotWriter.java
The number of bytes, chunks and keys for snapshot was always reported as
0. Also improves JobExecutionRecord to see if there's an ongoing snapshot.
=> Fix snapshot stats reporting

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SessionWindowP.java
Materialization of `distinctKeys` isn't needed (it even materialized a
Set first inside the `distinct()` stage and then copied it to a List).
Most of the time, each key has one Window, and if not, we'll call
`closeWindows` again and it will find out that there's no window to
close.
=> Don't materialize `distinctKeys` in SessionWindowP

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/GracefulShutdownTest.java
The removed part was racy: it could happen that job status was RUNNING
and the shutdown() call didn't yet return.
Fixes #1118
=> Fix when_shutDownInProgressFromInit_then_restarts

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/JetTestInstanceFactory.java
JobCoordinationService scans for jobs that aren't running and runs them. Currently the scanning starts in the middle of the Hazelcast service initialization phase, so a job may encounter a partially initialized Hazelcast instance.
=> Start job scan after HZ init is done

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java
It is an error to enable Hot Restart on a data structure when 
the feature of Hot Restart Persistence is disabled.
=> Align Hot Restart enablement with global setting

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetInstanceImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetNodeContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetNodeExtension.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/NodeExtensionCommon.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/exception/EnteringPassiveClusterStateException.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetInitDataSerializerHook.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobConfigOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobIdsByNameOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobIdsOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobStatusOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobSubmissionTimeOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobSummaryListOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/NotifyMemberShutdownOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/PrepareForPassiveClusterOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/ExceptionUtil.java, hazelcast-jet-core/src/main/resources/META-INF/services/com.hazelcast.instance.NodeExtension, hazelcast-jet-core/src/test/java/com/hazelcast/jet/JetTestInstanceFactory.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ClusterStateChangeTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java
In order to gracefully restart a Hazelcast cluster, it must first enter the PASSIVE state. Jet must prepare to enter this state by terminating all the running jobs.
This PR introduces the ability of Jet to prepare for the PASSIVE cluster state.
=> Cluster Restart support: graceful cluster state change to PASSIVE

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/WatermarkEmissionPolicy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/Planner.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/Processors_slidingWindowingIntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/WatermarkEmissionPolicyTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/InsertWatermarksPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/InsertWatermarksP_IntegrationTest.java
We'll include the maxGap in the gcd calculation. This might be slightly
less efficient with frame sizes that are not multiples of 1000 (1
second), but this is not common and it's not that much worse.
=> Simplify watermark max gap

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Job.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java
We changed the `jobStatus` to SUSPENDED and then we proceeded to copy
the validation key to the cache. In the meantime, the snapshot could
have been deleted.
=> Fix possible race with exportSnapshot

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/XmlJetConfigBuilder.java, hazelcast-jet-spring/src/main/java/com/hazelcast/jet/spring/JetInstanceBeanDefinitionParser.java
Code related to W3C DOM processing has been extracted from the XML
config builder classes in IMDG that, which led to compilation errors in Jet.
This commit fixes these errors by using the extracted methods from the
new DomConfigHelper class.
Depends on https://github.com/hazelcast/hazelcast/pull/14368
=> Fix compilation error in config

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ManualRestartTest.java
The `JobExecutionRecord` didn't yet exist and was `null`. Resolve by waiting until the job is RUNNING.
Fixes #1029
=> Fix ManualRestartTest failure

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/HazelcastRemoteConnectorTest.java
It seems to be a problem in IMDG code.
Fixes #1194
=> Work around a deadlock in Hazelcast.shutdownAll

hazelcast-jet-all/src/main/java/com/hazelcast/jet/server/JetBootstrap.java
=> Override initialSnapshotName and jobName only if they are passed as an argument to the cli

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorMetaSupplierContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorSupplierContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/Contexts.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlanBuilder.java
Method `processingGuarantee()` was available only in `Processor.Context`,
but this information is available up in `ProcessorMetaSupplier.Context`,
it should be there.
=> Move processingGuarantee up from Processor.Context

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingContextOrderedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingContextUnorderedP.java
This scenario was possible:
- `tryProcessWatermark` was called. `watermarkCounts` was empty, so it
tried to forward the watermark right away. `tryEmit` failed, so
`tryProcessWatermark` it returned `false`.
- `tryProcessWatermark` was called again. This time, the `lastReceivedWm`
was equal to the watermark, so it returned `true` without trying to
finish the watermark. This is the root of the problem.
- then `tryProcess()` was called, but `tryFlushQueue` did nothing
(because there are no in-flight items) and `tryProcess()` returned
`false` because there's an unfinished item in the outbox. The job got
stuck calling `tryProcess()` forever.
The fix is to ensure we correctly retry in `tryProcessWatermark`.
Fixes #1254
=> Fix cooperative emission in unordered-async-mapP

pom.xml, spotbugs/spotbugs-exclude.xml
1. Spotbugs exclusion due
https://github.com/spotbugs/spotbugs/issues/756
2. Hazelcast Client Protocol upgrade to include
https://github.com/hazelcast/hazelcast-client-protocol/pull/160
3. javadoc source version set to ${jdk.version}.
See https://bugs.openjdk.java.net/browse/JDK-8212233
=> Hazelcast Jet compiles with OpenJDK 11

hazelcast-jet-core/pom.xml
for OpenJDK 11 compatibility
See https://github.com/jqno/equalsverifier/issues/197
=> Equals lib upgrade

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/XmlJetConfigBuilder.java
- `AbstractConfigBuilder` renamed to `AbstractXmlConfigBuilder`
- `getProperties()` pulled up by one level
Depends on https://github.com/hazelcast/hazelcast/pull/14415
=> Update XmlJetConfigBuilder with changes made in IMDG

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Edge.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadWithPartitionIteratorP_MigrationDetectionTest.java
In the test we submitted the job and immediately proceeded to add a
member to cause migration, there was no synchronization. It could happen
that the member was added before the job started, which caused the test
to fail.
This commit also uses random group name for the remote members so that
they don't inadvertently form a cluster with test running in another JVM
on the same network.
Fixes #1108
=> Fix migration taking place before test job starts

pom.xml
To resolve: `java.lang.NumberFormatException` while running tests.
Example of the exception:
```
Caused by: java.lang.NumberFormatException: For input string: " output=[]](com.hazelcast.jet.impl.connector.StreamSocketPTest)"
at java.lang.NumberFormatException.forInputString (NumberFormatException.java:65)
at java.lang.Integer.parseInt (Integer.java:569)
at java.lang.Integer.parseInt (Integer.java:615)
at org.apache.maven.plugin.surefire.runorder.RunEntryStatistics.fromString (RunEntryStatistics.java:82)
at org.apache.maven.plugin.surefire.runorder.RunEntryStatisticsMap.fromReader (RunEntryStatisticsMap.java:96)
at org.apache.maven.plugin.surefire.runorder.RunEntryStatisticsMap.fromFile (RunEntryStatisticsMap.java:69)
at org.apache.maven.surefire.util.DefaultRunOrderCalculator.orderTestClas …
```
=> Bump-up the surefire plugin version

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/PipelineStreamTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowAggregateTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowGroupAggregateTest.java
Use a bounded streaming source so we can join() the job and 
deterministically assert the output.
=> Simplify unbounded stream tests

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestSupport.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MigrationWatcher.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamEventJournalPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamEventJournalP_WmCoalescingTest.java
Removes the `disableRunUntilCompleted()` method. The method was meant to
test streaming sources, but the timeout needs to be pretty high to
account for test environment hiccups which makes the test slow even in
cases when the output is produced very shortly after run. This commit
introduces `runUntilOutputMatches()` which runs `complete()` until the
output matches and for little extra time to check that there's no more
output.
Fixes #1261
=> Add run-until-output-matches mode to TestSupport

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetClientInstanceImpl.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/JetClientInstanceImplTest.java
Introduced getDistributedObjects method in the JetClientInstanceImpl which only returns list of objects instead of actual/usable proxies
Workaround for https://github.com/hazelcast/hazelcast/issues/14571
=> Introduced getDistributedObjects on JetClientInstanceImpl

hazelcast-jet-all/src/main/java/com/hazelcast/jet/server/JetCommandLine.java
If no arguments were given to the submitted jar, an array with length
one, containing an empty string was passed to the `main` method, which
could confuse it.
=> Allow zero arguments

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamSourceStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamSourceStageTestBase.java
The issue was that the kafka source total parallelism was 4, but there
was only 1 partition in the test. So 3 processors were idle. Most of the
time, the idle processors immediately emitted IDLE_MESSAGE. But in the
failed run, IDLE_MESSAGE was emitted after the active processor emitted
the items and watermarks. This caused that wm(1) was suppressed at the
coalescer and only wm(2) was forwarded after the idle message was
received.
It's resolved by using total parallelism=1 everywhere, the test isn't
influenced by the parallelism.
Fixes #1294
=> Fix StreamKafkaP_TimestampModesTest failure

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetClientConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetConfig.java, hazelcast-jet-core/src/main/resources/hazelcast-jet-client-default.xml, hazelcast-jet-core/src/main/resources/hazelcast-jet-member-default.xml
Fixes #734 
After https://github.com/hazelcast/hazelcast/pull/14603 is merged, the password warning should also not be printed. Password option will be kept only in the enterprise version as it is only used there.
=> Remove deprecated password from Jet

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetExportSnapshotMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetGetJobIdsByNameMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetGetJobIdsMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetGetJobStatusMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetGetJobSubmissionTimeMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetGetJobSummaryListMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetJoinSubmittedJobMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetResumeJobMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetSubmitJobMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetTerminateJobMessageTask.java
Threads that handles client tasks are refactored on the server side.
Generic executor was opening `coreSize * 20` threads when needed
before. This was not desirable. We have moved the blocking ones to
a second new executor with high max thread count and reduced the number
of threads that generic client executor opens to `coreSize`
This pr marks JetMessageTasks waiting for remote response as
BlockingMessageTask. Doing so, in terms of Jet perspective the old
behaviour is preserved.
related to https://github.com/hazelcast/hazelcast/issues/4641
=> Moves tasks waiting for remote response

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/JetGroupProperty.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/TaskletExecutionServiceTest.java
Also increases the default minimum from 1µs to 25µs - the real minimum
on linux actually was 50µs and 15000µs on Windows.
=> Make minimum idle time configurable

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/BatchStageWithKeyImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/ComputeStageImplBase.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StreamStageWithKeyImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStageWithKey.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStageWithKey.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GroupAggregateBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StageWithKeyAndWindow.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StageWithWindow.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StreamStageWithKey.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchAggregateTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamStageTest.java
Also remove the `mapToOutputFn` parameter from batch `aggregateN` methods.
Removed from `BatchStage`:
- `aggregate2(aggrOp0, stage1, aggrOp1, mapToOutputFn)`
- `aggregate3(aggrOp0, stage1, aggrOp1, stage2, aggrOp2, mapToOutputFn)`
Removed from `BatchStageWithKey`:
- `aggregate(aggrOp, mapToOutputFn)`
- `aggregate2(stage1, aggrOp, mapToOutputFn)`
- `aggregate2(aggrOp0, stage1, aggrOp1, mapToOutputFn)`
- `aggregate3(stage1, stage2, aggrOp, mapToOutputFn)`
- `aggregate3(aggrOp0, stage1, aggrOp1, stage2, aggrOp2, mapToOutputFn)`
Removed `GroupAggregateBuilder.build(mapToOutputFn)`
=> Add sample snippets to Javadoc

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Job.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetGetJobIdsByNameMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetGetJobIdsMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetGetJobStatusMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetGetJobSubmissionTimeMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetGetJobSummaryListMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetTerminateJobMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/management/ReadMetricsOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/AsyncOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobIdsByNameOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobIdsOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobStatusOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobSubmissionTimeOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobSummaryListOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/JoinSubmittedJobOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/NotifyMemberShutdownOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/PrepareForPassiveClusterOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/SnapshotOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/StartExecutionOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/SubmitJobOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/TerminateJobOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ParallelJobSubmissionTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ParallelStressTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java
A deadlock is possible when calling methods that execute operations
backed by `InvokeOnPartitions` from an async thread. This is an issue of
IMDG and it will probably be checked and disallowed in future version
(see hazelcast/hazelcast#14734 for description of the deadlock).
In case of Jet, we call `IMap.clear()` and `IMap.removeAll()` as part of
handling of operation response using `ExecutionCallback`, which is
normally executed on an async thread, which could cause the deadlock
under load.
The fix in this commit is to offload all such handling to own thread, we
use the cached thread pool in `JobCoordinationService`.
Fixes #1339
=> Offload blocking tasks from async thread

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/HashJoinCollectP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/HashJoinP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/package-info.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/HashJoinPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java
As in the title, this PR add Hash Join support for non-distinct keys #1326
Note: it considers only non-tag way. I have to digg more into how Tags works, but this issue is a blocker for my team, that's why I create PR before second part is implemented. It will be implemented in a follow-up
=> Hash Join support for non-distinct keys #1326

hazelcast-jet-distribution/pom.xml
forward-port of https://github.com/hazelcast/hazelcast-jet/pull/1367
=> Add workaround for including javadoc from core module into distribution

hazelcast-jet-core/src/test/java/com/hazelcast/jet/MulticastDiscoveryTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/benchmark/BackpressureTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/benchmark/WordCountTest.java, pom.xml
It fixes or adjusts following:
* categories `NightlyTest` and `SlowTest` were not executed in `nightly` profile
* run only categories `NightlyTest` and `SlowTest` in nightly profile (i.e. not run common tests in this profile)
* `test-coverage` used for Sonar should include also `NightlyTest` and `SlowTest` categories since they are also related to test coverage
* `redirectTestOutputToFile` is moved to property to have it configured automatically for all test-related profiles
* removed `failIfNoTests=false` from surefire plugin configuration - it can cause that no tests were run and it looks like everything finished ok. In case when anybody needs it for locally testing etc., then `-DfailIfNoTests=false` can be used in maven command 
* moved tests `MulticastDiscoveryTest`, …
=> Fixed nightly profile

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/ConfigProvider.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/XmlJetClientConfigLocator.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/XmlJetConfigLocator.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/XmlJetMemberConfigLocator.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/YamlJetClientConfigLocator.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/YamlJetConfigBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/YamlJetConfigLocator.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/YamlJetMemberConfigLocator.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/AbstractJetConfigLoadFromFileSystemOrClasspathTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/AbstractJetConfigWithSystemPropertyTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/JetConfigIllegalArgumentsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/XmlConfigTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/XmlJetConfigImportVariableReplacementTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/XmlJetConfigLoadFromFileSystemOrClasspathTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/XmlJetConfigWithSystemPropertyTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/YamlJetConfigImportVariableReplacementTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/YamlJetConfigLoadFromFileSystemOrClasspathTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/YamlJetConfigWithSystemPropertyTest.java, hazelcast-jet-core/src/test/resources/hazelcast-jet-foo.bar, hazelcast-jet-core/src/test/resources/hazelcast-jet-test.yaml
Changed behavior to treat an XML configuration file which has a non .xml file extension as XML files to satisfy backwards compatibility.
YAML configuration has a stricter requirement on file extensions
which only accepts .yaml or .yml extension.
Fixes #1380
Depends on https://github.com/hazelcast/hazelcast/pull/14945
=> Fix regression in declarative config file resolution

pom.xml
`argLine` property was not correctly passed to jacoco plugin which caused that Sonar build was not able to show code coverage.
=> Fixed test-coverage profile

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/SenderTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/SnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/StoreSnapshotTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/ExceptionUtil.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/OperationLossTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ProcessorTaskletTest_Snapshots.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/StoreSnapshotTaskletTest.java
Any operation or response to operation can be lost due to network reconnection. If it happens, we'll get an `OperationTimeoutException`. That operation might or might not have been executed on the remote member. This commit fixes issues around that for Jet operations:
- if we get it for `InitExecutionOp` or `StartExecutionOp`, treat it as a restartable exception and restart the job (implemented in `ExceptionUtil.isTopologyException`)
- for `CompleteExecutionOp` the operation is simply retried, assuming the operation is idempotent. I also added logging of other errors because they were ignored.
- for `TerminateExecutionOp` the termination is retried. The operation was already idempotent so it was fairly easy. Again, logging of other errors was added.
- for non-terminal `SnapshotOperation` …
=> Fix issues related to operation packet loss

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java
For non-distributed sources that use `forceTotalParallelismOne`, batch
processors are created on inactive members. If there's no distributed
edge in the DAG, the execution on those members will complete
immediately, while the execution on the active members tries to do
snapshot.
This PR changes the edge case behavior that if the execution is
completed, we immediately respond to the SnapshotOperation instead of
throwing a CancellationException.
=> Fix snapshot creation after execution is done

pom.xml
This PR cleans root `pom.xml` to allow utilizing Maven artifact proxies.
The same approach is used in the Hazelcast IMDG.
=> Clean-up Maven repositories in pom.xml

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/resources/jet-runtime.properties
It can be that different version of Hazelcast is included as a dependency due to misconfiguration. This can cause unexpected behaviour or confusing errors. Jet should fail fast in this scenario and refuse to start with a clear exception message.
Fixes #1405
=> Add check for matching expected Hazelcast version with actual version in classpath

hazelcast-jet-distribution/src/main/resources/bin/jet-start.sh
The flag has no meaning on modern JVM - tiered combination is enabled
by default.
Also it prevents Jet to start on ARMv6 where only the client compiler
is available :)
=> Remove -server flag from start script

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/SnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/StoreSnapshotTasklet.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/OperationLossTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TestProcessors.java
The previous fix in #1377 wasn't sufficient, it only worked when there
was no distributed edge in the DAG. A processor after a distributed edge
got stuck forever waiting for the barrier from a member that did not
receive the SnapshotOp.
The fix here is to retry the SnapshotOperation. If the operation was
lost, the snapshot will eventually succeed. If the response was lost,
even though the snapshot operation is not idempotent and will fail when
retried with the same snapshotId, at least the job won't get stuck.
Snapshot failure is then ignored.
Note that the test does not test when a response to an operation is lost,
there is currently no test harness to simulate that.
=> Fix loss of SnapshotOperation

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java
Fixes #1436.
It fixes the execution duration when the `executionStartTime` was not
initialized and was 0. On Linux `System.nanoTime` returns 0 at about OS
boot, which explains the 8 hours of runtime. The value was printed
because we've set the `executionStartTime` deeply in `tryStartJob`, but
this time the job was finalized before `tryStartJob` was called. Also
moves the initialization of `executionStartTime` at the very beginning
of `tryStartJob` because other exceptions could lead to garbabe duration
logged.
The commit does not fix the "execution 0000-0000-0000-0000" - it means
that no execution began yet. It might be surprising, but it's at least
not a garbage value.
=> Always initialize executionStartTime

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/JetClassLoader.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/JetClassLoaderTest.java
During ProcessorSupplier.init(), the ThreadContextCL
was not set to the correct class loader. Besides this,
it’s still possible that the context class loader
can leak to other threads (see https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8172726) because it’s inherited during thread creation. In the case that 
the class loader is still referenced by some thread
we should only print a warning instead of throwing an exception
=>  Fix issues in JetClassLoader

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/JetClassLoader.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/JetClassLoaderTest.java
During ProcessorSupplier.init(), the ThreadContextCL
was not set to the correct class loader. Besides this,
it’s still possible that the context class loader
can leak to other threads (see https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8172726) because it’s inherited during thread creation. In the case that 
the class loader is still referenced by some thread
we should only print a warning instead of throwing an exception
=> Fix issues in JetClassLoader

hazelcast-jet-core/src/test/java/com/hazelcast/jet/TestInClusterSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SinksTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SourceBuilderTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SourcesTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/Sources_withEventJournalTest.java
Remove ParallelTest: the logs were mingled and we were not able to
investigate issues. Also ensure that the shared cluster is cleaned up of
all non-terminated jobs and non-destroyed distributed objects.
Related to #1454
=> Drop ParallelTest, clean up cluster after tests

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamSocketPTest.java
The test fails when run twice with maven due to newline in parameters. See:
https://issues.apache.org/jira/browse/SUREFIRE-1662
=> Add workaround for StreamSocketPTest

hazelcast-jet-reference-manual/src/main/asciidoc/index.adoc, hazelcast-jet-reference-manual/src/main/asciidoc/stylesheets/hazelcast.css
This PR addresses #1462 and also introduces a clearer document flow for mobile devices. The built manual out of these improvements can be seen and tested at https://docs.hazelcast.org/docs/Test/jetrefman/
=> Improvements for source code blocks and page width.

hazelcast-jet-reference-manual/src/main/asciidoc/pipeline-api/pipeline-api.adoc
In section `4.15. Developing and testing your pipeline` there is incorrect link https://docs.hazelcast.org/docs/jet/latest-dev/manual/#appendix. It is fixed to use https://docs.hazelcast.org/docs/jet/latest-dev/manual/#jet-version-compatibility.
=> Doc: Fixed link from Testing Pipeline to Jet Version Compatibility

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetJoinSubmittedJobMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/JetSubmitJobMessageTask.java
* Submit and join tasks are now performed on coordinator thread so there
is no need to use a blocking message task
* When uploading job resources, getting the resource map proxy requires a 
blocking message and creates an unnecessary roundtrip.
=> Avoid using blocking client threads

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java
This causes them to be created even if they won’t be needed by the job
=> Do not attempt to clear snapshots maps on job start

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SinksTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SourcesTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/Sources_withEventJournalTest.java
I've noticed that `Sources_withEventJournalTest` was running the actual test cases in a reasonable amount of time, but then, at the end was stuck in `Hazelcast.shutdownAll();` for ages. While we should probably investigate the root reason for this, maybe we could switch such test usages to call `HazelcastInstanceFactory.terminateAll();` instead. Should we fine for tests. Pls. correct me if I'm wrong.
=> Use ungraceful instance termination in tests

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ConveyorCollector.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/OutboundCollector.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java
Previously partitions were calculated and assigned for every edge whether it was
partitioned or not and this caused unnecessary overhead during job initialisation.
=> Simplify creation of queues when edge is not partitioned

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/JetMetricsService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/init/VertexDef_HigherPrioritySourceTest.java
Registering metrics for running very small jobs incurs additional overhead without
bringing much value. It should be made optional
=> Make enabling job metrics optional

hazelcast-jet-core/src/test/java/com/hazelcast/jet/job/JobSubmissionSlownessRegressionTest.java, pom.xml
This test case is not part of default profile (i.e. tests which are executed by PR builder). You can execute it locally by `mvn test -Pnightly -Dtest=JobSubmissionSlownessRegressionTest`.
=> Regression test for job submission slowness

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/JetProperties.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobResult.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycle_RestartableExceptionTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/JobRepositoryTest.java
During job cleanup all the job results were queried, causing deserialization of all completed job metrics which causes excessive GC. Fixes #1540
=> Move JobMetrics to own map to avoid querying during job cleanup

hazelcast-jet-all/src/main/java/com/hazelcast/jet/server/StartServer.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/Job.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/JetProperties.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/TestInClusterSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_BatchTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_MiscTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_NonSharedClusterTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_StreamTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_StressTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/PipelineTestSupport.java
New option `JobConfig.setStoreMetricsAfterJobCompletion` 
can be used to control whether metrics are saved upon
job completion.
=> Disable persistence of completed job metrics by default

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycle_RestartableExceptionTest.java
If a job that failed with RestartableException was cancelled, the
cancellation might be ignored and job restarted anyway.
Fixes #1470
=> Fix cancellation race with RestartableException

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/OperationLossTest.java
`Processor.init()` is called as a part of Execute phase. So the job
might be running and init might not yet be called -> change the assert
to assertEventually.
Fixes #1491
=> Fix OperationLossTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/TransformStatefulP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/TransformStatefulPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamStageTest.java
The test was unstable because when processor has total parallelism > 1,
the watermarks are non-deterministic. They can be postponed if waiting
for another processor. The unit test covered the TTL handling enough.
I also added a test for the interrupted cleanup logic in
`tryProcessWatermarks` and more, the unit test coverage is 100% now.
Fixes #1560
=> Drop unstable mapStateful_keyedWithTtl, add coverage

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/PartitionedProcessorTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/ProcessorTransform.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/ProcessorTransformParallelismTest.java
Users still have the ability to override the default
=> Default to a lower parallelism(2) in case of non-cooperative context factory

hazelcast-jet-core/src/test/java/com/hazelcast/jet/SimpleTestInClusterSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/OperationLossTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SlowSourceYieldTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/HazelcastConnectorTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/init/VertexDef_HigherPrioritySourceTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingContextP_IntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ImdgUtilTest.java
This class is like TestInClusterSupport, but more flexible: allows
configuring member count, instance config, isn't parametrized, has
optional client.
=> Add SimpleTestInClusterSupport

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_MiscTest.java
If the client joined the job before it completed, a real exception was
in the causes. However, if it joined after the job completed, we
reconstitute the exception from `JobResult`, which only stores the
failure text. Therefore not the original exception is throws, but only
"JetException: failureText".
Fixes #1592
=> Fix exception asserting in causes

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamSourceStageTestBase.java
In StreamSourceStageTestBase the WatermarkCollector
would only process one wm and then perpetually return false
since it was trying to emit it. Tests were only passing because
each watermarks was going to a different processor.
Fixes #1591
=> Fix intermittent test failure in StreamSourceStageTest

hazelcast-jet-core/src/test/java/com/hazelcast/jet/job/JobSubmissionSlownessRegressionTest.java
The test is using a lot of memory when there is a lot of cores:
Each job creates core-count * core-count amount of queues, and each queue
has 1024 elements. On jenkins with 72 cores, this causes about 50mb of
memory usage per job, and the test submits 72 jobs at the same time.-
The fix is to set the queue size on edge to 1 as this is not related
to the regression tested by this test.
Fixes #1540
=> Reduce memory usage of JobSubmissionRegressionTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java
Multiple exceptions are translated into a TopologyChangeException (TCE)
in `MasterJobContext.getResult`. Sometimes it's not clear what
exceptions they were. This commit adds them to the message of the TCE.
Fixes #1594
=> Add causes from members to job failed with a TCE

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/JobSummaryTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ExceptionUtilTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/test/AssertionsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/test/TestSourcesTest.java, hazelcast-jet-reference-manual/src/main/java/Testing.java
Fixes #1598
One difference still remains: if a temporary master context is completed
in `JobCoordinatorService.completeMasterContextIfJobAlreadyCompleted()`,
it will have different error.
Also contains refactor of `ExecutionLifecycleTest` to use
`SimpleTestInClusterSupport`: some tests created a second cluster.
The test `when_job_withNoSnapshots_completed_then_noSnapshotMapsLeft`
was outdated.
=> Fix different exception from join if problem is same

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteMapP.java
Currently the limit is higher per processor, which may overload the cluster if the writes are slow. This allows the parallelism of the sink to be controlled in a more fine-grained way.
=> Change max parallel ops limit to 1 per processor for writeMapP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/StartExecutionOperation.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/NonSmartClientTest.java
We checked JobResults first and the master contexts. We could miss a job
that completed in the meantime. Fixed by reversing the order.
Fixes  #1610
=> Fix race in JCS.getJobIds

hazelcast-jet-client-protocol/src/main/java/com/hazelcast/client/impl/protocol/template/JetCodecTemplate.java
We had this failure:
```
com.hazelcast.spi.exception.TargetNotMemberException: Target '[10.0.0.81]:5701' is not a member.
...
at com.hazelcast.jet.impl.ClientJobProxy.getStatus(ClientJobProxy.java:72)
at com.hazelcast.jet.tests.rolling.RollingAggregateTest.test(RollingAggregateTest.java:83)
...
```
Fixes a part of #1606
=> Mark some client operations as retryable

hazelcast-jet-client-protocol/src/main/java/com/hazelcast/client/impl/protocol/template/JetCodecTemplate.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java
This can cause join() to fail with OperationTimeoutException when the job
fails instead of the actual cause. The default timeout is configured as 120 seconds and job can be running much longer than that and we already have 
custom retrying logic for the join operation.
=> Client Join message should not be marked as retryable

hazelcast-jet-client-protocol/src/main/java/com/hazelcast/client/impl/protocol/template/JetCodecTemplate.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java
This can cause join() to fail with OperationTimeoutException when the job
fails instead of the actual cause. The default timeout is configured as 120 seconds and job can be running much longer than that and we already have 
custom retrying logic for the join operation.
=> Client Join message should not be marked as retryable (#1656)

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ClientJobProxy.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java
When a join request is sent to non-master, it is automatically routed to the
master node. However if the master node is to leave the cluster then the join
request can be failed early with a OperationTimeoutException. The fix is
to make a join request never timeout - as the job can be potentially running for
a long time.
=> Fix for OperationTimeoutException when join request is sent to non-master

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java
As it can also fail with MemberLeftException, and needs to be addressed separately
=> Remove use of cancel() in JobTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java
Forward-port of https://github.com/hazelcast/hazelcast-jet/pull/1679
=> Move executor-service registration to the constructor of JobCoordinationService to avoid race

hazelcast-jet-all/src/main/resources/logging.properties
Our default logging.properties file inside the Jet JAR sets up the log line format that doesn't include the exception stacktrace. This PR add that. Hopefully we can squeeze in this small detail to the 3.2 release and make life of the users of our ZIP file easier.
=> Add exception logging to JUL logging.properties

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/DAG.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/DotTest.java
Improve DOT format to include queueSize for edges , and shorten localParallelism label
=> Improve DOT format to include queue sizes for edges

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/AbstractProcessorTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TestProcessors.java
Before, if Error was thrown in PMS.init (and others), the job will end a
half-submitted state, the submission process crashed in an unexpected
place.
Fixes #1712
=> Allow Throwable in user code

examples/event-journal/src/main/java/com/hazelcast/jet/examples/eventjournal/CacheJournalSource.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetConfig.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ScaleUpTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobMetrics_NonSharedClusterTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/WatermarkCoalescer_TerminalSnapshotTest.java
This method provides a convenience where you can configure
JetConfig inline without having to create another variable.
Some test usages are also replaced.
=> Add `JetConfig.configureHazelcast()` method

hazelcast-jet-distribution/pom.xml, hazelcast-jet-distribution/src/assembly-descriptor.xml
SLF4J is used in client APIs used by some connectors (i.e. Kafka) and without this
binding, these client APIs will not be able to do any logging.
=> Include slf4j-logj12 in the distribution

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceOrderedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceUnorderedP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/MetricsTest.java
We normally allow unfinished items after `process()` even when the inbox is
empty. We proceed to `saveToSnapshot()`, `tryProcess()`, `completeEdge()` or
`complete()` as needed and those should deal with it. This is only an issue
with async processors, sync processors finish emitting the items before they
remove the item from the inbox.
We could do a similar process as with do with `complete()`: if `complete()`
returns with an unfinished item in the outbox, we block the outbox and call
`complete()` until it's finished, before proceeding to other methods (such as
to `saveToSnapshot()`). However, doing similar thing with the `process()`
method makes no sense since it's normally implemented to only act on items in
the inbox and the inbox would be empty. We could call `tryProcess()` until …
=> Don't assert unfinished item after completeEdge

examples/imdg-connectors/src/main/java/com/hazelcast/jet/examples/imdg/MapSourceAndSinks.java
It failed because there was `Map<Integer, Integer>` which was used as source and sink but entries `<Integer, String>` tried to be written into it.
=> Fixed MapSourceAndSinks mapWithUpdating example

examples/enrichment/src/main/java/com/hazelcast/jet/examples/enrichment/Enrichment.java, examples/enrichment/src/main/resources/hazelcast.yaml
It fixes:
* map event journal in `hazelcast.yaml` in the example was not adjusted to IMDG 4.0 form
* usage of `enrichUsingAsyncService()` was removed because it was moved to grpc
* `enrichUsingHashJoin` example was not able to load needed text files
=> Fixed enrichment code sample

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ClientJobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/task/AbstractJetMessageTask.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/Job_SeparateClusterTest.java
`Job.getJobStatus` can fail if executed when the master is going down and the client doesn't know yet. This PR fixes 3 similar methods on the client, but similar issue remains on member and with other methods. `newJob` handles it on its own and differently.
Also rewrite the `JobTest` to use shared cluster, went from 130s to 11+13 seconds locally.
=> Fix few Job methods when master is going down

examples/hello-world/src/main/java/com/hazelcast/jet/examples/helloworld/HelloWorld.java
Output in this example should be indexed from `1.`. Currently it looks like this:
```
2019-11-15 08:50:17,702  INFO [HelloWorld] [main] - Top 10 random numbers observed so far in the stream are: 
2019-11-15 08:50:17,702  INFO [HelloWorld] [main] - 0. 9,215,250,687,646,003,515
2019-11-15 08:50:17,702  INFO [HelloWorld] [main] - 1. 8,965,949,692,594,839,883
2019-11-15 08:50:17,702  INFO [HelloWorld] [main] - 2. 8,811,902,117,834,639,543
2019-11-15 08:50:17,703  INFO [HelloWorld] [main] - 3. 8,676,926,573,567,461,817
2019-11-15 08:50:17,703  INFO [HelloWorld] [main] - 4. 8,528,816,033,953,131,797
2019-11-15 08:50:17,703  INFO [HelloWorld] [main] - 5. 8,307,847,392,982,656,741
2019-11-15 08:50:17,703  INFO [HelloWorld] [main] - 6. 8,248,347,955,411,719,963
2019-11-15 08:50:17,703  INFO …
```
=> Fix output of hello-world example

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Outbox.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceOrderedP.java
When we called `tryProcessWatermark`, we proceeded to `tryProcess` in a
recursion without calling `outbox.reset()`. This could lead to a situation when
each `tryProcessWatermark` and `process` offer to outbox and are rejected.
Without a `reset()`, the second offer will fail on an assertion. This compelled
us to check for `outbox.hasUnfinishedItem()` when returning from
`tryProcessWatermark()` in `AsyncTransformUsingServiceOrderedP`, and this call
seemed superfluous without knowledge of the inner workings of
`ProcessorTasklet`.
The contract of `outbox.offer()` says that if it returns `false, we should
return from the processor method. But it didn't say that we should return
`false` from the processor method, some methods don't even allow it, such as
`process()`.
The fix was to not recurse …
=> Don't call two processor methods w/o outbox.reset

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/TaskletExecutionServiceTest.java
Some tasklets have heavyweight initialization, this helps to speed up job start in such cases.
=> Parallelize tasklet initialization

pom.xml
aws plugin has a specific branch which is up to date with the latest IMDG(4.0) changes
=> Set aws plugin version to 3.0.1-SNAPSHOT

examples/early-window-results/src/main/java/com/hazelcast/jet/examples/earlyresults/support/TradeGenerator.java, examples/rolling-aggregation/src/main/java/com/hazelcast/jet/examples/rollingaggregation/TradeGenerator.java
Buffer should not be closed since they are stream jobs. There is thrown Exception in server log otherwise:
```
com.hazelcast.jet.JetException: a streaming source must not close the buffer, only batch source can
at com.hazelcast.jet.impl.pipeline.SourceBufferImpl.close(SourceBufferImpl.java:64)
at com.hazelcast.jet.examples.earlyresults.support.TradeGenerator.generateTrades(TradeGenerator.java:53)
at com.hazelcast.function.BiConsumerEx.accept(BiConsumerEx.java:47)
at com.hazelcast.jet.impl.connector.ConvenientSourceP.complete(ConvenientSourceP.java:115)
at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:346)
at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:208)
at …
```
=> Fixed streaming source must not close the buffer in code samples

examples/hadoop/pom.xml, examples/source-sink-builder/pom.xml, examples/tf-idf/pom.xml
Historically word-count examples were part of one project. It means that `books` directory was available for them on classpath. Now this directory is part of `word-count` project but other word-count related project fails with Exception like:
```
java.nio.file.FileSystemNotFoundException
at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
at java.nio.file.Paths.get(Paths.java:143)
at com.hazelcast.jet.examples.sinkbuilder.TopicSink.getBooksPath(TopicSink.java:87)
at com.hazelcast.jet.examples.sinkbuilder.TopicSink.buildPipeline(TopicSink.java:46)
at com.hazelcast.jet.examples.sinkbuilder.TopicSink.main(TopicSink.java:75)
```
This is not nice solution (due to using …
=> Add books directory on classpath in word-count examples

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImpl.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImplTest.java
We didn't subtract the header length from `usableChunkSize`. As a result, when
a single entry was just shy of the `usableChunkSize` large and inserted into an
empty chunk, it would be inserted into the current chunk and not into a
separate chunk. Later when flushing, "buffer full" was thrown when appending
the terminator.
Other changes:
- check that the chunkSize is a power of two, the code depends on this
- "put operation overwrote a previous value" assertion was thrown, but we don't
check the future for an error, we check the `firstError`, it was lost
- replace `whenCompleteAsync` with `whenComplete`, no need to offload, the
logic is lightweight
Fixes #1769
=> Fix snapshot chunking

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ExplodeSnapshotP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/UpdateMapP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/ComputeStageImplBase.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceOrderedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceUnorderedP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowGroupAggregateTest.java
We only improve the reported error, it failed before too, but depending on the order it failed either at runtime with a ClassCastException or when adding a window it complained that the pipeline doesn't have timestamps.
=> Fix merging of differently-timestamped streams

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SinkProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteJmsP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/JmsSinkBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsIntegrationTest.java
They would prevent implementing ex-once in the future without breaking changes.
=> Remove too much flexibility from the JMS sink & improvements

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/VertexDef.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/init/VertexDef_HigherPrioritySourceTest.java
If the A-B1-B2 sub-DAG is repeated N times in a sequence,
`isHigherPrioritySource` for vertex A would evaluate the sink vertex 2^N
times:
```
/-- B1 --\       /-- D1 --\       /-- F1 --\
A --+-- B2 --+-- C --+-- D2 --+-- E --+-- F2 --+--  ....
```
Fixes #1805
=> Fix exponential complexity in isHigherPrioritySrc

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImpl.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImplTest.java
We didn't subtract the header length from `usableChunkCapacity`. As a result,
when a single entry was just shy of the `usableChunkCapacity` large and
inserted into an empty chunk, it would be inserted into the current chunk and
not into a separate chunk. Later when flushing, "buffer full" was thrown when
appending the terminator.
Other changes:
- check that the chunkSize is a power of two, the code depends on this
- "put operation overwrote a previous value" assertion was thrown, but we don't
check the future for an error, we check the `firstError`, it was lost
- replace `whenCompleteAsync` with `whenComplete`, no need to offload, the
logic is lightweight (*)
Fixes #1769
=> Fix snapshot chunking (#1771)

hazelcast-jet-distribution/src/bin-filemode-755/jet, hazelcast-jet-distribution/src/bin-filemode-755/jet-start, hazelcast-jet-distribution/src/bin-regular/common.sh, hazelcast-jet-distribution/src/bin-regular/jet-start.bat, hazelcast-jet-distribution/src/root/config/hazelcast-client.yaml
Jet CLI was using log4j as with the start script, which meant it was 
logging to file and also verbosity had no effect. This is a regression
from when log4j was introduced.
Fixes #1802 and #1811
=> jet CLI shouldn’t use log4j

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteFileP.java
Without it the sink failed in jobs with timestamps.
=> Add missing WriteFileP.tryProcessWatermark()

hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/KafkaProcessors.java, hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/kafka/KafkaSources.java, hazelcast-jet-kafka/src/test/java/com/hazelcast/jet/kafka/impl/StreamKafkaPTest.java
`group.id` is used to commit offsets if processing guarantee is none, ignored otherwise. We set it to a random UUID unless explicitly set by user.
Fixes #1705
=> Add random group.id if not set explicitly

examples/hello-world/src/main/java/com/hazelcast/jet/examples/helloworld/HelloWorld.java
When using jet submit command, log4j's classloader is different than the
one used for the main class. For finding the log4j.properties log4j is
supposed to look at TCCL, which we are able to set, but in JDK9+ log4j 
because of buggy parsing logic thinks it's running in Java 1.1 instead 
and doesn't try to use TCCL (which was added in JDK 1.2). This is not a full
fix but a workaround for now.
Fixes #1837
=> Do not use log4j for HelloWorld example

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/IOUtil.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/IOUtilTest.java, hazelcast-jet-core/src/test/resources/nested/folder/test, hazelcast-jet-core/src/test/resources/nested/folder1/test1, hazelcast-jet-core/src/test/resources/nested/folder2/test2
The issue is related to the ZIP entries are not being correctly created for the directories which doesn't include a trailing slash so it leads to ZipEntry.isDirectory() calls to always return false.
Checklist
Fixes #1845
=> Fixed issue with the unzipping the nested directories.

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SourceProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/FileSourceBuilder.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadFilesPTest.java, hazelcast-jet-s3/src/main/java/com/hazelcast/jet/s3/S3Sources.java, pom.xml
Exoise readFileFn from SourcesProcessors. This allows to easily plug in custom file reading (like: CSV and TSV parsers, batched parsers, etc.).
Additionally I've added readFileFn to S3 source. 
Checklist
Links to issues fixed (if any): #1772
Fixes #1772
* ..
=> Expose read function

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadMapOrCacheP.java
It's now cloned as part of the Operation. see also: https://github.com/hazelcast/hazelcast/pull/16464
=> Remove cloning of iteration pointers

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Outbox.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamJmsP.java
An attempt to reproduce #1844
I believe the test failed because ActiveMQ returned an acknowledged message again. This PR adds more logging to be more sure about that.
=> Fix ex-once mode in StreamJmsP

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/IOUtilTest.java
=> Print collection contents in case of failure

hazelcast-jet-spring/src/test/java/com/hazelcast/jet/spring/SpringServiceFactoriesTest.java, hazelcast-jet-spring/src/test/resources/com/hazelcast/jet/spring/application-context-service.xml
The tests in the spring module creates normal instances not test instances and since the tests run in parallel they affect each other. 
Checklist
Fixes #1853
=> Add context for service tests to isolate it from other tests

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/IOUtilTest.java
=> Fixes file cleanup on the test and runs them in serial, fixes #1851

hazelcast-jet-spring/pom.xml
Spring module depends on jet-core which is wrong. It's an internal module
which is not part of the distribution. This seems like a regression from 3.2.
=> Spring module should not depend on jet-core

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ConvenientSourceP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteBufferedP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/ProcessorSupplierWithService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/ProcessorWrapper.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ManagedContextTest.java
The initialized object can have a different type than the original object passed to the `ManagedContext`. We check and throw exception if so.
Checklist
=> Add a type check for the initilized object by ManagedContext

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/TransformStatefulP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/TransformStatefulPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamStageTest.java
The aim is to make batch jobs more deterministic: all items are evicted at the
end, regardless of the WM.
Fixes #1801
=> Execute evictFn after completion

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/OutboxImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceUnorderedP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/PeekingWrapperTest.java
This could happen:
- in `currentTraverser` there was a WM pending, but there was no
unfinished item
- the initial check in `tryProcessWatermark` didn't cause to return
immediately nor attempt finishing of the current traverser
- the `watermarkCounts` collection was empty, so we added the new WM
directly to outbox
- later we emitted the `currentTraverser` and an older WM was added to
the outbox
=> Fix emission of older watermark

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ThrottleWrappedP.java
Didn't cause any actual test failure, but it could :)
- didn't override all methods
- didn't throttle when offer(int[], Object) was used
=> Fix ThrottleWrappedP

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/OutboxImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingContextUnorderedP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/PeekingWrapperTest.java
This could happen:
- in `currentTraverser` there was a WM pending
- the initial check in `tryProcessWatermark` didn't cause to return
immediately nor attempt finishing of the current traverser
- the `watermarkCounts` collection was empty, so we added the new WM
directly to outbox
- later we emitted the `currentTraverser` and an older WM was added to
the outbox
=> Fix emission of older watermark (backport of #1879)

hazelcast-jet-core/pom.xml, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamJmsP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/JmsSinkBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/JmsSourceBuilder.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsIntegrationTestBase.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsIntegrationTest_ActiveMQ.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsIntegrationTest_RabbitMQ.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamJmsPTest.java
Add tests for one more JMS broker. RabbitMQ throws very misleading error when `cf.createConnection(null, null)` is used, ActiveMQ is fine with that...
RabbitMQ tests are run nightly.
=> Add RabbitMQ tests and fix issues with it

examples/README.md, examples/hello-world/src/main/java/com/hazelcast/jet/examples/helloworld/HelloWorld.java, examples/pom.xml, examples/return-results/pom.xml, examples/return-results/src/main/java/com/hazelcast/jet/examples/returnresults/BasicObservable.java, examples/return-results/src/main/java/com/hazelcast/jet/examples/returnresults/FutureResults.java, examples/return-results/src/main/java/com/hazelcast/jet/examples/returnresults/IterableResults.java, examples/wordcount/src/main/java/com/hazelcast/jet/examples/wordcount/WordCount.java
Create a separate section of examples for return-results-to-caller feature.
Checklist
=> Make return-results-to-caller more discoverable via examples

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorState.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceP_IntegrationTest.java, hazelcast-jet-reference-manual/src/main/asciidoc/work-with-jet/configure-fault-tolerance.adoc
This happened:
- in `ProcessorTasklet.processInbox` we discovered that a new phase-2 begun
- there was an unfinished item in the outbox, so we blocked the outbox and
didn't begin the phase-2 in order to ensure that the unfinished item is finished
- however before that, the processor had returned from `process()` with an
empty inbox and an unfinished item. Therefore the process went to `fillInbox`
and found a WM there. So the state proceeded to PROCESS_WATERMARK, but the
outbox was still blocked.
- `tryProcessWatermark` tried to emit the `currentTraverser` first, but
couldn't because the outbox was blocked. And there it remained stuck, trying
that forever.
Returning `true` from `tryProcess()` or returning an empty inbox and having an
unfinished item in the outbox is allowed. So we changed …
=> Fix outbox blocking in snapshot phase 2

hazelcast-jet-core/src/test/java/com/hazelcast/jet/MulticastDiscoveryTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/HazelcastRemoteConnectorTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadMapOrCacheP_ConsistencyTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/test/SerialTest.java, hazelcast-jet-distribution/src/root/README.md
Mark additional tests which create Hazelcast/Jet Instances as serial.
Fixes #1900
=> Mark additional tests as serial

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/JetProperties.java, reference-manual/src/main/asciidoc/appendix.adoc, reference-manual/src/main/asciidoc/configuration.adoc, reference-manual/src/main/asciidoc/get-started.adoc, reference-manual/src/main/asciidoc/work-with-jet/start-jet-submit-job.adoc
Unify enterprise naming in the reference manual to Job Upgrade and Lossless Cluster Restart.
=> Unified naming of the enterprise features.

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java
fix the javadoc sample for mapUsingServiceAsyncBatched
and add maxBatchSize parameter too
Checklist
Fixes https://github.com/hazelcast/hazelcast-jet/issues/1911
=> fix the javadoc sample for mapUsingServiceAsyncBatched

checkstyle/checkstyle.xml, pom.xml
8.18 has a known security vulnerability: https://github.com/advisories/GHSA-763g-fqq7-48wg
=> Update checkstyle to 8.29

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobExecutionMetricsTest.java
Smoke tests for `executionStartTime` and `executionCompletionTime` metrics.
Checklist
=> Added test for job execution metrics

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStageWithKey.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamStageTest.java
`mapUsingServiceAsyncBatched` should be able to be used for filtering to, by setting `null` values in the output lists.
Checklist
Fixes #1909
=> Make sure mapUsingServiceAsyncBatched can do filtering

hazelcast-jet-distribution/src/root/config/log4j.properties
logs were being written to a `@jet.home@` folder. Also use abbreviated class names for the logger.
=> Improve log formatting, fix bad folder name

examples/hello-world/src/main/java/com/hazelcast/jet/examples/helloworld/HelloWorld.java, examples/return-results/src/main/java/com/hazelcast/jet/examples/returnresults/BasicObservable.java
HelloWorld example doesn't work properly when submitted to a remote cluster (needs a join to not die immediately).
Checklist
=> Fix examples not working in cluster

hazelcast-jet-core/src/test/java/com/hazelcast/jet/JetBootstrappedStandaloneTest.java
Add smoke test for `bootstrappedInstance` which is not called from `jet submit` script.
Checklist
=> Add smoke test for standalone bootstrappedInstance

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetBootstrap.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/JetLogHandler.java, hazelcast-jet-core/src/main/resources/logging.properties
Improve log experience when you don’t have log4j:
* print to stdout instead of stderr
* remove ip/cluster name/version information
* improved formatting
We should also consider not using java.util.logging at all
since every call is synchronized.
Checklist
See also: https://github.com/hazelcast/hazelcast/pull/16622
=> Improve default log experience

hazelcast-jet-distribution/src/bin-filemode-755/jet-start, hazelcast-jet-distribution/src/bin-regular/common.sh
Fixed handling `JET_LICENSE_KEY` for Unix `jet-start`.
Checklist
Fixes #1963
=> Fix handling JET_LICENSE_KEY for jet-start.

hazelcast-jet-distribution/src/bin-filemode-755/jet-start
When you start the node in daemon mode, the output filename will now have the timestamp appended to it to create a unique filename.
Checklist
Fixes #1964
=> Add timestamp to stdout filename

extensions/python/src/main/java/com/hazelcast/jet/python/PythonTransforms.java, extensions/python/src/main/java/com/hazelcast/jet/python/package-info.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/annotation/EvolvingApi.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/annotation/package-info.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/test/AssertionCompletedException.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/test/AssertionSinkBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/test/AssertionSinks.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/test/Assertions.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/test/GeneratorFunction.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/test/SimpleEvent.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/test/TestSources.java, reference-manual/src/main/asciidoc/appendix.adoc, reference-manual/src/main/asciidoc/pipeline-api/pipeline-api.adoc
* mark PythonTransforms as EvolvingAPI instead of Beta
* TestSinks/Sources are moved out of beta, except streaming source which is marked with EvolvingAPI
Checklist
=> Add Evolving API annotation, and move TestSources/Sinks out of Beta

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/AbstractDeploymentTest.java
Added test for `attachFile` and `attachDirectory`:
* attach file/dir where ID is not explicitly set up
* files from subdirs are attached if `attachDirectory` is used
* if more files and directories are attached to job they all of them are available
Checklist
=> Increase attach file/dir test coverage

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/metrics/MetricNames.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/metrics/JobLifecycleMetricsTest.java
Tests for job lifecycle metrics are limited, they only test the values on a single member cluster. 
Checklist
=> Improve test for and fix bug related to job lifecycle metrics

hazelcast-jet-distribution/src/root/config/hazelcast-client.yaml
Currently the `jet` command line is only configured to use 5701. If you run more than one instance, the other ports won't be tried.
Checklist
Fixes #1984
=> Use more ports in default client config

pom.xml
Nightly profile is broken since we split surefire test execution between serial and regular tests.
Checklist
=> Fix nightly profile

extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceConfig.java, extensions/python/src/main/java/com/hazelcast/jet/python/PythonTransforms.java, extensions/python/src/main/java/com/hazelcast/jet/python/package-info.java, extensions/python/src/test/java/com/hazelcast/jet/python/PythonInitCleanupTest.java, extensions/python/src/test/java/com/hazelcast/jet/python/PythonServiceTest.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java
Added some test cases for python. `PythonInitCleanupTest` is executed in nightly profile since it takes some non-trivial time (~85seconds). Here is the result for nightly profile run with this branch - http://jenkins.hazelcast.com/view/Jet/job/jet-oss-master-nightly-temp/2/testReport/com.hazelcast.jet.python/PythonInitCleanupTest/
One of tests is ignored due to https://github.com/hazelcast/hazelcast-jet/issues/1995
Checklist
=> Increase python test coverage

extensions/python/src/main/java/com/hazelcast/jet/python/PythonService.java, extensions/python/src/test/java/com/hazelcast/jet/python/PythonInitCleanupTest.java, extensions/python/src/test/java/com/hazelcast/jet/python/PythonServiceTest.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/AsyncOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/ExceptionUtil.java
Sometimes the processors may fail with a non-serializable exception.
Convert the exception to a String and fail with a generic exception in
this case.
Checklist
Fixes #1995
=> Handle non-serializable exceptions in AsyncOperation

extensions/avro/pom.xml, extensions/hadoop/pom.xml, extensions/kafka/pom.xml, extensions/pom.xml, extensions/python/pom.xml, extensions/s3/pom.xml
Python module also had an extra dependency which caused it to be shaded 
into the distribution jar
=> Standardize how extension modules import hazelcast-jet

examples/files/src/main/java/com/hazelcast/jet/examples/files/SalesCsvAnalyzer.java, examples/files/src/main/java/com/hazelcast/jet/examples/files/avro/AvroSink.java, extensions/avro/src/main/java/com/hazelcast/jet/avro/AvroProcessors.java, extensions/avro/src/main/java/com/hazelcast/jet/avro/AvroSinks.java, extensions/avro/src/test/java/com/hazelcast/jet/avro/AvroSinkTest.java, reference-manual/src/main/java/integration/Avro.java
The sink unnecessarily required a supplier, where a simple Schema object would be enough.
Note: it also needs backporting to 4.0 release branch.
Checklist
* `AvroSinks.files` takes `Schema` now instead of `Supplier<Schema>`
=> Replace Supplier<Schema> with Schema for Avro sink

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetGetJobConfigMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetGetJobSummaryListMessageTask.java
Removed dependency to `nodeEngine` and used already defined/inherited `toData()` in `JetGetJobConfigMessageTask` & `JetGetJobSummaryListMessageTask`.
Checklist
=> Remove dependency to nodeEngine from Jet tasks.

examples/grpc/pom.xml, extensions/python/pom.xml
Copy of https://github.com/hazelcast/hazelcast-jet/pull/2018 because PR builder is not able to be executed for given PR for any reason.
Checklist
=> Bump protobuf-maven-plugin from 0.5.1 to 0.6.1

reference-manual/pom.xml
Reference manual should be packaged same as in `3.x` branch.
Checklist
=> Change packaging of refman to pom

extensions/pom.xml
The licenses section is the standard way to provide information
about a license of a module. This is used by tools such as
license-maven-plugin.
It is inherited by child modules by default, so with the current
setting the extensions inherit the Apache 2 license of the root
module (this can be verified by running `mvn help:effective-pom`
in a module directory).
Checklist
* None
=> Set license of extension modules in pom

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/JetConsoleLogHandler.java, hazelcast-jet-core/src/main/resources/hazelcast-jet-member-default.xml, pom.xml
Do not write version number, ip and cluster name on every log message by default
This option can be turned on again by  setting `hazelcast.logging.details.enabled` to `true`
Checklist
=> Disable logging details by default

hazelcast-jet-all/pom.xml, hazelcast-jet-distribution/pom.xml, pom.xml
Javadoc for Jet+IMDG is currently not generated anywhere in Jet repo. In `3.x` version it was generated in `hazelcast-jet-distribution` but it is not working now since that module is packaged as `pom`.
After this PR javadoc for Jet+IMDG is generated by command `mvn javadoc:aggregate -DskipTests` called from `hazelcast-jet-distribution` module (not from root module).
Moreover version of `maven-javadoc-plugin` is downgraded back to `3.0.1`. Version `3.1.x` has some issue during javadoc generation, version `3.0.1` works correctly. 
Checklist
=> Generate javadoc in distribution module

hazelcast-jet-distribution/pom.xml
Some dependencies were still missing in javadoc generation and exclude some more packages
from javadoc generation.
Checklist
=> add missing dependencies and fix excluded names

hazelcast-jet-core/pom.xml, hazelcast-jet-distribution/pom.xml, pom.xml
It was leftover in the generated javadoc
Checklist
=> Exclude classgraph from javadocs

reference-manual/src/main/asciidoc/get-started.adoc
Typo fix in `get-started.adoc`
=> fixing command name (start-jet -> jet-start)

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java
Fix link in `Jet`'s JavaDoc, straightforward.
=> Fix link in Jet JavaDoc

site/docs/architecture/in-memory-storage.md
I think the new node receives primary of partition 1 from node 1st instead of partition 2.
=> Minor mistake in the documentation

hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/ResourceConfigTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/NestedClassIsLoaded.java
Added regression test for non-existing package passed in `JobConfif.addPackage()`.
Checklist
=> Add test for non-existing package for JobConfig

examples/jms/src/main/java/com/hazelcast/jet/examples/jms/JmsQueueSample.java, examples/jms/src/main/java/com/hazelcast/jet/examples/jms/JmsTopicSample.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsIntegration_NonSharedClusterTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsSourceIntegrationTestBase.java, reference-manual/src/main/java/integration/JMS.java
Checklist
- Change of public API for `Sources.jmsQueue` and `Sources.jmsTopic`
=> Re-order jms source parameters to have the lambda as last parameter

examples/sliding-windows/src/main/java/com/hazelcast/jet/examples/slidingwindow/TopNStocks.java, examples/trade-source/src/main/java/com/hazelcast/jet/examples/tradesource/TradeSource.java
`TopNStocks` code sample does not have any valuable output after migration to new `TradeSource` generator. There were two issues:
* it started to use all tickers instead of limited number (`500`)
* changes in price started to be too low that display cents of double was not sufficient (fixed by using `5f` instead of original `2f`)
Original output looks like:
```
Top rising stocks:
AMCX by 0.04
ASML by 0.04
BIIB by 0.04
ALTY by 0.03
ACIA by 0.03
Top falling stocks:
AGNC by -0.04
AXSM by -0.04
ACRX by -0.03
AREX by -0.03
ACGLP by -0.03
```
Not valuable output after TradeSource migration looks like:
```
Top rising stocks:
HMTA by 0.00
MSDIW by 0.00
SQBG by 0.00
ELOS by 0.00
CLRBW by 0.00
Top falling stocks:
INVT by -0.00
DBVT by -0.00
ADRA by -0.00
OFED by -0.00
WFM by -0.00
```
Output after …
=> Fix sliding-windows TopNStocks code sample

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Inbox.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteObservableP.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ArrayDequeInboxTest.java
Allowed job-level serializers to be used with IMDG `Observable`s.
Checklist
=> Enable job-level serializer for IMDG Observables

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/JdbcSinkBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsSinkIntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/SinkStressTestUtil.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteJdbcPTest.java
Changes:
- Fix incorrect usage of forceful instead of graceful shutdown in `JmsSinkIntegrationTest` and `WriteJdbcPTest`. 
- Removed unused assertion from `testFailJob_withNonTransientException()` in `WriteJdbcPTest`.
- Fix `since` for `jdbcBuilder`
Checklist
=> Fix graceful atLeastOnce stress tests for JMS and JDBC sink

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/ServiceFactories.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/ServiceFactory.java
Javadoc on mapUsingService is missing a warning about the restrictions on cooperative processors and the need to call `toNonCooperative` if they aren't respected.
Checklist
=> Add cooperative warning to mapUsingService

hazelcast-jet-core/pom.xml
Tests fail with older version on Java 14.
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 58
at nl.jqno.equalsverifier.internal.lib.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:184)
at nl.jqno.equalsverifier.internal.lib.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:166)
at nl.jqno.equalsverifier.internal.lib.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:152)
at nl.jqno.equalsverifier.internal.lib.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:82)
at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$Default.parse(TypePool.java:1174)
at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:1160)
at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$Abstra …
```
=> Update equalsverifier version to 3.1.13

hazelcast-jet-distribution/src/root/config/hazelcast-client.yaml
To have a better OOTB experience with the CLI when dealing with Kubernetes clusters from outside networks with port-forwarding
Checklist
=> Disable smart routing by default

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/ResourceConfig.java
The user may attempt to add a JDK class to the JobConfig. Many of these classes are loaded by the bootstrap classloader, which means their `.getClassLoader()` returns null. Currently Jet just barfs with an NPE, this introduces a nicer message.
Fixes https://github.com/hazelcast/hazelcast-jet/issues/2107.
Checklist
=> Improve error message in JobConfig.addClass() when class.getClassLoader() returns null

hazelcast-jet-core/pom.xml, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/JmsSinkBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsSinkIntegrationTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsSourceIntegrationTest_ActiveMqArtemis.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsSourceIntegration_NonSharedClusterTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamJmsPTest.java, pom.xml
Fixes #1954 - the broker sometimes didn't show up in tests.
We also had to change the default `connectionFn` - we relied on particular behavior of ActiveMQ which doesn't exist in Artemis, and IMO Artemis behavior is _more correct_: the `createConnection()` method returned an `XAConnection` when called on an `XAConnectionFactory`. In Artemis, only the `createXaConnection()` returns an `XAConnection`.
=> Replace ActiveMQ in tests

pom.xml
Bumped Classgraph version to 4.8.66.
Checklist
Fixes https://github.com/hazelcast/hazelcast-jet/issues/2130 by https://github.com/classgraph/classgraph/issues/400
=> Bump Classgraph version to 4.8.66

site/docs/api/pipeline.md, site/docs/api/serialization.md, site/docs/api/sources-sinks.md, site/docs/api/stateful-transforms.md, site/docs/concepts/processing-guarantees.md, site/docs/design-docs/index.md, site/docs/how-tos/observables.md, site/docs/how-tos/stream-imap.md, site/docs/operations/kubernetes.md, site/docs/operations/monitoring.md, site/website/blog/2020-02-20-transactional-processors.md, site/website/blog/2020-03-02-jet-40-is-released.md, site/website/package.json, site/website/versioned_docs/version-4.0/api/pipeline.md, site/website/versioned_docs/version-4.0/api/serialization.md, site/website/versioned_docs/version-4.0/api/sources-sinks.md, site/website/versioned_docs/version-4.0/api/stateful-transforms.md, site/website/versioned_docs/version-4.0/operations/monitoring.md, site/website/versioned_sidebars/version-4.0-sidebars.json
* Fix some broken links
* don't invoke download links for link-checker
* Use local javadoc instead of old URL
* 4.0 sidebar included invalid links
=> Various docs fixes

hazelcast-jet-core/pom.xml
As we don't have many kotlin classes, it doesn't provide any real speedup.
Checklist
=> Turn off kotlin incremental compilation (removes build warning)

pom.xml
This option is useful when a checkstyle report is generated,
it adds links to the source code directly from the checkstyle
html report.
We fail the build so the only report we ever get is empty report,
making this option not useful.
Checklist
=> Turn off linkXRef option to remove build warning

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java
Added the toString to the 'com.hazelcast.jet.config.JobConfig' class
Checklist
Links to issues fixed (if any): https://github.com/hazelcast/hazelcast-jet/issues/2126
attached is the screenshot of code testing. 
Fixes #NNNN
* ..
=> issue_2126 : add toString() to JobConfig

pom.xml
We put the setting directly to pom as we want to use it in all builds
and 1G heap should be fine to upload to S3.
The hprof file will be put to root directory of the module which runs
the test.
In case there are multiple heap dumps we can link to the file
to particular test via pid.
Checklist
=> Enable heap dump on OOM in tests

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/UtilTest.java
This combines Objects.requireNonNull with our Util.checkSerializable
into single method call. Useful in source/sink builders for checking
parameters.
Checklist
=> Add checkNonNullAndSerializable util method

extensions/grpc/src/main/java/com/hazelcast/jet/grpc/GrpcServices.java, extensions/grpc/src/main/java/com/hazelcast/jet/grpc/impl/GrpcUtil.java, extensions/grpc/src/test/java/com/hazelcast/jet/grpc/GrpcServiceTest.java, extensions/python/src/main/java/com/hazelcast/jet/python/PythonService.java
Several fixes
- closing channels doesn't happen imediatelly - added awatTermination
- Server stored in local variable not shutdown at end of test
- onCompleted should call onCompleted on responseObserver
Checklist
=> Shutdown gRPC channels cleanly

pom.xml
Maven compile plugin has a [bug](https://issues.apache.org/jira/browse/MCOMPILER-368) dues to which our `package-info.java` files are always considered dirty and most modules are always recompiled, even if there aren't actual changes in them. 
Will try a workaround for this by setting the `javac` param `pkginfo`.
Checklist
=> Add javac param to stop package info files sabotaging incremental compilation

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJetInstance.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ObservableShutdownTest.java
Triggering `Observable.destroy()` on `JetInstance` shutdown has some unexpected consequences (for example: you kill a client, the client destroys an observable, job execution terminates a bit later and it re-creates the observable in the meantime, next execution starts with a few left-over results). This is also related to the fact that observables aren't job specific and that we allow them to be reused in multiple executions... But anyways, better to not destroy them in such unexpected ways (especially since it's not even documented). Leave all destroys be explicitly triggered by users.
Fixes [#2059 ](https://github.com/hazelcast/hazelcast-jet/issues/2059)
Checklist
=> Remove destroying Observables on JetInstance shutdown

site/docs/api/serialization.md
Align order of Serialization interface in benchmark with previous benchmark and Serialization interface table. It's more simple to read if it has the same order.
Checklist
=> Align order of serialization interface in benchmark

site/docs/api/spring.md, site/docs/design-docs/004-spring-boot-starter.md, site/docs/tutorials/spring-boot.md
Add IMDG configuration options for Jet Spring Boot Starter
Checklist
Related to https://github.com/hazelcast/hazelcast-jet-contrib/pull/75
=> [004] Add IMDG configuration options for Jet Spring Boot Starter

extensions/grpc/src/main/java/com/hazelcast/jet/grpc/impl/UnaryService.java
see also: https://github.com/grpc/grpc-java/issues/6929
Checklist
=> UnaryService for gRPC doesn't need `volatile` on StreamObserver

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SuspendResumeTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TestUtil.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/JobSummaryTest.java
Fix flaky test where job can be completed from JobResult
Reproducible by adding delay to doInvokeJoinJob in AbstractJobProxy.
Fixes #2072
Add stacktrace to failureText in JobResult, stack trace is useful for debugging
Checklist
=> Fix flaky test in ExecutionLifecycleTest

examples/grpc/src/main/java/com/hazelcast/jet/examples/grpc/GRPCEnrichment.java, extensions/grpc/src/test/java/com/hazelcast/jet/grpc/GrpcServiceTest.java
The default cached thread pool is not suitable as it creates a new
thread when there is no available thread, leading to high amount of
threads.
Fixes #2162
Checklist
=> Create gRPC servers with fixed thread pool

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AbstractAsyncTransformUsingServiceP.java
The current default async ops per processor is 256. With a high default local parallelism on a multicore server this leads to many thousands of concurrent requests. Reducing to 4.
Checklist
=> Reduce default maximum number of concurrent async ops per processor in mapUsingService

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/BatchStageImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StreamStageImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/HashJoinTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/HashJoinP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralHashJoinBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/StreamStage.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/package-info.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/HashJoinPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamStageTest.java
As discussed on Gitter and mentioned in #1238, new users often don't know that hashJoin is not inner join (like their intuition says). Adding innerHashJoin with pre-filtering will reduce filtering in user apps and make API more clear for new users.
Checklist
Fixes #1238
=> Inner join distinction

extensions/grpc/src/test/java/com/hazelcast/jet/grpc/GrpcServiceTest.java, extensions/grpc/src/test/proto/greeter.proto
Add test for gRPC using `mapUsingServiceAsyncBatched` in pipeline and `repeated` in protobuf.
Checklist
=> Add test for gRPC with mapUsingServiceAsyncBatched

extensions/grpc/src/test/java/com/hazelcast/jet/grpc/GrpcServiceTest.java
Add test for using `mapUsingService` for gRPC
Checklist
=> Add test for mapUsingService stage with gRPC

site/docs/api/serialization.md
Fixed jet version in docs - replaced {hazelcast.jet.version} with {jet-version.}
Checklist
=> Fix jet version in docs

hazelcast-jet-distribution/src/root/README.md
=> Fix ref manual link in README

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SinkProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteMapP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/json/JsonUtil.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/json/package-info.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SinksTest.java
Add toKeyFn/toValueFn to WriteMapP
Add convenience for HazelcastJsonValue
Checklist
Fixes #NNNN
* ..
=> Add toKeyFn/toValueFn to WriteMapP

checkstyle/checkstyle.xml, hazelcast-jet-core/src/main/java/com/hazelcast/jet/json/JsonUtil.java
Original checkstyle `JavadocType` and `JavadocMethod` was split into those and `MissingJavadocType` and `MissingJavadocMethod` in checkstyle version 8.20. We started to use version 8.29 instead of 8.18 which means that this functionality is currently missing in our checkstyle.
For more details see https://checkstyle.sourceforge.io/releasenotes.html#Release_8.20
Checklist
=> Add MissingJavadoc checks to checkstyle

examples/trade-source/pom.xml
`trade-source` artifacts are currently not deployed to snapshot repositories.
Checklist
=> Do not skip deploy for trade-source

site/docs/operations/cdc-deployment.md
Fix the linter error MD025-singletitle by reducing each header's level by one
=> Fix the markdown linter error.

extensions/grpc/src/main/java/com/hazelcast/jet/grpc/GrpcProperties.java, extensions/grpc/src/main/java/com/hazelcast/jet/grpc/GrpcServices.java, extensions/grpc/src/main/java/com/hazelcast/jet/grpc/impl/BidirectionalStreamingService.java, extensions/grpc/src/main/java/com/hazelcast/jet/grpc/impl/GrpcProperties.java, extensions/grpc/src/main/java/com/hazelcast/jet/grpc/impl/GrpcUtil.java, extensions/grpc/src/main/java/com/hazelcast/jet/grpc/impl/UnaryService.java, extensions/python/src/main/java/com/hazelcast/jet/python/PythonService.java, site/docs/how-tos/grpc.md
Changes:
- create channel per processor
- make service destroy timeout and channel shutdown timeout configurable
- Use common ForkJoinPool as executor for the channel
Checklist
=> Improve gRPC module

hazelcast-jet-distribution/src/root/config/log4j2.properties
it was creating some files like `'.'2020-05-20` when rolling the logs
=> Fix rolling log filename

extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/AuthElasticSinksTest.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/CommonElasticSinksTest.java
Behavior of delete/update non existing document for elastic sink is not ideal now. It fails job if this happen. However it can be a problem when job is restarted (and the same delete request should be executed again) etc. Fixing this can be complicated - for Jet 4.2 this will be covered by documentation and eventually changed/fixed in the future. This PR adds regression tests for checking that behavior was not changed unexpectedly.
Checklist
=> Add test for elastic and update/delete for non existing document

site/docs/enterprise/installation.md, site/docs/enterprise/management-center.md, site/docs/enterprise/operator-openshift.md, site/docs/operations/docker.md, site/docs/operations/kubernetes.md, site/website/core/Footer.js, site/website/pages/en/docs.js, site/website/sidebars.json
* shorten very long titles on sidebar and titles containing redundant “jet”
* fix redirect url for /docs not to have html suffix
* add enterprise docs to sidebar so you can view it for previous versions
=> some docs improvements:

hazelcast-jet-distribution/src/bin-filemode-755/jet-start
This replaces the shell process with the Java process.
Due to signal handling in bash we would not be able to
stop Jet using Ctrl+C without this when using jet-start
in Docker container.
Checklist
=> Use exec when starting Jet in jet-start

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetBootstrap.java
Just adding a missing space in the Exception message.
=> Typo. Add missing space in a message

site/website/blog/2020-06-09-jdk-gc-benchmarks-part1.md
- A reader noted that the official acronym isn't Z but ZGC
- In the data-light streaming section, we said "GC pause" where actually it was just concurrent GC overhead causing increased latency
=> Blog post updates

site/website/siteConfig.js
Enable filter on version and language on the documentation website.
resolves algolia/docsearch-configs#2041
=> fix(search): filter on version & language

site/website/blog/2020-06-09-jdk-gc-benchmarks-part2.md
Fixed the small typo in the GC benchmark blog post.
=> Small typo fix in the GC blog post. 

extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/BaseElasticTest.java
Having parallel tests causes multiple Elasticsearch containers to start,
making the tests slower on low-core machines (4C).
The main time consuming part of the tests now is the container start,
which can't be avoided - we already reuse containers between test
classes.
=> Use SerialTest for Elasticsearch integration tests

pom.xml
Removes 'WARNING: An illegal reflective access operation has occurred'
=> Upgrade spotbugs plugin to 4.0.0

hazelcast-jet-all/pom.xml
Sources of shaded jars are already attached, but with
original packages.
The mismatch breaks javadoc in the enterprise. This fixes the
javadoc build.
Also removed the dangling dots from the patterns which
caused syntax error in the shaded sources (package
statement ended with . instead of ;)
=> Shade and relocate also sources

extensions/avro/src/main/java/com/hazelcast/jet/avro/AvroSerializerHooks.java, extensions/avro/src/main/resources/META-INF/services/com.hazelcast.SerializerHook, extensions/avro/src/test/java/com/hazelcast/jet/avro/AvroSerializerTest.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/SerializerHookConstants.java
=> Add serializer for avro Utf8 class

site/docs/tutorials/map-join.md, site/docs/tutorials/pulsar.md, site/docs/tutorials/windowing.md
Replace the deprecated usage of gradle obj `classifier` with `archiveClassifier` in the tutorials.
Checklist
=> Remove the deprecated gradle object from the tutorial documents

extensions/avro/src/main/java/com/hazelcast/jet/avro/AvroSourceBuilder.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadFilesP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/FileSourceBuilder.java
Change default local parallelism from 2 to 4 for avro/file/json sources
Checklist
Fixes #2352
* Change default preferedLocalParallelism from 2 to 4
=> Change default local parallelism from 2 to 4 for avro/file/json sources

extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/RecordPartImpl.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/AbstractPostgresCdcIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/MultiTableCacheIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcIntegrationTest.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SinkProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java
Intention: come up with a pipeline, which reads two different tables from a database via CDC and keeps an up-to-date map with their merged values, in this case customers and their orders. 
Particular details to pay attention to:
* I've added a version of `Sinks.mapWithEntryProcessor` where you can specify `maxParallelAsyncOps`; I have to set that to 1 for this scenario, to avoid Sink-to-IMap reordering due to multiple async requests
* I've changed multiple sinks to have partitioned input-edges, where a partitioning function is naturally available
* the test code probably runs on a local member only, a remote cluster will not know how to deserialize objects like `Customer`, `Order` and `OrdersToCustomer`; if/when we turn this into a tutorial or cookbook entry we will need to change it to …
=> Add test for CDC join scenario

extensions/cdc-mysql/src/main/java/com/hazelcast/jet/cdc/mysql/MySqlCdcSources.java, extensions/cdc-postgres/src/main/java/com/hazelcast/jet/cdc/postgres/PostgresCdcSources.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcIntegrationTest.java
Set snapshot mode to `exported` where data loss is one message only.
Checklist
=> [005] Make Postgres dataloss on snapshot-stream sync less severe

hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/ResourceConfigTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/YamlJetConfigResolutionTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesPTest.java
The error in `ResourceConfigTest` was 
```
Expected: (an instance of com.hazelcast.jet.JetException and exception with message a string containing "Not an existing, readable file: /i/do/not/exist")
but: exception with message a string containing "Not an existing, readable file: /i/do/not/exist" message was "Not an existing, readable file: \i\do\not\exist"
```
=> Fix test failures on Windows

hazelcast-jet-all/pom.xml, hazelcast-jet-distribution/pom.xml
When generating javadoc, some Hazelcast modules would be skipped because of transitive dependencies
=> Fixes to javadoc generation

hazelcast-jet-all/pom.xml
Maven jar plugin recreates the original jar only
if the jar is missing or there are changes in the inputs.
The shaded jar contains all inputs up to date so it is not
changed and is used as input for shade plugin if you run
the build 2nd time. Causing the build to fail due to overlapping
resources.
The forceCreation parameter forces the creation of the jar every time,
only for the hazelcast-jet-all module.
See https://maven.apache.org/plugins/maven-jar-plugin/jar-mojo.html#forceCreation
=> Avoid shading already shaded jar

extensions/elasticsearch/elasticsearch-5/src/test/java/com/hazelcast/jet/elastic/LocalClusterElasticSourcesTest.java, pom.xml
`test-coverage` profile did not run nightly test.
`LocalClusterElasticSourcesTest` in `elasticsearch-5` module is ignored for test coverage since it gets stuck in this configuration for some reason. We can investigate it deeper later.
Checklist
=> Add nightly tests to test-coverage profile

pom.xml
Serial tests are executed in both `serial-tests` and `regular-tests` parts of `all` profile. Solution is to have only one execution in `all` profile (in the same way as it is for `nightly` profile).
Checklist
=> Fix serial tests in profile all

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/JobRepositoryTest.java
Every exception during tryStartJob should finalize the job with the error. The
previous alternative just ignored it and left the job in an inconsistent state.
What triggered this error was a non-serializable ProcessorSupplier that
implemented DataSerializable: it wasn't caught in `checkSerializable`, but
later when calling `toData(plan)`.
=> Fix error handling in tryStartJob()

extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/AbstractCdcIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/AbstractMySqlCdcIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/AbstractPostgresCdcIntegrationTest.java, extensions/elasticsearch/elasticsearch-5/src/test/java/com/hazelcast/jet/elastic/BaseElasticTest.java, extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/BaseElasticTest.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/BaseElasticTest.java, extensions/hadoop/src/test/java/com/hazelcast/jet/hadoop/impl/HadoopTestSupport.java, extensions/s3/src/test/java/com/hazelcast/jet/s3/S3MockTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsSourceIntegrationTest_RabbitMQ.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteJdbcPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/test/IgnoreInJenkinsOnWindows.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/test/IgnoreOnJenkinsWindows.java, pom.xml
Introduce `windows-jenkins` which can be used for running test on our AWS windows machine from jenkins. Some notes:
- It runs all tests (common and nightly). 
- There is `IgnoreOnJenkinsWindows` category for tests which uses docker since our machine is not able to run them.
- There are some failures in `YamlJetConfigResolutionTest`. We should investigate them after merge once this profile will be available for jenkins job.
Checklist
=> Add windows-jenkins profile

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/observer/ObservableImpl.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ObservableResultsTest.java
Cancelling an observable's listener was just setting a flag and not actually stopping any ongoing processing of previously received results. This fix improves the situation and also makes the test a bit more tolerant. 
Checklist
Fixes #2415
=> Skip processing in-flight observable results when observer is cancelled

extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/ChangeRecord.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSerializerHooks.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/ChangeRecordImpl.java, extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/WriteCdcP.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/MultiTableCacheIntegrationTest.java, site/docs/tutorials/cdc-join.md
We are using sequence numbers from Debezium to fix reordering of CDC events anyways, so why not make them part of the API.
Checklist
=> [005] Make Debezium sequences public

extensions/elasticsearch/elasticsearch-5/src/test/java/com/hazelcast/jet/elastic/ElasticSinkBuilderTest.java, extensions/elasticsearch/elasticsearch-5/src/test/java/com/hazelcast/jet/elastic/LocalElasticSinkTest.java, extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/ElasticSinkBuilderTest.java, extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/LocalElasticSinkTest.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/ElasticSinkBuilderTest.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/LocalElasticSinkTest.java
The default parallelism for the Sink is 2, so 2 clients are created.
The ClientHolder in the test stored only one of the 2 clients created.
Sometimes the same client instance is returned for both threads,
causing the issue #2427.
This commit changes so all clients are stored in the holder and verified.
Also adds a test for closing the client in a non-failing Sink.
Fixes #2427
Checklist
=> Fix client.close() verification in Elastic sink test

extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/WriteKafkaPTest.java
We waited for 2 seconds for the kafka to deliver the results, probably
it wasn't long enough. Also it could happen that we receive 1 record and
don't poll for the next, even though it wasn't the case this time.
An attempt to fix #2398
=> Fix WriteKafkaPTest.test_resumeTransaction failure

extensions/elasticsearch/elasticsearch-5/src/main/java/com/hazelcast/jet/elastic/ElasticClients.java, extensions/elasticsearch/elasticsearch-5/src/main/java/com/hazelcast/jet/elastic/ElasticSources.java, extensions/elasticsearch/elasticsearch-5/src/test/java/com/hazelcast/jet/elastic/ElasticClientsTest.java, extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/ElasticClients.java, extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/ElasticSources.java, extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/ElasticClientsTest.java, extensions/elasticsearch/elasticsearch-7/src/main/java/com/hazelcast/jet/elastic/ElasticClients.java, extensions/elasticsearch/elasticsearch-7/src/main/java/com/hazelcast/jet/elastic/ElasticSources.java, extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/ElasticClientsTest.java
Takes host and optional scheme and port. Came up during the CDC/Elastic example. This is what most users most likely want to use.
=> Add ElasticClients#client(java.lang.String) convenience method 

hazelcast-jet-all/src/main/java/com/hazelcast/jet/server/JetCommandLine.java, hazelcast-jet-all/src/test/java/com/hazelcast/jet/server/JetCommandLineTest.java, hazelcast-jet-all/src/test/resources/com/hazelcast/jet/server/hazelcast-client-template.yaml, hazelcast-jet-all/src/test/resources/com/hazelcast/jet/server/hazelcast-client-test.xml
Make --targets update only the relevant options (cluster name and address) of `hazelcast-client.yaml`.
Checklist
Fixes #2373
=> Fix client config overriding by --targets option

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsSourceIntegration_NonSharedClusterTest.java
=> Extend assertion timeouts in JmsSourceIntegration_NonSharedClusterTest.when_memberTerminated_then_transactionsRolledBack

extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/RecordPart.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/JsonUtilTest.java, pom.xml
When doing object mapping from JSON for CDC we've noticed that there is a problem with null values not being handled properly by Jackson jr (used by our JSON convenience code). This is the issue that has been submitted to them: https://github.com/FasterXML/jackson-jr/issues/73. They have fixed the problem and now we need to upgrade to the fixed version. That's what this PR does.
Checklist
=> [005] Upgrade Jackson jr version to get rid of null value bug

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobRestartWithSnapshotTest.java
The test waits for a snapshot. The snapshot was proceeding correctly but slowly, causing the test to fail.
Checklist
Fixes #2450
=> Increase timeout in JobRestartWithSnapshotTest.when_nodeDown_then_jobRestartsFromSnapshot

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/CancellationTest.java
Increase the timeout of the assertions in the cancellation tests. To explain briefly, the assertTrueEventually calls in the tests timed out before the execution of the job starts. I explained my reasoning on this within the issue.
Checklist
Fixes #2449.
=> Increase the timeout in the CancellationTests

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/test/TestSourcesTest.java
The test was sensitive to initial delays, the new code tests for deterministic results.
Checklist
=> Improve TestSources.longStreamTest

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamEventJournalP_WmCoalescingTest.java
The event journal processor publishes the idle message watermark as its first message, instead of emitting the item written with map.put in the test and this causes the test to fail. To solve it, I increased the idle timeouts of event journal processors in StreamEventJournalP_WmCoalescingTest.
Checklist
Fixes #2465
=> Increase the idleTimeouts in StreamEventJournalP_WmCoalescingTest

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/test/TestSourcesTest.java
When Jenkins slowed down, tests are failed with this many items. I reduced its number.
Checklist
Fixes #2477
=> Decrease the itemsPerSecond from 1_000 to 250 in test_longStream.

extensions/elasticsearch/elasticsearch-5/src/test/java/com/hazelcast/jet/elastic/CommonElasticSourcesTest.java, extensions/elasticsearch/elasticsearch-5/src/test/java/com/hazelcast/jet/elastic/ElasticClientsTest.java
Some tests used empty SearchRequests, which searches in whole ES instance.
ES 5.6.x creates an index with monitoring events after it runs for around half a minute.
These documents then appeared in search results causing the test to fail.
Limiting the search request to `my-index` fetches only the required results.
Fixes #2486.
=> Limit all ES 5 tests to `my-index`

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/OperationLossTest.java
Fixes #2498
The change unfortunately makes the test run more slowly, from 25s to 37s locally. Can't make the test parallel because it uses `TestProcessors` which use static variables (also the logs would mess up).
=> Increase timeout for OperationLossTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java
The job status was reported as `RUNNING` briefly while the `finalizeJob`
method was running. The `COMPLETING` state is actually never set to
`MasterContext.jobStatus`. It is only calculated in
`JobCoordinationService.getJobStatus()` if the status is `RUNNING`, but
the execution has been terminated. However, we've assigned `null` to
`requestedTerminationMode` before setting `jobStatus` to something else
than `RUNNING`.
The fix is to set the `jobStatus` before clearing the
`requestedTerminationMode`.
=> Fix race in Job.getStatus()

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetBootstrap.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/GlobalFlatMapStatefulTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/GlobalMapStatefulTransform.java
- Add missing newJob(Pipeline, JobConfig) and newJobIfAbsent(Pipeline, JobConfig) methods to JetBootstrap. Because of these missing methods, we do not add the class definitions in the jar to JobConfig and that was causing us to get ClassCastException.
- Extra: Converted two forgotten non-serializable functions to serializable.
Checklist
Links to issues fixed (if any): 
Fixes #2510
=> Fix the issue that some jobs cannot be sent to cluster.

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java
Fixes #2487
Scenario:
- The current successful snapshot is 10.
- The master started snapshot 11 phase 1. The (only) member executed it,
but before the master handled the phase1 response, the job was
forcefully restarted.
- The master restarted the job. Handling of the phase1 response was
blocked due to synchronization in MasterContext.
- The master started the job and was about to restore state from
snapshot 10.
- The response for snapshot 11 phase 1 was handled by the master. It was
a success response so the master stored it and cleared the snapshot map
for snapshot 10.
- "snapshot doesn't exist or is damaged" error was thrown because the
restoration from snapshot 10 still didn't begin.
This issue went unnoticed for a long time because there was partial
handling for it: even though we …
=> Fix handling of late snapshot responses

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Job.java
The `String` cause is probably not ok in the long run, let's not commit to it.
=> Mark `getSuspensionCause` as evolving API

site/website/blog/2020-07-16-designing-evergreen-cache-cdc.md
There are other changes backing these on the [Evergreen Cache repo's `fix-sink` branch](https://github.com/hazelcast-demos/evergreen-cache/tree/fix-sink), but I will keep those away from the `master` branch until merging this in, so the Blog and backing codebase remain in sync.
=> Change Evergreen Cache tutorial to proper CDC sink

hazelcast-jet-all/src/test/java/com/hazelcast/jet/server/JetCommandLineTest.java
The test `test_targets_after_command_and_configuration_from_default_config_together` creates a client config which is picked up by other tests if run parallel. There are also other test failures in this class which can be avoided if the tests run serial.
Checklist
Fixes #2470
* ..
=> Convert JetCommandLineTest to serial

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetConfigXmlGenerator.java
Found by analysis in Sonar - https://sonarcloud.io/organizations/devopshazelcast-github/rules?open=java%3AS2755&rule_key=java%3AS2755
Checklist
=> Disable access to external entities in XML parsing

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/config/YamlJetConfigBuilder.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/YamlJetConfigResolutionTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/test/JetDeclarativeConfigFileHelper.java
Added closing `YamlJetConfigBuilder` input on `build()` so the resources are correctly released.
Fixes #2395
=> Close YamlJetConfigBuilder input on build()

hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadMapOrCacheP_ConsistencyTest.java
Currently we create a `ClientConfig` to connect to the remote cluster but does not set the port. 
We expect it to have the default port. 
But sometimes the created remote cluster has higher port number such as 5705, in which case client cannot connect to the cluster. 
With the fix we configure the client with the host:port value of the created hazelcast instance.
Checklist
Fixes #2437 
* ..
=> Use host:port for client to connect to remote cluster

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobRepository.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/Networking.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ReceiverTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/SenderTasklet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/MulticastDiscoveryTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/MemberReconnectionTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ReceiverTaskletSendLimitTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ReceiverTaskletTest.java
The failure scenario was this:
- SenderTasklet reaches EOS in tryFillInbox(), writes DONE_ITEM
- We try to send the last packet in the call method, Connection.write()
returns true
- The connection is broken and the packet is never sent. The connection
is transparently reestablished, but the packet isn't sent again.
- Jet doesn't use this connection anymore in SenderTasklet as EOS has
been reached, so the failure goes unnoticed
- Remote member never receives the packet, the ReceiverTasklet will keep
waiting for the DONE_ITEM
The solution is that when the ReceiverTasklet creates data for the flow
control packet, it compares that the Connection object it was crated
with is the same.
We send the flow control packet regularly so any transparent
reconnection will cause the job to fail. …
=> Fix job hanging due to lost DONE_ITEM

hazelcast-jet-core/src/test/java/com/hazelcast/jet/MulticastDiscoveryTest.java
With this [commit](https://github.com/hazelcast/hazelcast-jet/commit/424e109af3709ad860d65230ef7f92ef7c73964a), we've introduced random cluster name to isolate tests.
Looks like we've missed setting the cluster name to client 
Checklist
Fixes #1407
* ..
=> Use the configured cluster name of the instance for client

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ClientJobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobProxy.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/SimpleTestInClusterSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java
- fix when `Job` instance is from non-coordinator and the coordinator
leaves, the job completes. The issue was that in a specific case,
`HazelcastInstanceNotActiveException` was thrown on the
`JoinJobOperation` target member (the master) and the non-coordinator
didn't retry the operation. The fix is to retry the operation in case of
`HazelcastInstanceNotActiveException`, but only if the local member is
running and the exception likely originates on the remote member. Fixes
#2461 
- `AbstractJobProxy.resubmitJob()` and `rejoinJob()` checked
`AbstractJobProxy.memberUuid()` for a `null` result, but it never
actually returned null but threw instead. The fix is to specify a single
exception to throw (the `IllegalStateException`) and fix the code to
check for the exception.
- Unify the code of …
=> Fix AbstractJobProxy issues

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamSourceStageTest.java, site/website/sidebars.json
Test is added as nightly test since it takes more than 15seconds. 
This PR also adds sparse event test plan to left menu on site.
Checklist
=> Add test for not emit windows too early with sparse events

extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcNetworkIntegrationTest.java
The CDC Network tests are not entirely deterministic. For example when we want to test some behaviour during snapshotting mode we rely on timeouts to do a certain action hopefully in that time period, which succeeds most of the time, but not always. This is ok (or better than no tests at all), but we need to make sure to not trigger false positive failures, when we are not in the targeted test state. 
Current pull request addresses a situation where the MySQL connector's internal reconnect mechanism kicks in and tries to reconnect endlessly, instead of our own reconnect mechanism which would throw an error instead.
Fixes #2531
=> Fix CDC network related test timeouts (issue #2531)

extensions/cdc-mysql/pom.xml, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java, extensions/cdc-postgres/pom.xml, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcNetworkIntegrationTest.java
Issue is caused by some kind of cleanup problem, affecting the Ryuk resource reapers. This resource manager is not mandatory, tests already do manual container management, so will disable it. Hopefully the reduced complexity will get rid of the clean-up issues experienced.
Fixes #2534
=> Fix MySql related intermittent network test failures (issue #2534)

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SortBatchStageTest.java
Added test for sort stage for scenarios:
- sorting items where some of the items are the same
- sorting using comparator
- exception during sorting should fail the job with expected exception
- job can finish even if some of `sortP` processors does not get any values for sorting
Checklist
- [N/A] Breaking changes documented
=> Add test for sort batch stage

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Edge.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/EdgeDef.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/SortTransform.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStream_MergeSortDrainTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStream_OrderedDrainTest.java
- fix getter name: setter is `Edge.monotonicOrder()` and the getter is
`Edge.getComparator()`
- the getter and setter also use different type: `ComparatorEx<T>` vs
`ComparatorEx<?>`
- fail cleanly on watermarks or barriers
- improve javadoc
- for `SenderTasklet`, use a comparator that handles
`ObjectWithPartitionId` instead of tentatively unwrapping (a.k.a.
_adapted_ comparator)
- when the item was unwrapped, it was returned unwrapped
- use two subclasses to implement the behavior in CIES
- add unit test
- don't add items to exceptions: it can appear in logs, MC, for security
it should not
=> Improve & fix merge-sorting in CIES

site/website/blog/2020-09-18-cdc-meets-stream-processing.md
Since the Apache License doesn't fully cover Jet and we mention that in the Blog post, we should also add a link to where further information can be found.
=> Add Jet licensing info to CDC blog post

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStream.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStreamTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/ConcurrentInboundEdgeStream_OrderedDrainTest.java
Remove the need to qualify superclass fields with `super` or make them visible to the whole package.
=> Simplify ConcurrentInboundEdgeStream structure

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJetInstance.java
Remove the first config.attachAll() call that is not needed. 
Fixes #2562
Checklist
=> Fix config.attachAll(...) is calling twice when the job is submitted via newJobIfAbsent

extensions/s3/pom.xml, extensions/s3/src/test/java/com/hazelcast/jet/s3/S3MockTest.java, extensions/s3/src/test/java/com/hazelcast/jet/s3/S3SinkTest.java, extensions/s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java
The issue here is that the test code gets the list of keys by asking the s3 server, but when it asks for the value of one of these keys in the next step, the s3 server could not find this key. We can say that seeing a key, then not seeing the same key is an eventual consistency issue in the S3 side (Note: Frantisek showed me this point and said that he also encountered this type of issue during s3 benchmarks. He can help discussions on this topic). Although they say s3 provides eventual consistency, it may not. I added a conditional wait after these key deletions because maybe the key deletions are running slowly.
I am aware that with eventual consistency guarantee, write operations may be reflected after cleanup. But we call cleanup before and after tests. In such a case, the test …
=> Fix S3SinkTest Issue

extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java
There is false positive findbugs failure for JDK 11 (PR builder is running with JDK 8 - that's the reason why it was merged without notice, it was caused by this PR - https://github.com/hazelcast/hazelcast-jet/pull/2564). See build for this PR with JDK 11 here - http://jenkins.hazelcast.com/job/jet-oss-master-oracle-jdk11-temp/
Checklist
- [N/A] Breaking changes documented
=> Suppress false positive RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE

hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperation.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperations.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/DAG.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/Processors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/ItemsByTag.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/KeyedWindowResult.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/Tuple2.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/Tuple3.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/Tuple4.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/Tuple5.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/WindowResult.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/AggregateTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/SortTransform.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/AggregateP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/GroupP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/BatchStage.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/aggregate/AggregateOperationsTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchAggregateTest.java
Even without any input, the aggregation stage must produce its output. 
This PR fixes the behavior of those aggregate operations that can represent an "empty" result (zero sum, empty list), but not of those whose result is `null` without any input (`minBy`, `maxBy`). These operations keep the current behavior of emitting nothing.
Fixes #2560. 
Checklist
=> Fix global aggregation with no input

extensions/cdc-mysql/pom.xml, extensions/cdc-postgres/pom.xml, hazelcast-jet-distribution/src/root/NOTICE
There was a wrong dependency in the CDC implementations, a testing library wasn't properly scoped as `test` and blew up the distribution's extension jar sizes. Fixing it here (for the `master` branch).
=> Fix unintentional increase in CDC jar sizes

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/JetClassLoader.java
Currently JetClassLoader loads the configured classes but does not define their 
packages. According to the javadoc of `ClassLoader#definePackage` it should
be defined prior to definig the class:
```
* Defines a package by name in this <tt>ClassLoader</tt>.  This allows
* class loaders to define the packages for their classes. Packages must
* be created before the class is defined, and package names must be
* unique within a class loader and cannot be redefined or changed once
* created.
```
Not defining the package results in issues for the avro, the implementation
relies on that the package of the class while creating the schema.
Checklist
- [NA] Breaking changes documented …
=> Define package of the class before defining the class in JetClassLoader

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Edge.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/EdgeDef.java
Fixes a soak test issue indicating a classloader leak.
Breaking changes:
* snapshot format: version 4.3 already changes the snapshot format by introducing `Edge.comparator`, this PR additionally changes the order of serialized components
Checklist:
=> Use custom CL for Comparator serialization

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Job.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/JobSuspensionCause.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ClientJobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionRecord.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobProxy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobSuspensionCauseImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetGetJobSuspensionCauseCodec.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetGetJobSuspensionCauseMessageTask.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetInitDataSerializerHook.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobSuspensionCauseOperation.java, hazelcast-jet-core/src/main/resources/client-protocol-definition/Jet.yaml, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SuspendExecutionOnFailureTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/init/JetInitDataSerializerHookTest.java
Attempting to make working programmatically with job suspension cause, for example in MC, less error prone (than relying on specific formatting of Strings).
Breaking changes:
* API
Checklist:
=> Improve safety of working with job suspension cause programmatically

extensions/cdc-mysql/src/main/java/com/hazelcast/jet/cdc/mysql/MySqlCdcSources.java, extensions/cdc-postgres/src/main/java/com/hazelcast/jet/cdc/postgres/PostgresCdcSources.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/retry/RetryStrategies.java
Turns out that the default reconnect interval is too small and can cause problems with the MySQL binary log client. Increased it to 5 seconds. 
Also made some wording changes in the CDC source javadoc, to make the distinction between database snapshotting and Jet's snapshotting clearer.
Checklist:
=> Increase default reconnect interval, improve docs

extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/AbstractCdcIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcNetworkIntegrationTest.java
In our CDC network tests we are doing manual container lifecycle management, for more control. It turned out to be flawed. It was stopping the containers used by the tests, but it wasn't also removing them nor the volumes they created. This PR fixes the problem and also improves the test code a bit. 
Checklist:
=> Improve container cleanup, when done explicitly

extensions/python/src/main/java/com/hazelcast/jet/python/PythonService.java, extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java, extensions/python/src/test/java/com/hazelcast/jet/python/PythonInitCleanupTest.java
Retry initialization of PythonService context
Fixes https://github.com/hazelcast/hazelcast-jet/issues/2585
Breaking changes (list specific methods/types/messages):
* After job finished, the base directory for python is not deleted
Checklist:
- [NA] Updated `examples/README.md` (when adding a new code sample)
=> Retry initialization of PythonService context

extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/AbstractCdcIntegrationTest.java, extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/DebeziumCdcIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/AbstractMySqlCdcIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/AbstractPostgresCdcIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcNetworkIntegrationTest.java
These changes assign names to containers used instantiated for testing. The names are meant to help identify the tests that start a particular container. This should help with identifying the cause of some containers not being cleaned up on Jenkins.
=> Name containers used in tests

extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSource.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadJdbcP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteJdbcP.java
Fixes #2603
To avoid the deadlock we need to ensure `java.sql.DriverManager` has initialized the drivers before trying to use them.
=> Fix JDBC driver initialization deadlock

site/website/all-versions.json
Page https://jet-start.sh/download includes incorrect link release notes. The value is taken from this file. I'm not sure whether it will be updated by our job just by changing this file or it needs to be re-generate. Let's try to fix it by just changing it here.
Checklist:
=> Fix broken 4.3 RN link from download page

extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcNetworkIntegrationTest.java
CDC network tests are still leaking containers on Jenkins.... One situation which could lead to this is when the JVM/OS process running the tests is killed. To solve it I'm going to re-activate the Ryuk resource reaper for the tests. It solves the problem locally, let's see. (I can't really tell if this is what is actually going on usually on Jenkins, when containers get leaked.)
Checklist:
=> Reactivate TestContainers resource reaper in CDC network tests

extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/DebeziumCdcIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/AbstractMySqlCdcIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java
MySQL CDC connector is not able to work when Zulu JDK 15 is used (https://github.com/hazelcast/hazelcast-jet/issues/2623). This is problematic for nightly profile since it causes those tests take too long (see http://jenkins.hazelcast.com/job/jet-oss-master-nightly-zulu-jdk15/) and make nightly jobs unusable. This PR causes those test be ignored if JDK version contains `15.0.1`. We should remove those `Assume`s once it will be fixed. Job which ran with this change - http://jenkins.hazelcast.com/job/jet-oss-master-nightly-zulu-jdk15-temp/3/
Checklist: …
=> Ignore MySql CDC tests with JDK 15

extensions/python/src/main/java/com/hazelcast/jet/python/PythonService.java, extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java, extensions/python/src/test/java/com/hazelcast/jet/python/PythonInitCleanupTest.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorSupplier.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorSupplierContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/Contexts.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java, pom.xml
Adds two new methods to `ProcessorSupplier`: `recreateAttachedDirectory` and `recreateAttachedFile`
Improves on #2586 by recreating the attached directory instead of just repeating the initialization.
Checklist:
=> Improve PythonService init/cleanup

hazelcast-jet-all/pom.xml, pom.xml
Added `net.openhft:affinity` as optional dependency to fix javadoc generation.
Checklist:
=> Fix javadoc generation under JDK 11+.

hazelcast-jet-sql/pom.xml
Added `jaxb-api` test dependency to remediate test failures under JDK 11+.
Cleaned up pom - moved some dependencies that are not needed in compile time to test scope.
Fixes #2644
Checklist:
=> Fix Kafka Avro tests under JDK 11+

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JobConfig.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/logical/LogicalRules.java
Roughly saying, the new rule converts HAVING to WHERE, if possible, e.g.:
```sql
SELECT a FROM t GROUP BY a HAVING b=0
```
to 
```sql
SELECT a FROM t WHERE b=0 GROUP BY a
```
As a result, filtering isn't applied after aggregation, but pushed down to the source.
=> Add `FilterAggregateTransposeRule` rule

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/JetConsoleLogHandler.java, hazelcast-jet-distribution/src/root/release_notes.txt
Jet configures JUL logging with its own console log handler that writes to `System.out`. The handler doesn't override `close()`, so it closes `System.out` when closing itself. Most importantly, this happens during JVM shutdown in a shutdown hook, so other shutdown hooks lose the ability to print messages to the console.
This PR overrides `JetConsoleLogHandler#close()` so it doesn't close its output stream.
Fixes #2649 
Checklist:
=> Avoid closing System.out in JetConsoleLogHandler

hazelcast-jet-distribution/src/root/release_notes.txt, site/website/blog/2020-10-23-jet-43-is-released.md
Every version of Jet inherits all the enhancements and fixes done in the IMDG. So our Release Notes should link to IMDG's.
Checklist:
=> Link to IMDG Release Notes from Jet's

hazelcast-jet-distribution/src/root/release_notes.txt, site/website/blog/2020-10-23-jet-43-is-released.md
IMDG has separate release notes for the Enterprise Edition. Added a link to that as well.
Checklist:
=> Add links to EE release notes

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/JetQueryResultProducer.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/JetQueryResultProducerTest.java
With `JetQueryResultProducer` following execution is possible:
```
------- thread 1 (the iterator consumer)
nextRow != null || (nextRow = queue.poll()) != null // returning false
------- thread 2 (results producer)
consume()
done()
------- thread 1(the iterator consumer)
isDone()
```
As the outcome empty results might be returned to client.
This PR hopefully fixes that race by exhausting internal queue before returning `DONE`.
Fixes #2637
Checklist:
=> Fix spurious empty SQL results

extensions/kafka/pom.xml, hazelcast-jet-sql/pom.xml, pom.xml
Bumped `zookeper` to version 3.5.8 to remediate https://issues.apache.org/jira/browse/ZOOKEEPER-3779
Fixes #2624
Checklist:
=> Fix Kafka tests under JDK14+

extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/AbstractCdcIntegrationTest.java
The "network" CDC tests still experience various container start/stop related failures. While I have no idea of the exact cause (since I can't reproduce the problem), I have found an extra step we can take in these tests, maybe that will help... Lame, but nothing to loose at this point.
Checklist:
=> Unregister manually stopped container from resource reaper

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/MetricsContext.java
Turns out the failures observed in issue #2572 are caused by an exception thrown in `MetricsContext`. It's a NPE caused by non-thread safe data being accessed from multiple threads (one is the thread executing the tasklet, another is the thread doing dynamic metrics collection). This PR attempts to fix the problem.
Fixes #2572 
Checklist:
=> Fix race in MetricsContext

hazelcast-jet-sql/pom.xml, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/extract/JsonQueryTarget.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/inject/JsonUpsertTarget.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlJsonTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/extract/JsonQueryTargetTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/inject/JsonUpsertTargetTest.java
Added support for json as `byte[]`.
Removed dependency to `org.apache.kafka:connect-json`.
Checklist:
=> Support byte[] json objects

extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/AbstractCdcIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcNetworkIntegrationTest.java
Change our approach to the `*CdcNetworkIntegrationTests` in order to get rid of intermittent issues on Jenkins. Remove hacky open port detection.
Fixes #2634 
Fixes #2601 
Checklist:
=> Simplify container start/stop logic and how ports are assigned

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/logical/LogicalRules.java
Added `ReduceExpressionsRule.FILTER_INSTANCE` to the set of logical rules so for instance:
```
LogicalProject(v=[$0])
LogicalFilter(condition=[AND(=($0, 10), IS NULL($0))])
LogicalTableScan(table=[[hazelcast, public, t[projects=[0]]]])
```
results now in:
```
ValuesPhysicalRel(tuples=[[]])
```
instead of:
```
FullScanPhysicalRel(table=[[hazelcast, public, t[projects=[0], filter=AND(=($0, 10), IS NULL($0))]]])
```
Checklist:
=> Use FilterReduceRule

hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetConfigXmlGenerator.java
Apply changes from https://github.com/hazelcast/hazelcast/pull/17842 to Jet config. See IMDG PR for more details.
Checklist:
=> Follow IMDG change: Allow disabling XXE protection

extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java
=> Check if python3 is available before initializing python service context

extensions/kafka/src/main/java/com/hazelcast/jet/kafka/KafkaSources.java
Fixes #2663 
NO Breaking changes.
Checklist:
=> Remove obsolete reference to old default local parallelism in Kafka source javadoc

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/PipelineImpl.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Pipeline.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/PipelineTest.java
Very simple PR which adds Pipeline.isEmpty() method to check if any transformations were added to Pipeline.
Breaking changes (list specific methods/types/messages):
* API - added Pipeline.isEmpty
Checklist:
=> Add Pipeline.isEmpty

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/kafka/KafkaSqlConnector.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/kafka/KafkaTable.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/kafka/PropertiesResolver.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/PropertiesResolverTest.java
Removed Jet specific options from Kafka properties.
Added specific properties resolution for consumer & producer.
Fixes #2715
Checklist:
=> Improve Kafka properties resolution

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/retry/RetryStrategies.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/retry/RetryStrategy.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/retry/impl/RetryStrategyImpl.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/HazelcastConnector_RestartTest.java
My theory on what happened is this: The `MigrationBlockingService`
blocks in the `beforeMigration()` method. It could happen that all
partition threads were blocked and progress was stalled, which would
cause that the `IList.size()` operation will retry many times and
ultimately fail with "Wrong target". I saw the blocked partitions
threads in the thread dump. However, I don't understand why it got stuck
in only about 10% of cases. Also it wasn't failing before. The fix is to
block at most one thread in the `MigrationBlockingService`.
After the fix, second issue happened
Fixes #2657
=> Fix HazelcastConnector_RestartTest

hazelcast-jet-sql/pom.xml
Change the `hazelcast-sql` dependency to the new `hazelcast-sql-core` in `hazelcast-jet-sql` module. The `hazelcast-sql-core` doesn't use the Maven shade plugin with package relocations.
Related Hazelcast PRs:
- hazelcast/hazelcast#17921 (`master`)
- hazelcast/hazelcast#17922 (`4.1.z`)
Checklist:
=> Change hazelcast-sql dependency to use the new non-shaded hazelcast-sql-core

extensions/kafka/src/main/java/com/hazelcast/jet/kafka/impl/StreamKafkaP.java, extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/KafkaPartitionAssignerTest.java, extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/KafkaPartitionAssignmentTest.java, extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/KafkaTestSupport.java, extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/StreamKafkaPTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/MockLoggingFactory.java
We reduced the `poll` timeout from 50ms to 0ms. The consumer receives
records on the background, there's no need to block for more records,
just grab those that are immediately available. This reduces snapshot
latency.
Secondly, it fixes the issue when the `consumer.partitionsFor()` can
block for up to 60 seconds waiting for the metadata in the `init()`
method. We reduced the waiting to 1 second, which can easily not be
enough. As as consequence, we had to adapt the processor to live without
partition information and try to get it later (we already did that when
checking for partitions added at runtime). The major change was that
now, when restoring offsets from the snapshot, we can't rely on
`currentAssignment`, but we'll simply assume the topic has at least as
many partitions as the …
=> Reduce poll and init timeout in Kafka source

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/PeekTransform.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/OrderedBatchParallelismTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/OrderedStreamParallelismTest.java
Fixes #2738 
Since this transform does not generate its own vertex, it got me wrong before. At first, I thought it would be okay if we did not determine LP in this transform, but this broke up LP propagation. I fixed it in this PR.
Checklist:
=> Fix peek transform that previously disrupts LP propagation

extensions/hadoop/src/test/java/com/hazelcast/jet/hadoop/file/ParquetFileFormatTest.java
=> Fix ParquetFileFormatTest.shouldThrowWhenIncorrectSchema

extensions/kafka/src/main/java/com/hazelcast/jet/kafka/impl/StreamKafkaP.java, extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/StreamKafkaPTest.java
* Fix issue with added partitions
This could happen:
- the processor starts with 2 partitions p0 and p1
- p0 has some item, p1 doesn't
- the processor saves a snapshot. It will only save the offset for p0
because it doesn't know it for p1
- the job restarts
- the processor restores offset for p0, but not for p1. Therefore it
will assume the partition count before the restart was 1
- later it will detect that there are 2 partitions and will seek p1 to
the beginning because it will think that p1 was added while the job was
down
The fix is that the processor with global processor index of 0 will save
one additional key to the snapshot, the `PARTITION_COUNTS_SNAPSHOT_KEY`.
Under that key we the known partition count for each topic. That key is
broadcast, every processor will know the …
=> Kafka fixes

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Edge.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/OutboundCollector.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/EdgeDef.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/RoutingPolicyDistributedTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/RoutingPolicyTest.java
Added `FANOUT` routing policy.
For distributed edge case it sends each item to a single processor on each of the cluster members - a combination of `BROADCAST` & `ROUND_ROBIN`. For a local edge case it behaves exactly as `ROUND_ROBIN`.
Useful for optimized `IMap` (SQL) join implementations where single item is being joined with local `IMap` partitions.
Checklist:
=> Add FANOUT routing policy

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/MemberReconnectionStressTest.java
There were two issues:
1. A race when reusing the same `Operation` instance: the
`InvocationRegistry.deactivate` inverts the `Operation.callId` to a
negative number. But this happens after the invocation future is
completed. We had action hooked to the future that sent the operation
again. In most times it managed to deregister the operation before we
tried to set it again, but if not, the invocation failed with "Attempt
to reuse the same operation in multiple invocations." A retry wasn't
sent and the job got stuck.
The fix is to create a new Operation instance for each invocation.
2. The issue would be easy to spot if the exception wasn't swallowed: it
was another instance of using `whenComplete` without logging the
exception in the callback - the `whenComplete` doesn't log the exception …
=> Don't reuse operations and fix error handling

hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/JetProperties.java
Jet is normally used as the `hazelcast-jet` artifact, but `hazelcast-jet-core` is also available, and the user can combine it with any version of the `hazelcast` artifact.
Some users want to use this in order to benefit from a bug fix in IMDG that doesn't influence interoperability with Jet, but the version check in Jet prevents them.
This PR adds a system property that disables the version check.
Checklist:
=> Config option to disable the IMDG version check

pom.xml
This PR updates the version of the imdg dependency to 4.1.1 and corresponding hazelcast plugin versions. 
Checklist:
=> Update IMDG version to 4.1.1

hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/OrderedBatchProcessingTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/OrderedProcessingMergingStagesTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/OrderedProcessingMultipleMemberTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/OrderedStreamProcessingTest.java
This PR aims to improve event reordering functional test suite.
Improvements:
Missing stages are aggregate, and rollingAggregate. Since I don't know how to test the order after the aggregate stages, I will not add tests for them. All of our current aggregate operations are order independent (commutative, associative), therefore I am unable to check whether the order of items entering these stage has changed or not.
Checklist:
=> Event Reordering Functional Test Improvements

hazelcast-jet-all/src/main/java/com/hazelcast/jet/server/JetCommandLine.java
Formerly, the cli was crashing because of the absence of the null check for the column values. This PR adds null check to solve this issue.
Fixes: #2768 
Checklist:
=> Fix sql cli crash

extensions/hadoop/src/main/java/com/hazelcast/jet/hadoop/HadoopSources.java, extensions/hadoop/src/main/java/com/hazelcast/jet/hadoop/impl/HadoopFileSourceFactory.java, extensions/hadoop/src/main/java/com/hazelcast/jet/hadoop/impl/ReadHadoopNewApiP.java, extensions/hadoop/src/main/java/com/hazelcast/jet/hadoop/impl/ReadHadoopOldApiP.java, extensions/hadoop/src/main/java/com/hazelcast/jet/hadoop/impl/ReadHdfsMetaSupplierBase.java, extensions/hadoop/src/test/java/com/hazelcast/jet/hadoop/file/SharedFilesystemFileTest.java, extensions/hadoop/src/test/java/com/hazelcast/jet/hadoop/impl/ReadHadoopPTest.java, extensions/hadoop/src/test/java/com/hazelcast/jet/hadoop/impl/WriteHadoopPTest.java
When reading local files using Hadoop, the source splits the input on one of the members and distributes those splits to other members, ignoring the files on other members. With the fix, source splits the input on all members if the input belongs to local file system. 
We've also introduced a property `HadoopSources.SHARED_LOCAL_FS`. It can be used to mark the local file system as shared (e.g multiple members on a machine).
Checklist:
=> Re-assign InputSplits on members for LocalFileSystem

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/ComputeStageImplBase.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/RebalanceBatchStageTest.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/RebalanceStreamStageTest.java
There was a problem if peek was called after rebalance. This pr solves that issue.
Fixes #2760
Checklist:
=> Fix peek after rebalance issue

extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/KafkaTestSupport.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataAvroResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataJavaResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataJsonResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataResolvers.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/MetadataJsonResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/MetadataPortableResolver.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlAvroTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlJsonTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlPojoTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlPrimitiveTest.java
Multiple issues fixed:
- maybeAddDefaultField() only looked ad key's or value's fields, not at
all user fields. It would add __key for a second time if it is mapped to
value
- if __key is added as a value field, resolvePrimitiveSchema() will just
add it again. Not it leaves the key unmapped (which will fail in case of
imap because it's mandatory, but not in case of kafka)
Fixes #2793
=> Fix double __key column

hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/GeneralStage.java
After #2765 peek is not supported if used after rebalance. This pull request modify peek Javadoc so it's now properly documented that peek after rebalance isn't supported.
Checklist:
=> Modify peek javadoc to show peek after rebalance isn't supported

hazelcast-jet-distribution/src/root/config/jvm.options
Saves time to lookup the exact name of the option, both for the users
and us.
=> Add MaxMetaspaceSize to jvm.options

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataResolvers.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlPrimitiveTest.java
Fixes #2792
I've kept both variants: `keyFormat=bigint` and `keyFormat=java, keyJavaClass=java.lang.Long`. The reason is that there's no type name for all of the supported classes, for example for `java.util.Date`. If you want a `java.util.Date` key, you need to use the longer variant.
This PR doesn't update the refman to avoid conflict with Marko who's working on it.
=> Simpler syntax for primitive key/value

extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/StreamKafkaPTest.java
This happened:
- assertTrueEventually calls the given lambda repeatedly, until no
assert fails. Therefore it could produce multiple records. This is
intentional because our auto.offset.reset is latest and we don't know
where the consumer starts
- on one iteration a record is produced, but sinkList is still empty (it
didn't yet made its way through the pipeline). On a next iteration,
another record was produced, but sinkList contained 1 item, so the
`assertTrueEventually` method returned
- then we suspended the job and cleared the list. However, `job.suspend`
returns before the execution actually terminates. We cleared the list,
but the job was still running and inserted one more item into it
- the test then failed because of an unexpected item in the list
The fix is to not rely on a …
=> Fix when_partitionAddedWhileJobDown test failure

extensions/hadoop/src/main/java/com/hazelcast/jet/hadoop/HadoopSinks.java, extensions/hadoop/src/main/java/com/hazelcast/jet/hadoop/HadoopSources.java, extensions/kafka/src/main/java/com/hazelcast/jet/kafka/KafkaSinks.java, extensions/kafka/src/main/java/com/hazelcast/jet/kafka/KafkaSources.java, extensions/s3/src/main/java/com/hazelcast/jet/s3/S3Sinks.java, extensions/s3/src/main/java/com/hazelcast/jet/s3/S3Sources.java, hazelcast-jet-distribution/src/root/release_notes.txt
Sources and sinks in the core module are named `xyzSource` and `xyzSink` respectively.
Use the same convention in the extensions module as well.
NO breaking API changes, only changed default source/sink names in the extensions module.
Checklist:
=> Ensure naming conventions for sources/sinks in the extensions module

extensions/hadoop/src/test/java/com/hazelcast/jet/hadoop/file/PathAndGlobFileSourceTest.java
=> Clean up in PathAndGlobFileSourceTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteFilePTest.java
There was no locking in
`MasterSnapshotContext.onSnapshotPhase1Complete`. This was possible:
- snapshot 1 is the last successful one
- snapshot 2 was initiated, the phase 1 was successful on member.
`onSnapshotPhase1Complete` was entered on thread `A`. Current
executionId and the executionId from the response were equal
- in another threads, the execution was forcibly restarted,
`finalizeJob` called, new execution started and started and was about to
restore from snapshot 1 (the snapshot 2 wasn't yet marked as successful
by `onSnapshotPhase1Complete`)
- thread `A` continued assuming that snapshot 2 is the new successful
one, cleared the map for snapshot 1
- snapshot 1 was restored from an cleared map - state wasn't restored.
The source started emission from 0 and caused the duplicate …
=> Fix race in snapshot phase 1 completion

examples/cdc/src/main/java/com/hazelcast/jet/examples/cdc/Cache.java, extensions/cdc-debezium/pom.xml, extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/DebeziumCdcIntegrationTest.java, extensions/cdc-mysql/pom.xml, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/AbstractMySqlCdcIntegrationTest.java, extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java, extensions/cdc-postgres/pom.xml, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/AbstractPostgresCdcIntegrationTest.java, extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcNetworkIntegrationTest.java, hazelcast-jet-distribution/src/root/NOTICE
Fixes #2714
Can't reproduce the failure from the issue, have no clue why it happened...
What this PR does is:
* bump up the version of the Docker image we use in the tests (wasn't quite right for the code version we are using)
* bump up the version of the Debezium jars we are using (we were 4 minor versions behind)
Let's see if this helps. Locally all tests work perfectly...
Checklist:
=> Address occasional CDC test failures

site/docs/operations/configuration.md
Creating JetConfig object from existing loader functions were missing from the docs. This pull request adds brief description of configuration loaders and 2 simple examples for creating JetConfig from String using `loadYamlFromString()` function.
Fixes #2779 
Checklist:
- [ x ] Labels and Milestone set
=> Add configuration loaders to docs

hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/SqlClientTest.java
`SqlService.execute()` in jet jobs returns after 1 second if there are
no rows to return. If the failure occurred after that 1 second, then
`execute()` succeeds and the row iteration will fail. This is what
happened here, the fix is to add iteration if the `execute` succeeds.
Fixes #2836
=> Fix SqlClientTest failure

examples/kafka/pom.xml
It's the same fix as https://github.com/hazelcast/hazelcast-jet/commit/360c8ff1.
Checklist:
=> Fix Kafka code sample for JDK14+

hazelcast-jet-sql/pom.xml
This PR adds an empty `hazelast-jet-sql-javadoc.jar` as a workaround for Sonatype's Javadoc release requirements.
Checklist:
=> Workaround for missing hazelcast-jet-sql-javadoc.jar

site/docs/api/sources-sinks.md, site/docs/design-docs/005-cdc-sources.md, site/docs/sql/kafka-connector.md, site/docs/tutorials/kafka.md, site/docs/tutorials/kinesis.md, site/docs/tutorials/python.md, site/website/blog/2021-02-03-jet-44-is-released.md, site/website/versioned_docs/version-4.4/api/sources-sinks.md, site/website/versioned_docs/version-4.4/design-docs/005-cdc-sources.md, site/website/versioned_docs/version-4.4/sql/kafka-connector.md, site/website/versioned_docs/version-4.4/tutorials/kafka.md, site/website/versioned_docs/version-4.4/tutorials/kinesis.md, site/website/versioned_docs/version-4.4/tutorials/python.md
Parts of the documentation were still referencing the `opt` folder of the distribution, which doesn't exist anymore. This PR fixes it.
Checklist:
=> Adapt docs to distribution changes

hazelcast-jet-distribution/pom.xml, hazelcast-jet-distribution/src/root/changelog.txt, hazelcast-jet-distribution/src/root/release_notes.txt, hazelcast-jet-sql/pom.xml
Changes from 4.4 release branch.
Checklist:
=> 4.4 branch changes

hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/validate/SinkTypeCoercionTest.java
Don't insert to IMap value because it doesn't allow nulls. Use non-null
value with a class with a field of the desired type. This also improves
the tests which used to fail with "Writing to top-level fields of type
OBJECT not supported".
Fixes #2894
=> Finish SinkTypeCoercionTest for NULL

hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/kafka/PropertiesResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/JavaClassNameResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataAvroResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataJavaResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataJsonResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataNullResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataResolvers.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/MetadataJsonResolver.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/MetadataPortableResolver.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataJavaResolverTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/keyvalue/KvMetadataResolversTest.java
Removed java serialization specific code from generic `KvMetadataResolvers`.
Removed the necessity to copy (preprocess) options.
=> Cleanup SQL java format/class resolution

hazelcast-jet-sql/src/main/codegen/config.fmpp, hazelcast-jet-sql/src/main/codegen/includes/parserImpls.ftl, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/parse/ParserResource.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/parse/SqlCreateJob.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/parse/SqlCreateMapping.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/SqlJobManagementTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/parse/JetSqlParserTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/schema/SqlMappingTest.java
Forbade `CREATE OR REPLACE MAPPING IF NOT EXISTS`.
Moved validations from `parseImpls.ftl` to respective `validate()`'s.
Fixes #2918
=> Forbid OR REPLACE & IF NOT EXISTS to be used together while creating mapping

examples/files/pom.xml, extensions/cdc-debezium/pom.xml, extensions/cdc-mysql/pom.xml, extensions/cdc-postgres/pom.xml, extensions/elasticsearch/elasticsearch-6/src/root/NOTICE, hazelcast-jet-core/pom.xml, hazelcast-jet-distribution/pom.xml, hazelcast-jet-distribution/src/root/NOTICE, pom.xml
=> Update Jackson version to 2.11.4

extensions/elasticsearch/elasticsearch-6/src/root/NOTICE, hazelcast-jet-distribution/src/root/NOTICE, pom.xml
=> Update Snakeyaml version to 1.26

hazelcast-jet-distribution/src/root/NOTICE, pom.xml
=> Update Kafka to 2.2.2

hazelcast-jet-distribution/src/root/NOTICE, pom.xml
Fixes: https://github.com/hazelcast/hazelcast-jet/issues/2916
Checklist:
=> Update Netty version to 4.1.59.Final

site/docs/tutorials/cdc-join.md, site/website/versioned_docs/version-4.3/tutorials/cdc-join.md, site/website/versioned_docs/version-4.4/tutorials/cdc-join.md
In version 4.3 the CDC event sequence number have been made public in `ChangeRecord`. The CDC tutorials weren't updated accordingly. This is what current PR fixes.
=> Adapt CDC join tutorial to API change

extensions/elasticsearch/elasticsearch-6/pom.xml, extensions/elasticsearch/elasticsearch-6/src/root/NOTICE, extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/ElasticSupport.java
=> Update ElasticSearch-6 to 6.8.14

examples/hadoop/pom.xml, examples/python/pom.xml, examples/source-sink-builder/pom.xml, extensions/elasticsearch/elasticsearch-5/pom.xml, extensions/elasticsearch/elasticsearch-6/pom.xml, extensions/elasticsearch/elasticsearch-6/src/root/NOTICE, extensions/elasticsearch/elasticsearch-7/pom.xml, extensions/grpc/pom.xml, hazelcast-jet-distribution/src/root/NOTICE, pom.xml
Update MySQL Connector to 8.0.20
Update Apache Httpclient to 4.5.13
Update Guava to 30.1-jre
Update Apache Commons Compress to 1.20
Fixes #2915 
Fixes #2911 
Fixes #2910 
Fixes #2908 
Checklist:
=> fix security vulnerabilities

extensions/elasticsearch/elasticsearch-7/pom.xml, hazelcast-jet-distribution/src/root/NOTICE
=> Update ElasticSearch-7 to 7.10.2

hazelcast-jet-distribution/src/root/release_notes.txt
=> Update release notes

hazelcast-jet-core/src/test/java/com/hazelcast/jet/MulticastDiscoveryTest.java
Recently, client started retrying indefinitely.
To fix the test, former cluster connection timeout has been set for the client.
Fixes #2904
=> Set cluster connection timeout for MulticastDiscoveryTest

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/EventTimeMapper.java
1. It's called from https://github.com/hazelcast/hazelcast-jet/blob/2797c7ad3cecffa673e2d6f7ae276777885ad155/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/InsertWatermarksP.java#L63 which accepts Null items
2. It delegates to https://github.com/hazelcast/hazelcast-jet/blob/2797c7ad3cecffa673e2d6f7ae276777885ad155/hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/EventTimeMapper.java#L211 where the item is already annotated with @Nullable
=> Fix nullability annotation in EventTimeMapper

extensions/hadoop/src/test/java/com/hazelcast/jet/hadoop/file/AvroFileFormatTest.java, extensions/hadoop/src/test/java/com/hazelcast/jet/hadoop/file/BaseFileFormatTest.java, extensions/hadoop/src/test/java/com/hazelcast/jet/hadoop/file/JsonFileFormatTest.java
Check for com.fasterxml.. exception fails because a relocated version
is thrown, but non-relocated version is used in tests.
We can't use relocated version in tests because IDE doesn't see it.
Fixes #2941
=> Fix test issue with checking relocated exception

hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobSerializerTest.java
I increased the timeout in this test to make sure something went wrong
when this test fails. This test won't take long when it passes anyway.
Also, added missing Nonnull annotation
Checklist:
=> Increase the timeout in the test that uses observable

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SinkProcessors.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteJdbcP.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/JdbcSinkBuilder.java, hazelcast-jet-distribution/src/root/release_notes.txt
Fixes #2879
The implementation adds a new `batchLimit()` builder method to the `JdbcSinkBuilder` class and the corresponding constructor arguments to the underlying implementation class and meta-suppliers.
I also took the opportunity to add public constants for default values in the `JdbcSinkBuilder` class and improve its Javadoc.
Breaking changes (list specific methods/types/messages):
* The `SinkProcessors.writeJdbcP()` method gained a new argument: `batchLimit`.
* The `WriteJdbcP.metaSupplier()` method gained a new argument `batchLimit`.
I believe the above breaking changes have very minimal impact as I don't think many users call these methods directly.
Checklist:
=> Implement configurable batch size limit in JDBC sink processor

hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/DAG.java, hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/DotTest.java, hazelcast-jet-distribution/src/root/release_notes.txt
Fixes #2878
After studying the codebase and the implications, I decided to implement this fix without passing a `JetConfig` object instance but instead adding a new `defaultQueueSize` method argument. In this way, the `DAG` class remains uncoupled from any Jet instance and the caller is free to pass any value to be used for displaying a default queue size.
The `MasterJobContext.tryStartJob()` method is then adapted to pass the default queue size extracted from the `JetConfig` object of the running instance, similar to how the `defaultParallelism` value is passed.
I also took the opportunity to add some missing `@param` Javadoc annotations and made the `defaultLocalParallelism` argument name consistent across all methods in the `DAG` class.
Breaking changes:
The `DAG.toDotString(int …
=> Fix queue size display in Dot representation when default is changed

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java, hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/processors/RootResultConsumerSink.java
Many exceptions with a warning level were printed when the job was canceled by the user. 
Job cancellation by user is abnormal, but legal action, and user should see corresponding message, not exception stack traces.
This PR introduces such workaround for catching `QueryException` with `CANCELLED_BY_USER` error code.
Closes #2940.
=> Prevent exception stack trace printing when user cancels the job

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadMapOrCacheP.java
Reading from all of the partitions in parallel can cause OOM on the
server-side. We limit the parallel reads to a constant value (5) and
decrease the max fetch size (2048).
Fixes #2926
Checklist:
=> Limit the number of parallel partition reads for map/cache.

extensions/hadoop-dist/files-azure/src/root/NOTICE, extensions/hadoop-dist/files-gcs/src/root/NOTICE, extensions/hadoop-dist/files-s3/src/root/NOTICE, extensions/hadoop-dist/hadoop-all/src/root/NOTICE, extensions/hadoop-dist/pom.xml, extensions/hadoop/pom.xml, hazelcast-jet-distribution/src/root/NOTICE
It seems we actually don't need this dependency.
If it turns out log4j 1.2.x is needed we will add a
compatibility bridge instead.
Fixes #2981
=> Exclude log4j (1.2.x) from hadoop module dependencies

extensions/elasticsearch/elasticsearch-6/src/root/NOTICE, hazelcast-jet-distribution/src/root/NOTICE, pom.xml
When compiled with maven 3.5.x, the enforcer plugin throws an error indicating that we are using the same library with different versions. This PR aims to fix the version of that library.
Checklist:
=> Fix httpcore-nio dependency to 4.4.13

NOTICE, hazelcast-jet-distribution/src/NOTICE.ftl, hazelcast-jet-distribution/src/root/NOTICE
=> Merge content of NOTICE files

hazelcast-jet-distribution/src/root/release_notes.txt, site/website/blog/2021-04-23-jet-45-is-released.md
Checklist:
- N/A Added a line in `hazelcast-jet-distribution/src/root/release_notes.txt` (for any non-trivial fix/enhancement/feature)
- N/A New public APIs have `@Nonnull/@Nullable` annotations
- N/A New public APIs have `@since` tags in Javadoc
=> Release blog post for Jet 4.5

hazelcast-jet-distribution/pom.xml
HZ IMDG 4.2 includes two classes with `import org.jetbrains.annotations.NotNull` which breaks Jet javadoc generation. It can be overcome by adding the dependency to `additionalDependencies` of javadoc plugin. 
Checklist:
=> Fixes to javadoc generation for Jet 4.5

extensions/elasticsearch/elasticsearch-5/pom.xml, extensions/elasticsearch/elasticsearch-6/pom.xml, extensions/elasticsearch/elasticsearch-7/pom.xml, extensions/s3/pom.xml, hazelcast-jet-core/pom.xml
This is already fixed in Platform but missing fix in Jet `4.5-maintenance` branch causes test failures.
Checklist:
=> Update testcontainers to 1.14.3

hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/file/SqlAvroTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/file/SqlCsvTest.java, hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/file/SqlJsonTest.java
There are cases when the cause of a failed job is _stringified_ before reported to the user ([here](https://github.com/hazelcast/hazelcast-jet/blob/2797c7ad3cecffa673e2d6f7ae276777885ad155/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java#L654)).
Replaced usage of `hasMessageEndingWith()` with `hasMessageContaining()` to avoid false negatives.
Fixes #3048
=> Replace usage of hasMessageEndingWith() with hasMessageContaining() in SQL tests

hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/Planner.java, hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/RebalanceBatchStageTest.java
* Add reproducer for rebalance in stage which is later fused
* Set the rebalance flag of fused stage
Co-authored-by: Ufuk Yılmaz <ufuk.yilmaz@hazelcast.com>
(cherry picked from commit 0eb3d1abb80d3d7524f3996d18e967bc2f91a1fe)
=> [BACKPORT] Fix rebalance() nonfunctional before fused stages

site/docs/enterprise/management-center.md, site/website/pages/en/download.js, site/website/versioned_docs/version-4.0/enterprise/installation.md, site/website/versioned_docs/version-4.0/enterprise/management-center.md, site/website/versioned_docs/version-4.1.1/enterprise/installation.md, site/website/versioned_docs/version-4.1.1/enterprise/management-center.md, site/website/versioned_docs/version-4.2/enterprise/installation.md, site/website/versioned_docs/version-4.2/enterprise/management-center.md, site/website/versioned_docs/version-4.3.1/enterprise/installation.md, site/website/versioned_docs/version-4.3.1/enterprise/management-center.md, site/website/versioned_docs/version-4.4/enterprise/installation.md, site/website/versioned_docs/version-4.4/enterprise/management-center.md, site/website/versioned_docs/version-4.5.1/enterprise/installation.md, site/website/versioned_docs/version-4.5.1/enterprise/management-center.md, site/website/versioned_docs/version-4.5/enterprise/installation.md, site/website/versioned_docs/version-4.5/enterprise/management-center.md
Update links to do not link current download machine. See https://hazelcast.atlassian.net/browse/HZ-741 for more details.
=> Decommission download machine - update links

site/website/blog/2021-03-17-billion-events-per-second.md
Fixing dead link generated by https://github.com/hazelcast/big-data-benchmark/pull/19
=> Fixing dead link

extensions/grpc/src/main/resources/NOTICE, extensions/hadoop-dist/files-azure/src/main/resources/NOTICE, extensions/hadoop-dist/files-gcs/src/main/resources/NOTICE, extensions/hadoop-dist/files-s3/src/main/resources/NOTICE, extensions/hadoop-dist/hadoop-all/src/main/resources/NOTICE, extensions/hadoop-dist/src/main/resources/NOTICE, extensions/python/src/main/resources/NOTICE, hazelcast-jet-distribution/src/root/NOTICE, pom.xml
Fixes gRPC Python requirement and Woodstox CVE
Fixes #3129
Checklist:
=> Downgrade gRPC and upgrade Woodstox
